version: '3.8'

services:
  postgres-db:
    image: postgres:17
    container_name: kubo-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: kw29zxu12001
      POSTGRES_DB: kubo-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

  