create table creditos_integracion (
    id SERIAL PRIMARY KEY,
    cve_dda VARCHAR(1),
    no_nota VARCHAR(10),
    tip_not VARCHAR(13),
    fecha TIMESTAMP,
    no_fac VARCHAR(10),
    no_cliente INTEGER,
    no_agente INTEGER,
    no_estado VARCHAR(10),
    tot_imp NUMERIC(20,6),
    subtotal NUMERIC(20,2),
    desc_not NUMERIC(12,2),
    tot_nota NUMERIC(20,2),
    num INTEGER,
    saldo NUMERIC(20,2),
    tot_des NUMERIC(20,6),
    lugar VARCHAR(10),
    cve_factu VARCHAR(3),
    cve_mon INTEGER,
    tip_cam NUMERIC(10,4),
    cve_suc VARCHAR(3),
    mes VARCHAR(2),
    aqo VARCHAR(4),
    usuario INTEGER,
    trans INTEGER,
    CONSTRAINT unique_cre_cve_factu UNIQUE (no_fac,cve_factu)   
);