ALTER TABLE productos_padre
ADD COLUMN IF NOT EXISTS foto_url_4 TEXT,
ADD COLUMN IF NOT EXISTS foto_url_5 TEXT,
ADD COLUMN IF NOT EXISTS foto_url_6 TEXT,
ADD COLUMN IF NOT EXISTS foto_url_7 TEXT,
ADD COLUMN IF NOT EXISTS foto_url_8 TEXT;