// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const obtenerIngresosMensuales = `-- name: ObtenerIngresosMensuales :many
SELECT
    EXTRACT(YEAR FROM created_at)::int AS anio,
    EXTRACT(MONTH FROM created_at)::int AS mes,
    CAST(COALESCE(SUM(monto_total), 0) AS DECIMAL(15,2)) AS total
FROM pagos_facturas
WHERE created_at >= CURRENT_TIMESTAMP - INTERVAL '6 months'
GROUP BY anio, mes
ORDER BY anio, mes
`

type ObtenerIngresosMensualesRow struct {
	Anio  int32          `json:"anio"`
	Mes   int32          `json:"mes"`
	Total pgtype.Numeric `json:"total"`
}

func (q *Queries) ObtenerIngresosMensuales(ctx context.Context) ([]ObtenerIngresosMensualesRow, error) {
	rows, err := q.db.Query(ctx, obtenerIngresosMensuales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObtenerIngresosMensualesRow
	for rows.Next() {
		var i ObtenerIngresosMensualesRow
		if err := rows.Scan(&i.Anio, &i.Mes, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerIngresosRecientes = `-- name: ObtenerIngresosRecientes :one
SELECT
    CAST(COALESCE(SUM(monto_total), 0) AS DECIMAL(15,2)) AS total_ingresos,
    COUNT(*)::bigint AS total_pagos
FROM pagos_facturas
WHERE created_at >= CURRENT_TIMESTAMP - INTERVAL '30 days'
`

type ObtenerIngresosRecientesRow struct {
	TotalIngresos pgtype.Numeric `json:"total_ingresos"`
	TotalPagos    int64          `json:"total_pagos"`
}

func (q *Queries) ObtenerIngresosRecientes(ctx context.Context) (ObtenerIngresosRecientesRow, error) {
	row := q.db.QueryRow(ctx, obtenerIngresosRecientes)
	var i ObtenerIngresosRecientesRow
	err := row.Scan(&i.TotalIngresos, &i.TotalPagos)
	return i, err
}

const obtenerStatsBackorders = `-- name: ObtenerStatsBackorders :one
SELECT
    COUNT(*)::bigint AS total_backorders,
    COALESCE(SUM(total_orden), 0)::DECIMAL(15,2) AS monto_retenido
FROM backorders
WHERE deleted_at IS NULL
  AND estado_backorder IN ('Pendiente', 'Stock Disponible')
`

type ObtenerStatsBackordersRow struct {
	TotalBackorders int64          `json:"total_backorders"`
	MontoRetenido   pgtype.Numeric `json:"monto_retenido"`
}

func (q *Queries) ObtenerStatsBackorders(ctx context.Context) (ObtenerStatsBackordersRow, error) {
	row := q.db.QueryRow(ctx, obtenerStatsBackorders)
	var i ObtenerStatsBackordersRow
	err := row.Scan(&i.TotalBackorders, &i.MontoRetenido)
	return i, err
}

const obtenerStatsDevoluciones = `-- name: ObtenerStatsDevoluciones :one
SELECT
    COUNT(*) FILTER (WHERE estatus = 'Pendiente')::bigint AS pendientes,
    COUNT(*) FILTER (WHERE estatus = 'Aprobada')::bigint AS aprobadas,
    COUNT(*) FILTER (WHERE estatus = 'Rechazada')::bigint AS rechazadas,
    COUNT(*) FILTER (WHERE estatus = 'Cancelada')::bigint AS canceladas
FROM devoluciones_garantias
WHERE deleted_at IS NULL
`

type ObtenerStatsDevolucionesRow struct {
	Pendientes int64 `json:"pendientes"`
	Aprobadas  int64 `json:"aprobadas"`
	Rechazadas int64 `json:"rechazadas"`
	Canceladas int64 `json:"canceladas"`
}

func (q *Queries) ObtenerStatsDevoluciones(ctx context.Context) (ObtenerStatsDevolucionesRow, error) {
	row := q.db.QueryRow(ctx, obtenerStatsDevoluciones)
	var i ObtenerStatsDevolucionesRow
	err := row.Scan(
		&i.Pendientes,
		&i.Aprobadas,
		&i.Rechazadas,
		&i.Canceladas,
	)
	return i, err
}

const obtenerStatsFacturas = `-- name: ObtenerStatsFacturas :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN f_pago < CURRENT_TIMESTAMP AND saldo_fac > 0 THEN saldo_fac ELSE 0 END), 0) AS DECIMAL(15,2)) AS cartera_vencida,
    CAST(COALESCE(SUM(CASE WHEN saldo_fac > 0 THEN saldo_fac ELSE 0 END), 0) AS DECIMAL(15,2)) AS saldo_pendiente_total
FROM facturas_integracion
`

type ObtenerStatsFacturasRow struct {
	CarteraVencida      pgtype.Numeric `json:"cartera_vencida"`
	SaldoPendienteTotal pgtype.Numeric `json:"saldo_pendiente_total"`
}

func (q *Queries) ObtenerStatsFacturas(ctx context.Context) (ObtenerStatsFacturasRow, error) {
	row := q.db.QueryRow(ctx, obtenerStatsFacturas)
	var i ObtenerStatsFacturasRow
	err := row.Scan(&i.CarteraVencida, &i.SaldoPendienteTotal)
	return i, err
}

const obtenerStatsInventario = `-- name: ObtenerStatsInventario :one
SELECT
    COUNT(*)::bigint AS total_variantes,
    COUNT(*) FILTER (WHERE stock_actual = 0)::bigint AS sin_stock,
    COUNT(*) FILTER (WHERE stock_actual > 0 AND stock_actual < 10)::bigint AS stock_bajo
FROM productos_variantes
WHERE deleted_at IS NULL
`

type ObtenerStatsInventarioRow struct {
	TotalVariantes int64 `json:"total_variantes"`
	SinStock       int64 `json:"sin_stock"`
	StockBajo      int64 `json:"stock_bajo"`
}

func (q *Queries) ObtenerStatsInventario(ctx context.Context) (ObtenerStatsInventarioRow, error) {
	row := q.db.QueryRow(ctx, obtenerStatsInventario)
	var i ObtenerStatsInventarioRow
	err := row.Scan(&i.TotalVariantes, &i.SinStock, &i.StockBajo)
	return i, err
}

const obtenerStatsPedidos = `-- name: ObtenerStatsPedidos :one
SELECT
    COUNT(*)::bigint AS total_pedidos,
    COALESCE(SUM(total_orden), 0)::DECIMAL(15,2) AS monto_total_ordenes
FROM pedidos
WHERE deleted_at IS NULL
`

type ObtenerStatsPedidosRow struct {
	TotalPedidos      int64          `json:"total_pedidos"`
	MontoTotalOrdenes pgtype.Numeric `json:"monto_total_ordenes"`
}

func (q *Queries) ObtenerStatsPedidos(ctx context.Context) (ObtenerStatsPedidosRow, error) {
	row := q.db.QueryRow(ctx, obtenerStatsPedidos)
	var i ObtenerStatsPedidosRow
	err := row.Scan(&i.TotalPedidos, &i.MontoTotalOrdenes)
	return i, err
}
