// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backorders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarEstadoBackorder = `-- name: ActualizarEstadoBackorder :one
UPDATE backorders
SET
    estado_backorder = $2,
    guia_backorder = $4,
    notas_admin_backorder = $5,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, folio, cliente_id, usuario_id, estado_backorder, metodo_pago, subtotal, iva, total_orden, guia_backorder, notas_admin_backorder, pedido_origen_id, fecha_backorder, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type ActualizarEstadoBackorderParams struct {
	ID                  int32       `json:"id"`
	EstadoBackorder     string      `json:"estado_backorder"`
	UpdatedBy           pgtype.Int4 `json:"updated_by"`
	GuiaBackorder       pgtype.Text `json:"guia_backorder"`
	NotasAdminBackorder pgtype.Text `json:"notas_admin_backorder"`
}

func (q *Queries) ActualizarEstadoBackorder(ctx context.Context, arg ActualizarEstadoBackorderParams) (Backorder, error) {
	row := q.db.QueryRow(ctx, actualizarEstadoBackorder,
		arg.ID,
		arg.EstadoBackorder,
		arg.UpdatedBy,
		arg.GuiaBackorder,
		arg.NotasAdminBackorder,
	)
	var i Backorder
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.UsuarioID,
		&i.EstadoBackorder,
		&i.MetodoPago,
		&i.Subtotal,
		&i.Iva,
		&i.TotalOrden,
		&i.GuiaBackorder,
		&i.NotasAdminBackorder,
		&i.PedidoOrigenID,
		&i.FechaBackorder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const crearBackorder = `-- name: CrearBackorder :one
INSERT INTO backorders (
    folio,
    cliente_id,
    usuario_id,
    estado_backorder,
    metodo_pago,
    subtotal,
    iva,
    total_orden,
    guia_backorder,
    notas_admin_backorder,
    pedido_origen_id,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, folio, cliente_id, usuario_id, estado_backorder, metodo_pago, subtotal, iva, total_orden, guia_backorder, notas_admin_backorder, pedido_origen_id, fecha_backorder, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CrearBackorderParams struct {
	Folio               string         `json:"folio"`
	ClienteID           pgtype.Int4    `json:"cliente_id"`
	UsuarioID           pgtype.Int4    `json:"usuario_id"`
	EstadoBackorder     string         `json:"estado_backorder"`
	MetodoPago          string         `json:"metodo_pago"`
	Subtotal            pgtype.Numeric `json:"subtotal"`
	Iva                 pgtype.Numeric `json:"iva"`
	TotalOrden          pgtype.Numeric `json:"total_orden"`
	GuiaBackorder       pgtype.Text    `json:"guia_backorder"`
	NotasAdminBackorder pgtype.Text    `json:"notas_admin_backorder"`
	PedidoOrigenID      pgtype.Int4    `json:"pedido_origen_id"`
	CreatedBy           pgtype.Int4    `json:"created_by"`
}

func (q *Queries) CrearBackorder(ctx context.Context, arg CrearBackorderParams) (Backorder, error) {
	row := q.db.QueryRow(ctx, crearBackorder,
		arg.Folio,
		arg.ClienteID,
		arg.UsuarioID,
		arg.EstadoBackorder,
		arg.MetodoPago,
		arg.Subtotal,
		arg.Iva,
		arg.TotalOrden,
		arg.GuiaBackorder,
		arg.NotasAdminBackorder,
		arg.PedidoOrigenID,
		arg.CreatedBy,
	)
	var i Backorder
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.UsuarioID,
		&i.EstadoBackorder,
		&i.MetodoPago,
		&i.Subtotal,
		&i.Iva,
		&i.TotalOrden,
		&i.GuiaBackorder,
		&i.NotasAdminBackorder,
		&i.PedidoOrigenID,
		&i.FechaBackorder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const crearBackorderDetalle = `-- name: CrearBackorderDetalle :one
INSERT INTO backorder_detalles (
    backorder_id,
    variante_id,
    cantidad,
    precio_unitario_aplicado,
    disponible,
    created_by
) VALUES (
    $1, $2, $3, $4, FALSE, $5
) RETURNING id, backorder_id, variante_id, cantidad, precio_unitario_aplicado, disponible, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CrearBackorderDetalleParams struct {
	BackorderID            pgtype.Int4    `json:"backorder_id"`
	VarianteID             pgtype.Int4    `json:"variante_id"`
	Cantidad               int32          `json:"cantidad"`
	PrecioUnitarioAplicado pgtype.Numeric `json:"precio_unitario_aplicado"`
	CreatedBy              pgtype.Int4    `json:"created_by"`
}

func (q *Queries) CrearBackorderDetalle(ctx context.Context, arg CrearBackorderDetalleParams) (BackorderDetalle, error) {
	row := q.db.QueryRow(ctx, crearBackorderDetalle,
		arg.BackorderID,
		arg.VarianteID,
		arg.Cantidad,
		arg.PrecioUnitarioAplicado,
		arg.CreatedBy,
	)
	var i BackorderDetalle
	err := row.Scan(
		&i.ID,
		&i.BackorderID,
		&i.VarianteID,
		&i.Cantidad,
		&i.PrecioUnitarioAplicado,
		&i.Disponible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getBackorder = `-- name: GetBackorder :one
SELECT b.id, b.folio, b.cliente_id, b.usuario_id, b.estado_backorder, b.metodo_pago, b.subtotal, b.iva, b.total_orden, b.guia_backorder, b.notas_admin_backorder, b.pedido_origen_id, b.fecha_backorder, b.created_at, b.updated_at, b.deleted_at, b.created_by, b.updated_by, b.deleted_by, COALESCE(p.folio, '') AS pedido_origen_folio
FROM backorders b
LEFT JOIN pedidos p ON b.pedido_origen_id = p.id
WHERE b.id = $1 AND b.deleted_at IS NULL LIMIT 1
`

type GetBackorderRow struct {
	ID                  int32            `json:"id"`
	Folio               string           `json:"folio"`
	ClienteID           pgtype.Int4      `json:"cliente_id"`
	UsuarioID           pgtype.Int4      `json:"usuario_id"`
	EstadoBackorder     string           `json:"estado_backorder"`
	MetodoPago          string           `json:"metodo_pago"`
	Subtotal            pgtype.Numeric   `json:"subtotal"`
	Iva                 pgtype.Numeric   `json:"iva"`
	TotalOrden          pgtype.Numeric   `json:"total_orden"`
	GuiaBackorder       pgtype.Text      `json:"guia_backorder"`
	NotasAdminBackorder pgtype.Text      `json:"notas_admin_backorder"`
	PedidoOrigenID      pgtype.Int4      `json:"pedido_origen_id"`
	FechaBackorder      pgtype.Timestamp `json:"fecha_backorder"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
	CreatedBy           pgtype.Int4      `json:"created_by"`
	UpdatedBy           pgtype.Int4      `json:"updated_by"`
	DeletedBy           pgtype.Int4      `json:"deleted_by"`
	PedidoOrigenFolio   string           `json:"pedido_origen_folio"`
}

func (q *Queries) GetBackorder(ctx context.Context, id int32) (GetBackorderRow, error) {
	row := q.db.QueryRow(ctx, getBackorder, id)
	var i GetBackorderRow
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.UsuarioID,
		&i.EstadoBackorder,
		&i.MetodoPago,
		&i.Subtotal,
		&i.Iva,
		&i.TotalOrden,
		&i.GuiaBackorder,
		&i.NotasAdminBackorder,
		&i.PedidoOrigenID,
		&i.FechaBackorder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.PedidoOrigenFolio,
	)
	return i, err
}

const getBackorderByFolio = `-- name: GetBackorderByFolio :one
SELECT b.id, b.folio, b.cliente_id, b.usuario_id, b.estado_backorder, b.metodo_pago, b.subtotal, b.iva, b.total_orden, b.guia_backorder, b.notas_admin_backorder, b.pedido_origen_id, b.fecha_backorder, b.created_at, b.updated_at, b.deleted_at, b.created_by, b.updated_by, b.deleted_by, COALESCE(p.folio, '') AS pedido_origen_folio
FROM backorders b
LEFT JOIN pedidos p ON b.pedido_origen_id = p.id
WHERE b.folio = $1 AND b.deleted_at IS NULL LIMIT 1
`

type GetBackorderByFolioRow struct {
	ID                  int32            `json:"id"`
	Folio               string           `json:"folio"`
	ClienteID           pgtype.Int4      `json:"cliente_id"`
	UsuarioID           pgtype.Int4      `json:"usuario_id"`
	EstadoBackorder     string           `json:"estado_backorder"`
	MetodoPago          string           `json:"metodo_pago"`
	Subtotal            pgtype.Numeric   `json:"subtotal"`
	Iva                 pgtype.Numeric   `json:"iva"`
	TotalOrden          pgtype.Numeric   `json:"total_orden"`
	GuiaBackorder       pgtype.Text      `json:"guia_backorder"`
	NotasAdminBackorder pgtype.Text      `json:"notas_admin_backorder"`
	PedidoOrigenID      pgtype.Int4      `json:"pedido_origen_id"`
	FechaBackorder      pgtype.Timestamp `json:"fecha_backorder"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
	CreatedBy           pgtype.Int4      `json:"created_by"`
	UpdatedBy           pgtype.Int4      `json:"updated_by"`
	DeletedBy           pgtype.Int4      `json:"deleted_by"`
	PedidoOrigenFolio   string           `json:"pedido_origen_folio"`
}

func (q *Queries) GetBackorderByFolio(ctx context.Context, folio string) (GetBackorderByFolioRow, error) {
	row := q.db.QueryRow(ctx, getBackorderByFolio, folio)
	var i GetBackorderByFolioRow
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.UsuarioID,
		&i.EstadoBackorder,
		&i.MetodoPago,
		&i.Subtotal,
		&i.Iva,
		&i.TotalOrden,
		&i.GuiaBackorder,
		&i.NotasAdminBackorder,
		&i.PedidoOrigenID,
		&i.FechaBackorder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.PedidoOrigenFolio,
	)
	return i, err
}

const getBackorderDetalles = `-- name: GetBackorderDetalles :many
SELECT d.id, d.backorder_id, d.variante_id, d.cantidad, d.precio_unitario_aplicado, d.disponible,
       d.created_at, d.updated_at, d.deleted_at, d.created_by, d.updated_by, d.deleted_by,
       v.sku AS variante_sku,
       p.descripcion AS padre_descripcion,
       p.descripcion_extendida AS padre_descripcion_extendida,
       p.foto_url AS padre_foto_url
FROM backorder_detalles d
LEFT JOIN productos_variantes v ON d.variante_id = v.id
LEFT JOIN productos_padre p ON v.padre_id = p.id
WHERE d.backorder_id = $1 AND d.deleted_at IS NULL
`

type GetBackorderDetallesRow struct {
	ID                        int32            `json:"id"`
	BackorderID               pgtype.Int4      `json:"backorder_id"`
	VarianteID                pgtype.Int4      `json:"variante_id"`
	Cantidad                  int32            `json:"cantidad"`
	PrecioUnitarioAplicado    pgtype.Numeric   `json:"precio_unitario_aplicado"`
	Disponible                bool             `json:"disponible"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
	UpdatedAt                 pgtype.Timestamp `json:"updated_at"`
	DeletedAt                 pgtype.Timestamp `json:"deleted_at"`
	CreatedBy                 pgtype.Int4      `json:"created_by"`
	UpdatedBy                 pgtype.Int4      `json:"updated_by"`
	DeletedBy                 pgtype.Int4      `json:"deleted_by"`
	VarianteSku               pgtype.Text      `json:"variante_sku"`
	PadreDescripcion          pgtype.Text      `json:"padre_descripcion"`
	PadreDescripcionExtendida pgtype.Text      `json:"padre_descripcion_extendida"`
	PadreFotoUrl              pgtype.Text      `json:"padre_foto_url"`
}

func (q *Queries) GetBackorderDetalles(ctx context.Context, backorderID pgtype.Int4) ([]GetBackorderDetallesRow, error) {
	rows, err := q.db.Query(ctx, getBackorderDetalles, backorderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBackorderDetallesRow
	for rows.Next() {
		var i GetBackorderDetallesRow
		if err := rows.Scan(
			&i.ID,
			&i.BackorderID,
			&i.VarianteID,
			&i.Cantidad,
			&i.PrecioUnitarioAplicado,
			&i.Disponible,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.VarianteSku,
			&i.PadreDescripcion,
			&i.PadreDescripcionExtendida,
			&i.PadreFotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarBackorders = `-- name: ListarBackorders :many
SELECT b.id, b.folio, b.cliente_id, b.usuario_id, b.estado_backorder, b.metodo_pago, b.subtotal, b.iva, b.total_orden, b.guia_backorder, b.notas_admin_backorder, b.pedido_origen_id, b.fecha_backorder, b.created_at, b.updated_at, b.deleted_at, b.created_by, b.updated_by, b.deleted_by, COALESCE(p.folio, '') AS pedido_origen_folio
FROM backorders b
LEFT JOIN pedidos p ON b.pedido_origen_id = p.id
WHERE b.deleted_at IS NULL
ORDER BY b.created_at DESC
`

type ListarBackordersRow struct {
	ID                  int32            `json:"id"`
	Folio               string           `json:"folio"`
	ClienteID           pgtype.Int4      `json:"cliente_id"`
	UsuarioID           pgtype.Int4      `json:"usuario_id"`
	EstadoBackorder     string           `json:"estado_backorder"`
	MetodoPago          string           `json:"metodo_pago"`
	Subtotal            pgtype.Numeric   `json:"subtotal"`
	Iva                 pgtype.Numeric   `json:"iva"`
	TotalOrden          pgtype.Numeric   `json:"total_orden"`
	GuiaBackorder       pgtype.Text      `json:"guia_backorder"`
	NotasAdminBackorder pgtype.Text      `json:"notas_admin_backorder"`
	PedidoOrigenID      pgtype.Int4      `json:"pedido_origen_id"`
	FechaBackorder      pgtype.Timestamp `json:"fecha_backorder"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
	CreatedBy           pgtype.Int4      `json:"created_by"`
	UpdatedBy           pgtype.Int4      `json:"updated_by"`
	DeletedBy           pgtype.Int4      `json:"deleted_by"`
	PedidoOrigenFolio   string           `json:"pedido_origen_folio"`
}

func (q *Queries) ListarBackorders(ctx context.Context) ([]ListarBackordersRow, error) {
	rows, err := q.db.Query(ctx, listarBackorders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarBackordersRow
	for rows.Next() {
		var i ListarBackordersRow
		if err := rows.Scan(
			&i.ID,
			&i.Folio,
			&i.ClienteID,
			&i.UsuarioID,
			&i.EstadoBackorder,
			&i.MetodoPago,
			&i.Subtotal,
			&i.Iva,
			&i.TotalOrden,
			&i.GuiaBackorder,
			&i.NotasAdminBackorder,
			&i.PedidoOrigenID,
			&i.FechaBackorder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.PedidoOrigenFolio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarBackordersPorCliente = `-- name: ListarBackordersPorCliente :many
SELECT b.id, b.folio, b.cliente_id, b.usuario_id, b.estado_backorder, b.metodo_pago, b.subtotal, b.iva, b.total_orden, b.guia_backorder, b.notas_admin_backorder, b.pedido_origen_id, b.fecha_backorder, b.created_at, b.updated_at, b.deleted_at, b.created_by, b.updated_by, b.deleted_by, COALESCE(p.folio, '') AS pedido_origen_folio
FROM backorders b
LEFT JOIN pedidos p ON b.pedido_origen_id = p.id
WHERE b.cliente_id = $1 AND b.deleted_at IS NULL
ORDER BY b.created_at DESC
`

type ListarBackordersPorClienteRow struct {
	ID                  int32            `json:"id"`
	Folio               string           `json:"folio"`
	ClienteID           pgtype.Int4      `json:"cliente_id"`
	UsuarioID           pgtype.Int4      `json:"usuario_id"`
	EstadoBackorder     string           `json:"estado_backorder"`
	MetodoPago          string           `json:"metodo_pago"`
	Subtotal            pgtype.Numeric   `json:"subtotal"`
	Iva                 pgtype.Numeric   `json:"iva"`
	TotalOrden          pgtype.Numeric   `json:"total_orden"`
	GuiaBackorder       pgtype.Text      `json:"guia_backorder"`
	NotasAdminBackorder pgtype.Text      `json:"notas_admin_backorder"`
	PedidoOrigenID      pgtype.Int4      `json:"pedido_origen_id"`
	FechaBackorder      pgtype.Timestamp `json:"fecha_backorder"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
	CreatedBy           pgtype.Int4      `json:"created_by"`
	UpdatedBy           pgtype.Int4      `json:"updated_by"`
	DeletedBy           pgtype.Int4      `json:"deleted_by"`
	PedidoOrigenFolio   string           `json:"pedido_origen_folio"`
}

func (q *Queries) ListarBackordersPorCliente(ctx context.Context, clienteID pgtype.Int4) ([]ListarBackordersPorClienteRow, error) {
	rows, err := q.db.Query(ctx, listarBackordersPorCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarBackordersPorClienteRow
	for rows.Next() {
		var i ListarBackordersPorClienteRow
		if err := rows.Scan(
			&i.ID,
			&i.Folio,
			&i.ClienteID,
			&i.UsuarioID,
			&i.EstadoBackorder,
			&i.MetodoPago,
			&i.Subtotal,
			&i.Iva,
			&i.TotalOrden,
			&i.GuiaBackorder,
			&i.NotasAdminBackorder,
			&i.PedidoOrigenID,
			&i.FechaBackorder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.PedidoOrigenFolio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarBackordersPorClienteRango = `-- name: ListarBackordersPorClienteRango :many
SELECT b.id, b.folio, b.cliente_id, b.usuario_id, b.estado_backorder, b.metodo_pago, b.subtotal, b.iva, b.total_orden, b.guia_backorder, b.notas_admin_backorder, b.pedido_origen_id, b.fecha_backorder, b.created_at, b.updated_at, b.deleted_at, b.created_by, b.updated_by, b.deleted_by, COALESCE(p.folio, '') AS pedido_origen_folio
FROM backorders b
LEFT JOIN pedidos p ON b.pedido_origen_id = p.id
WHERE b.cliente_id = $1 AND b.deleted_at IS NULL
  AND b.created_at >= $2
  AND b.created_at <= $3
ORDER BY b.created_at DESC
`

type ListarBackordersPorClienteRangoParams struct {
	ClienteID   pgtype.Int4      `json:"cliente_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

type ListarBackordersPorClienteRangoRow struct {
	ID                  int32            `json:"id"`
	Folio               string           `json:"folio"`
	ClienteID           pgtype.Int4      `json:"cliente_id"`
	UsuarioID           pgtype.Int4      `json:"usuario_id"`
	EstadoBackorder     string           `json:"estado_backorder"`
	MetodoPago          string           `json:"metodo_pago"`
	Subtotal            pgtype.Numeric   `json:"subtotal"`
	Iva                 pgtype.Numeric   `json:"iva"`
	TotalOrden          pgtype.Numeric   `json:"total_orden"`
	GuiaBackorder       pgtype.Text      `json:"guia_backorder"`
	NotasAdminBackorder pgtype.Text      `json:"notas_admin_backorder"`
	PedidoOrigenID      pgtype.Int4      `json:"pedido_origen_id"`
	FechaBackorder      pgtype.Timestamp `json:"fecha_backorder"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
	CreatedBy           pgtype.Int4      `json:"created_by"`
	UpdatedBy           pgtype.Int4      `json:"updated_by"`
	DeletedBy           pgtype.Int4      `json:"deleted_by"`
	PedidoOrigenFolio   string           `json:"pedido_origen_folio"`
}

func (q *Queries) ListarBackordersPorClienteRango(ctx context.Context, arg ListarBackordersPorClienteRangoParams) ([]ListarBackordersPorClienteRangoRow, error) {
	rows, err := q.db.Query(ctx, listarBackordersPorClienteRango, arg.ClienteID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarBackordersPorClienteRangoRow
	for rows.Next() {
		var i ListarBackordersPorClienteRangoRow
		if err := rows.Scan(
			&i.ID,
			&i.Folio,
			&i.ClienteID,
			&i.UsuarioID,
			&i.EstadoBackorder,
			&i.MetodoPago,
			&i.Subtotal,
			&i.Iva,
			&i.TotalOrden,
			&i.GuiaBackorder,
			&i.NotasAdminBackorder,
			&i.PedidoOrigenID,
			&i.FechaBackorder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.PedidoOrigenFolio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarBackordersPorRango = `-- name: ListarBackordersPorRango :many
SELECT b.id, b.folio, b.cliente_id, b.usuario_id, b.estado_backorder, b.metodo_pago, b.subtotal, b.iva, b.total_orden, b.guia_backorder, b.notas_admin_backorder, b.pedido_origen_id, b.fecha_backorder, b.created_at, b.updated_at, b.deleted_at, b.created_by, b.updated_by, b.deleted_by, COALESCE(p.folio, '') AS pedido_origen_folio
FROM backorders b
LEFT JOIN pedidos p ON b.pedido_origen_id = p.id
WHERE b.deleted_at IS NULL
  AND b.created_at >= $1
  AND b.created_at <= $2
ORDER BY b.created_at DESC
`

type ListarBackordersPorRangoParams struct {
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

type ListarBackordersPorRangoRow struct {
	ID                  int32            `json:"id"`
	Folio               string           `json:"folio"`
	ClienteID           pgtype.Int4      `json:"cliente_id"`
	UsuarioID           pgtype.Int4      `json:"usuario_id"`
	EstadoBackorder     string           `json:"estado_backorder"`
	MetodoPago          string           `json:"metodo_pago"`
	Subtotal            pgtype.Numeric   `json:"subtotal"`
	Iva                 pgtype.Numeric   `json:"iva"`
	TotalOrden          pgtype.Numeric   `json:"total_orden"`
	GuiaBackorder       pgtype.Text      `json:"guia_backorder"`
	NotasAdminBackorder pgtype.Text      `json:"notas_admin_backorder"`
	PedidoOrigenID      pgtype.Int4      `json:"pedido_origen_id"`
	FechaBackorder      pgtype.Timestamp `json:"fecha_backorder"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
	CreatedBy           pgtype.Int4      `json:"created_by"`
	UpdatedBy           pgtype.Int4      `json:"updated_by"`
	DeletedBy           pgtype.Int4      `json:"deleted_by"`
	PedidoOrigenFolio   string           `json:"pedido_origen_folio"`
}

func (q *Queries) ListarBackordersPorRango(ctx context.Context, arg ListarBackordersPorRangoParams) ([]ListarBackordersPorRangoRow, error) {
	rows, err := q.db.Query(ctx, listarBackordersPorRango, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarBackordersPorRangoRow
	for rows.Next() {
		var i ListarBackordersPorRangoRow
		if err := rows.Scan(
			&i.ID,
			&i.Folio,
			&i.ClienteID,
			&i.UsuarioID,
			&i.EstadoBackorder,
			&i.MetodoPago,
			&i.Subtotal,
			&i.Iva,
			&i.TotalOrden,
			&i.GuiaBackorder,
			&i.NotasAdminBackorder,
			&i.PedidoOrigenID,
			&i.FechaBackorder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.PedidoOrigenFolio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarDisponibleBackorderDetalle = `-- name: MarcarDisponibleBackorderDetalle :one
UPDATE backorder_detalles
SET
    disponible = TRUE,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $3
WHERE id = $1 AND backorder_id = $2 AND deleted_at IS NULL
RETURNING id, backorder_id, variante_id, cantidad, precio_unitario_aplicado, disponible, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type MarcarDisponibleBackorderDetalleParams struct {
	ID          int32       `json:"id"`
	BackorderID pgtype.Int4 `json:"backorder_id"`
	UpdatedBy   pgtype.Int4 `json:"updated_by"`
}

func (q *Queries) MarcarDisponibleBackorderDetalle(ctx context.Context, arg MarcarDisponibleBackorderDetalleParams) (BackorderDetalle, error) {
	row := q.db.QueryRow(ctx, marcarDisponibleBackorderDetalle, arg.ID, arg.BackorderID, arg.UpdatedBy)
	var i BackorderDetalle
	err := row.Scan(
		&i.ID,
		&i.BackorderID,
		&i.VarianteID,
		&i.Cantidad,
		&i.PrecioUnitarioAplicado,
		&i.Disponible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const setPedidoOrigenBackorder = `-- name: SetPedidoOrigenBackorder :one
UPDATE backorders
SET
    pedido_origen_id = $2,
    estado_backorder = 'Convertido',
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, folio, cliente_id, usuario_id, estado_backorder, metodo_pago, subtotal, iva, total_orden, guia_backorder, notas_admin_backorder, pedido_origen_id, fecha_backorder, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type SetPedidoOrigenBackorderParams struct {
	ID             int32       `json:"id"`
	PedidoOrigenID pgtype.Int4 `json:"pedido_origen_id"`
	UpdatedBy      pgtype.Int4 `json:"updated_by"`
}

func (q *Queries) SetPedidoOrigenBackorder(ctx context.Context, arg SetPedidoOrigenBackorderParams) (Backorder, error) {
	row := q.db.QueryRow(ctx, setPedidoOrigenBackorder, arg.ID, arg.PedidoOrigenID, arg.UpdatedBy)
	var i Backorder
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.UsuarioID,
		&i.EstadoBackorder,
		&i.MetodoPago,
		&i.Subtotal,
		&i.Iva,
		&i.TotalOrden,
		&i.GuiaBackorder,
		&i.NotasAdminBackorder,
		&i.PedidoOrigenID,
		&i.FechaBackorder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}
