// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clientes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarCliente = `-- name: ActualizarCliente :one
UPDATE clientes
SET 
    nombre_comercial = $2,
    razon_social = $3,
    estado = $4,
    monto_minimo_compra = $5,
    linea_credito_total = $6,
    linea_credito_utilizada = $7,
    dias_credito = $8,  
    permitir_pago_credito = $9,
    metodo_pago_preferente = $10,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $11
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, nombre_comercial, razon_social, rfc, estado, monto_minimo_compra, linea_credito_total, linea_credito_utilizada, dias_credito, permitir_pago_credito, metodo_pago_preferente, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type ActualizarClienteParams struct {
	ID                    int32          `json:"id"`
	NombreComercial       string         `json:"nombre_comercial"`
	RazonSocial           string         `json:"razon_social"`
	Estado                string         `json:"estado"`
	MontoMinimoCompra     pgtype.Numeric `json:"monto_minimo_compra"`
	LineaCreditoTotal     pgtype.Numeric `json:"linea_credito_total"`
	LineaCreditoUtilizada pgtype.Numeric `json:"linea_credito_utilizada"`
	DiasCredito           int32          `json:"dias_credito"`
	PermitirPagoCredito   bool           `json:"permitir_pago_credito"`
	MetodoPagoPreferente  string         `json:"metodo_pago_preferente"`
	UpdatedBy             pgtype.Int4    `json:"updated_by"`
}

// Modifica datos generales y financieros registrando el auditor (Pág. 16)
func (q *Queries) ActualizarCliente(ctx context.Context, arg ActualizarClienteParams) (Cliente, error) {
	row := q.db.QueryRow(ctx, actualizarCliente,
		arg.ID,
		arg.NombreComercial,
		arg.RazonSocial,
		arg.Estado,
		arg.MontoMinimoCompra,
		arg.LineaCreditoTotal,
		arg.LineaCreditoUtilizada,
		arg.DiasCredito,
		arg.PermitirPagoCredito,
		arg.MetodoPagoPreferente,
		arg.UpdatedBy,
	)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.Estado,
		&i.MontoMinimoCompra,
		&i.LineaCreditoTotal,
		&i.LineaCreditoUtilizada,
		&i.DiasCredito,
		&i.PermitirPagoCredito,
		&i.MetodoPagoPreferente,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const actualizarSaldoCredito = `-- name: ActualizarSaldoCredito :exec
UPDATE clientes
SET 
    linea_credito_utilizada = linea_credito_utilizada + $2,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $3
WHERE id = $1
`

type ActualizarSaldoCreditoParams struct {
	ID                    int32          `json:"id"`
	LineaCreditoUtilizada pgtype.Numeric `json:"linea_credito_utilizada"`
	UpdatedBy             pgtype.Int4    `json:"updated_by"`
}

// Solo modifica el saldo utilizado (usado tras un pedido) (Pág. 20)
func (q *Queries) ActualizarSaldoCredito(ctx context.Context, arg ActualizarSaldoCreditoParams) error {
	_, err := q.db.Exec(ctx, actualizarSaldoCredito, arg.ID, arg.LineaCreditoUtilizada, arg.UpdatedBy)
	return err
}

const crearCliente = `-- name: CrearCliente :one
INSERT INTO clientes (
    nombre_comercial, 
    razon_social, 
    rfc, 
    estado, 
    monto_minimo_compra, 
    linea_credito_total, 
    linea_credito_utilizada,
    dias_credito, 
    permitir_pago_credito, 
    metodo_pago_preferente,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, nombre_comercial, razon_social, rfc, estado, monto_minimo_compra, linea_credito_total, linea_credito_utilizada, dias_credito, permitir_pago_credito, metodo_pago_preferente, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CrearClienteParams struct {
	NombreComercial       string         `json:"nombre_comercial"`
	RazonSocial           string         `json:"razon_social"`
	Rfc                   string         `json:"rfc"`
	Estado                string         `json:"estado"`
	MontoMinimoCompra     pgtype.Numeric `json:"monto_minimo_compra"`
	LineaCreditoTotal     pgtype.Numeric `json:"linea_credito_total"`
	LineaCreditoUtilizada pgtype.Numeric `json:"linea_credito_utilizada"`
	DiasCredito           int32          `json:"dias_credito"`
	PermitirPagoCredito   bool           `json:"permitir_pago_credito"`
	MetodoPagoPreferente  string         `json:"metodo_pago_preferente"`
	CreatedBy             pgtype.Int4    `json:"created_by"`
}

// Registra un nuevo cliente e identifica al responsable (Pág. 10)
func (q *Queries) CrearCliente(ctx context.Context, arg CrearClienteParams) (Cliente, error) {
	row := q.db.QueryRow(ctx, crearCliente,
		arg.NombreComercial,
		arg.RazonSocial,
		arg.Rfc,
		arg.Estado,
		arg.MontoMinimoCompra,
		arg.LineaCreditoTotal,
		arg.LineaCreditoUtilizada,
		arg.DiasCredito,
		arg.PermitirPagoCredito,
		arg.MetodoPagoPreferente,
		arg.CreatedBy,
	)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.Estado,
		&i.MontoMinimoCompra,
		&i.LineaCreditoTotal,
		&i.LineaCreditoUtilizada,
		&i.DiasCredito,
		&i.PermitirPagoCredito,
		&i.MetodoPagoPreferente,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getCliente = `-- name: GetCliente :one
SELECT id, nombre_comercial, razon_social, rfc, estado, monto_minimo_compra, linea_credito_total, linea_credito_utilizada, dias_credito, permitir_pago_credito, metodo_pago_preferente, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM clientes
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

// Obtiene un cliente por su ID para validar solvencia [cite: 131]
func (q *Queries) GetCliente(ctx context.Context, id int32) (Cliente, error) {
	row := q.db.QueryRow(ctx, getCliente, id)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.Estado,
		&i.MontoMinimoCompra,
		&i.LineaCreditoTotal,
		&i.LineaCreditoUtilizada,
		&i.DiasCredito,
		&i.PermitirPagoCredito,
		&i.MetodoPagoPreferente,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const listarClientesActivos = `-- name: ListarClientesActivos :many
SELECT id, nombre_comercial, razon_social, rfc, estado, monto_minimo_compra, linea_credito_total, linea_credito_utilizada, dias_credito, permitir_pago_credito, metodo_pago_preferente, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM clientes
WHERE deleted_at IS NULL
`

// Lista clientes para el panel de administración [cite: 139]
func (q *Queries) ListarClientesActivos(ctx context.Context) ([]Cliente, error) {
	rows, err := q.db.Query(ctx, listarClientesActivos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cliente
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(
			&i.ID,
			&i.NombreComercial,
			&i.RazonSocial,
			&i.Rfc,
			&i.Estado,
			&i.MontoMinimoCompra,
			&i.LineaCreditoTotal,
			&i.LineaCreditoUtilizada,
			&i.DiasCredito,
			&i.PermitirPagoCredito,
			&i.MetodoPagoPreferente,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCliente = `-- name: SoftDeleteCliente :exec
UPDATE clientes
SET 
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2,
    estado = 'Bloqueado'
WHERE id = $1
`

type SoftDeleteClienteParams struct {
	ID        int32       `json:"id"`
	DeletedBy pgtype.Int4 `json:"deleted_by"`
}

// Borrado lógico para mantener integridad histórica (Pág. 21)
func (q *Queries) SoftDeleteCliente(ctx context.Context, arg SoftDeleteClienteParams) error {
	_, err := q.db.Exec(ctx, softDeleteCliente, arg.ID, arg.DeletedBy)
	return err
}
