// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clientes_integracion.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const crearClienteIntegracion = `-- name: CrearClienteIntegracion :one
INSERT INTO clientes_integracion (
    cve_cte, 
    nom_cte, 
    dir_cte, 
    col_cte, 
    cd_cte, 
    edo_cte, 
    rfc_cte, 
    cp_cte, 
    contacto, 
    tel1_cte, 
    lim_cre, 
    dia_cre, 
    cve_age, 
    lada_cte, 
    cve_zon, 
    cve_sub, 
    cve_can, 
    cuentacon, 
    contado, 
    pais_cte, 
    email_cte
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
) RETURNING id, cve_cte, nom_cte, dir_cte, col_cte, cd_cte, edo_cte, rfc_cte, cp_cte, contacto, tel1_cte, lim_cre, dia_cre, cve_age, lada_cte, cve_zon, cve_sub, cve_can, cuentacon, contado, pais_cte, email_cte
`

type CrearClienteIntegracionParams struct {
	CveCte    pgtype.Int4    `json:"cve_cte"`
	NomCte    pgtype.Text    `json:"nom_cte"`
	DirCte    pgtype.Text    `json:"dir_cte"`
	ColCte    pgtype.Text    `json:"col_cte"`
	CdCte     pgtype.Text    `json:"cd_cte"`
	EdoCte    pgtype.Text    `json:"edo_cte"`
	RfcCte    pgtype.Text    `json:"rfc_cte"`
	CpCte     pgtype.Text    `json:"cp_cte"`
	Contacto  pgtype.Text    `json:"contacto"`
	Tel1Cte   pgtype.Text    `json:"tel1_cte"`
	LimCre    pgtype.Numeric `json:"lim_cre"`
	DiaCre    pgtype.Int4    `json:"dia_cre"`
	CveAge    pgtype.Int4    `json:"cve_age"`
	LadaCte   pgtype.Text    `json:"lada_cte"`
	CveZon    pgtype.Int4    `json:"cve_zon"`
	CveSub    pgtype.Int4    `json:"cve_sub"`
	CveCan    pgtype.Int4    `json:"cve_can"`
	Cuentacon pgtype.Text    `json:"cuentacon"`
	Contado   pgtype.Int4    `json:"contado"`
	PaisCte   pgtype.Text    `json:"pais_cte"`
	EmailCte  pgtype.Text    `json:"email_cte"`
}

func (q *Queries) CrearClienteIntegracion(ctx context.Context, arg CrearClienteIntegracionParams) (ClientesIntegracion, error) {
	row := q.db.QueryRow(ctx, crearClienteIntegracion,
		arg.CveCte,
		arg.NomCte,
		arg.DirCte,
		arg.ColCte,
		arg.CdCte,
		arg.EdoCte,
		arg.RfcCte,
		arg.CpCte,
		arg.Contacto,
		arg.Tel1Cte,
		arg.LimCre,
		arg.DiaCre,
		arg.CveAge,
		arg.LadaCte,
		arg.CveZon,
		arg.CveSub,
		arg.CveCan,
		arg.Cuentacon,
		arg.Contado,
		arg.PaisCte,
		arg.EmailCte,
	)
	var i ClientesIntegracion
	err := row.Scan(
		&i.ID,
		&i.CveCte,
		&i.NomCte,
		&i.DirCte,
		&i.ColCte,
		&i.CdCte,
		&i.EdoCte,
		&i.RfcCte,
		&i.CpCte,
		&i.Contacto,
		&i.Tel1Cte,
		&i.LimCre,
		&i.DiaCre,
		&i.CveAge,
		&i.LadaCte,
		&i.CveZon,
		&i.CveSub,
		&i.CveCan,
		&i.Cuentacon,
		&i.Contado,
		&i.PaisCte,
		&i.EmailCte,
	)
	return i, err
}

const obtenerClienteIntegracion = `-- name: ObtenerClienteIntegracion :one
SELECT id, cve_cte, nom_cte, dir_cte, col_cte, cd_cte, edo_cte, rfc_cte, cp_cte, contacto, tel1_cte, lim_cre, dia_cre, cve_age, lada_cte, cve_zon, cve_sub, cve_can, cuentacon, contado, pais_cte, email_cte FROM clientes_integracion
WHERE id = $1 LIMIT 1
`

func (q *Queries) ObtenerClienteIntegracion(ctx context.Context, id int32) (ClientesIntegracion, error) {
	row := q.db.QueryRow(ctx, obtenerClienteIntegracion, id)
	var i ClientesIntegracion
	err := row.Scan(
		&i.ID,
		&i.CveCte,
		&i.NomCte,
		&i.DirCte,
		&i.ColCte,
		&i.CdCte,
		&i.EdoCte,
		&i.RfcCte,
		&i.CpCte,
		&i.Contacto,
		&i.Tel1Cte,
		&i.LimCre,
		&i.DiaCre,
		&i.CveAge,
		&i.LadaCte,
		&i.CveZon,
		&i.CveSub,
		&i.CveCan,
		&i.Cuentacon,
		&i.Contado,
		&i.PaisCte,
		&i.EmailCte,
	)
	return i, err
}

const obtenerClientesIntegracion = `-- name: ObtenerClientesIntegracion :many
SELECT id, cve_cte, nom_cte, dir_cte, col_cte, cd_cte, edo_cte, rfc_cte, cp_cte, contacto, tel1_cte, lim_cre, dia_cre, cve_age, lada_cte, cve_zon, cve_sub, cve_can, cuentacon, contado, pais_cte, email_cte FROM clientes_integracion
`

func (q *Queries) ObtenerClientesIntegracion(ctx context.Context) ([]ClientesIntegracion, error) {
	rows, err := q.db.Query(ctx, obtenerClientesIntegracion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientesIntegracion
	for rows.Next() {
		var i ClientesIntegracion
		if err := rows.Scan(
			&i.ID,
			&i.CveCte,
			&i.NomCte,
			&i.DirCte,
			&i.ColCte,
			&i.CdCte,
			&i.EdoCte,
			&i.RfcCte,
			&i.CpCte,
			&i.Contacto,
			&i.Tel1Cte,
			&i.LimCre,
			&i.DiaCre,
			&i.CveAge,
			&i.LadaCte,
			&i.CveZon,
			&i.CveSub,
			&i.CveCan,
			&i.Cuentacon,
			&i.Contado,
			&i.PaisCte,
			&i.EmailCte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerClientesIntegracionPorCveCte = `-- name: ObtenerClientesIntegracionPorCveCte :one
SELECT id, cve_cte, nom_cte, dir_cte, col_cte, cd_cte, edo_cte, rfc_cte, cp_cte, contacto, tel1_cte, lim_cre, dia_cre, cve_age, lada_cte, cve_zon, cve_sub, cve_can, cuentacon, contado, pais_cte, email_cte FROM clientes_integracion
WHERE cve_cte = $1 LIMIT 1
`

func (q *Queries) ObtenerClientesIntegracionPorCveCte(ctx context.Context, cveCte pgtype.Int4) (ClientesIntegracion, error) {
	row := q.db.QueryRow(ctx, obtenerClientesIntegracionPorCveCte, cveCte)
	var i ClientesIntegracion
	err := row.Scan(
		&i.ID,
		&i.CveCte,
		&i.NomCte,
		&i.DirCte,
		&i.ColCte,
		&i.CdCte,
		&i.EdoCte,
		&i.RfcCte,
		&i.CpCte,
		&i.Contacto,
		&i.Tel1Cte,
		&i.LimCre,
		&i.DiaCre,
		&i.CveAge,
		&i.LadaCte,
		&i.CveZon,
		&i.CveSub,
		&i.CveCan,
		&i.Cuentacon,
		&i.Contado,
		&i.PaisCte,
		&i.EmailCte,
	)
	return i, err
}

const upsertClienteIntegracion = `-- name: UpsertClienteIntegracion :one
INSERT INTO clientes_integracion (
    cve_cte, nom_cte, dir_cte, col_cte, cd_cte, edo_cte, rfc_cte, cp_cte, 
    contacto, tel1_cte, lim_cre, dia_cre, cve_age, lada_cte, cve_zon, 
    cve_sub, cve_can, cuentacon, contado, pais_cte, email_cte
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
ON CONFLICT (cve_cte) DO UPDATE SET
    nom_cte = EXCLUDED.nom_cte,
    dir_cte = EXCLUDED.dir_cte,
    col_cte = EXCLUDED.col_cte,
    cd_cte = EXCLUDED.cd_cte,
    edo_cte = EXCLUDED.edo_cte,
    rfc_cte = EXCLUDED.rfc_cte,
    cp_cte = EXCLUDED.cp_cte,
    contacto = EXCLUDED.contacto,
    tel1_cte = EXCLUDED.tel1_cte,
    lim_cre = EXCLUDED.lim_cre,
    dia_cre = EXCLUDED.dia_cre,
    cve_age = EXCLUDED.cve_age,
    lada_cte = EXCLUDED.lada_cte,
    cve_zon = EXCLUDED.cve_zon,
    cve_sub = EXCLUDED.cve_sub,
    cve_can = EXCLUDED.cve_can,
    cuentacon = EXCLUDED.cuentacon,
    contado = EXCLUDED.contado,
    pais_cte = EXCLUDED.pais_cte,
    email_cte = EXCLUDED.email_cte
RETURNING id, cve_cte, nom_cte, dir_cte, col_cte, cd_cte, edo_cte, rfc_cte, cp_cte, contacto, tel1_cte, lim_cre, dia_cre, cve_age, lada_cte, cve_zon, cve_sub, cve_can, cuentacon, contado, pais_cte, email_cte
`

type UpsertClienteIntegracionParams struct {
	CveCte    pgtype.Int4    `json:"cve_cte"`
	NomCte    pgtype.Text    `json:"nom_cte"`
	DirCte    pgtype.Text    `json:"dir_cte"`
	ColCte    pgtype.Text    `json:"col_cte"`
	CdCte     pgtype.Text    `json:"cd_cte"`
	EdoCte    pgtype.Text    `json:"edo_cte"`
	RfcCte    pgtype.Text    `json:"rfc_cte"`
	CpCte     pgtype.Text    `json:"cp_cte"`
	Contacto  pgtype.Text    `json:"contacto"`
	Tel1Cte   pgtype.Text    `json:"tel1_cte"`
	LimCre    pgtype.Numeric `json:"lim_cre"`
	DiaCre    pgtype.Int4    `json:"dia_cre"`
	CveAge    pgtype.Int4    `json:"cve_age"`
	LadaCte   pgtype.Text    `json:"lada_cte"`
	CveZon    pgtype.Int4    `json:"cve_zon"`
	CveSub    pgtype.Int4    `json:"cve_sub"`
	CveCan    pgtype.Int4    `json:"cve_can"`
	Cuentacon pgtype.Text    `json:"cuentacon"`
	Contado   pgtype.Int4    `json:"contado"`
	PaisCte   pgtype.Text    `json:"pais_cte"`
	EmailCte  pgtype.Text    `json:"email_cte"`
}

func (q *Queries) UpsertClienteIntegracion(ctx context.Context, arg UpsertClienteIntegracionParams) (ClientesIntegracion, error) {
	row := q.db.QueryRow(ctx, upsertClienteIntegracion,
		arg.CveCte,
		arg.NomCte,
		arg.DirCte,
		arg.ColCte,
		arg.CdCte,
		arg.EdoCte,
		arg.RfcCte,
		arg.CpCte,
		arg.Contacto,
		arg.Tel1Cte,
		arg.LimCre,
		arg.DiaCre,
		arg.CveAge,
		arg.LadaCte,
		arg.CveZon,
		arg.CveSub,
		arg.CveCan,
		arg.Cuentacon,
		arg.Contado,
		arg.PaisCte,
		arg.EmailCte,
	)
	var i ClientesIntegracion
	err := row.Scan(
		&i.ID,
		&i.CveCte,
		&i.NomCte,
		&i.DirCte,
		&i.ColCte,
		&i.CdCte,
		&i.EdoCte,
		&i.RfcCte,
		&i.CpCte,
		&i.Contacto,
		&i.Tel1Cte,
		&i.LimCre,
		&i.DiaCre,
		&i.CveAge,
		&i.LadaCte,
		&i.CveZon,
		&i.CveSub,
		&i.CveCan,
		&i.Cuentacon,
		&i.Contado,
		&i.PaisCte,
		&i.EmailCte,
	)
	return i, err
}
