// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: creditos_integracion.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredito = `-- name: CreateCredito :one
INSERT INTO creditos_integracion (
    cve_dda, no_nota, tip_not, fecha, no_fac, no_cliente, no_agente, 
    no_estado, tot_imp, subtotal, desc_not, tot_nota, num, saldo, 
    tot_des, lugar, cve_factu, cve_mon, tip_cam, cve_suc, mes, aqo, usuario, trans
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
)
RETURNING id, cve_dda, no_nota, tip_not, fecha, no_fac, no_cliente, no_agente, no_estado, tot_imp, subtotal, desc_not, tot_nota, num, saldo, tot_des, lugar, cve_factu, cve_mon, tip_cam, cve_suc, mes, aqo, usuario, trans
`

type CreateCreditoParams struct {
	CveDda    pgtype.Text      `json:"cve_dda"`
	NoNota    pgtype.Text      `json:"no_nota"`
	TipNot    pgtype.Text      `json:"tip_not"`
	Fecha     pgtype.Timestamp `json:"fecha"`
	NoFac     pgtype.Text      `json:"no_fac"`
	NoCliente pgtype.Int4      `json:"no_cliente"`
	NoAgente  pgtype.Int4      `json:"no_agente"`
	NoEstado  pgtype.Text      `json:"no_estado"`
	TotImp    pgtype.Numeric   `json:"tot_imp"`
	Subtotal  pgtype.Numeric   `json:"subtotal"`
	DescNot   pgtype.Numeric   `json:"desc_not"`
	TotNota   pgtype.Numeric   `json:"tot_nota"`
	Num       pgtype.Int4      `json:"num"`
	Saldo     pgtype.Numeric   `json:"saldo"`
	TotDes    pgtype.Numeric   `json:"tot_des"`
	Lugar     pgtype.Text      `json:"lugar"`
	CveFactu  pgtype.Text      `json:"cve_factu"`
	CveMon    pgtype.Int4      `json:"cve_mon"`
	TipCam    pgtype.Numeric   `json:"tip_cam"`
	CveSuc    pgtype.Text      `json:"cve_suc"`
	Mes       pgtype.Text      `json:"mes"`
	Aqo       pgtype.Text      `json:"aqo"`
	Usuario   pgtype.Int4      `json:"usuario"`
	Trans     pgtype.Int4      `json:"trans"`
}

func (q *Queries) CreateCredito(ctx context.Context, arg CreateCreditoParams) (CreditosIntegracion, error) {
	row := q.db.QueryRow(ctx, createCredito,
		arg.CveDda,
		arg.NoNota,
		arg.TipNot,
		arg.Fecha,
		arg.NoFac,
		arg.NoCliente,
		arg.NoAgente,
		arg.NoEstado,
		arg.TotImp,
		arg.Subtotal,
		arg.DescNot,
		arg.TotNota,
		arg.Num,
		arg.Saldo,
		arg.TotDes,
		arg.Lugar,
		arg.CveFactu,
		arg.CveMon,
		arg.TipCam,
		arg.CveSuc,
		arg.Mes,
		arg.Aqo,
		arg.Usuario,
		arg.Trans,
	)
	var i CreditosIntegracion
	err := row.Scan(
		&i.ID,
		&i.CveDda,
		&i.NoNota,
		&i.TipNot,
		&i.Fecha,
		&i.NoFac,
		&i.NoCliente,
		&i.NoAgente,
		&i.NoEstado,
		&i.TotImp,
		&i.Subtotal,
		&i.DescNot,
		&i.TotNota,
		&i.Num,
		&i.Saldo,
		&i.TotDes,
		&i.Lugar,
		&i.CveFactu,
		&i.CveMon,
		&i.TipCam,
		&i.CveSuc,
		&i.Mes,
		&i.Aqo,
		&i.Usuario,
		&i.Trans,
	)
	return i, err
}

const getCreditoByFactura = `-- name: GetCreditoByFactura :one
SELECT id, cve_dda, no_nota, tip_not, fecha, no_fac, no_cliente, no_agente, no_estado, tot_imp, subtotal, desc_not, tot_nota, num, saldo, tot_des, lugar, cve_factu, cve_mon, tip_cam, cve_suc, mes, aqo, usuario, trans FROM creditos_integracion
WHERE no_fac = $1 AND cve_factu = $2 LIMIT 1
`

type GetCreditoByFacturaParams struct {
	NoFac    pgtype.Text `json:"no_fac"`
	CveFactu pgtype.Text `json:"cve_factu"`
}

// Aprovecha la restricción UNIQUE (no_fac, cve_factu)
func (q *Queries) GetCreditoByFactura(ctx context.Context, arg GetCreditoByFacturaParams) (CreditosIntegracion, error) {
	row := q.db.QueryRow(ctx, getCreditoByFactura, arg.NoFac, arg.CveFactu)
	var i CreditosIntegracion
	err := row.Scan(
		&i.ID,
		&i.CveDda,
		&i.NoNota,
		&i.TipNot,
		&i.Fecha,
		&i.NoFac,
		&i.NoCliente,
		&i.NoAgente,
		&i.NoEstado,
		&i.TotImp,
		&i.Subtotal,
		&i.DescNot,
		&i.TotNota,
		&i.Num,
		&i.Saldo,
		&i.TotDes,
		&i.Lugar,
		&i.CveFactu,
		&i.CveMon,
		&i.TipCam,
		&i.CveSuc,
		&i.Mes,
		&i.Aqo,
		&i.Usuario,
		&i.Trans,
	)
	return i, err
}

const getCreditoByID = `-- name: GetCreditoByID :one
SELECT id, cve_dda, no_nota, tip_not, fecha, no_fac, no_cliente, no_agente, no_estado, tot_imp, subtotal, desc_not, tot_nota, num, saldo, tot_des, lugar, cve_factu, cve_mon, tip_cam, cve_suc, mes, aqo, usuario, trans FROM creditos_integracion
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCreditoByID(ctx context.Context, id int32) (CreditosIntegracion, error) {
	row := q.db.QueryRow(ctx, getCreditoByID, id)
	var i CreditosIntegracion
	err := row.Scan(
		&i.ID,
		&i.CveDda,
		&i.NoNota,
		&i.TipNot,
		&i.Fecha,
		&i.NoFac,
		&i.NoCliente,
		&i.NoAgente,
		&i.NoEstado,
		&i.TotImp,
		&i.Subtotal,
		&i.DescNot,
		&i.TotNota,
		&i.Num,
		&i.Saldo,
		&i.TotDes,
		&i.Lugar,
		&i.CveFactu,
		&i.CveMon,
		&i.TipCam,
		&i.CveSuc,
		&i.Mes,
		&i.Aqo,
		&i.Usuario,
		&i.Trans,
	)
	return i, err
}

const listAllCreditos = `-- name: ListAllCreditos :many
SELECT id, cve_dda, no_nota, tip_not, fecha, no_fac, no_cliente, no_agente, no_estado, tot_imp, subtotal, desc_not, tot_nota, num, saldo, tot_des, lugar, cve_factu, cve_mon, tip_cam, cve_suc, mes, aqo, usuario, trans FROM creditos_integracion
ORDER BY fecha DESC
`

func (q *Queries) ListAllCreditos(ctx context.Context) ([]CreditosIntegracion, error) {
	rows, err := q.db.Query(ctx, listAllCreditos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditosIntegracion
	for rows.Next() {
		var i CreditosIntegracion
		if err := rows.Scan(
			&i.ID,
			&i.CveDda,
			&i.NoNota,
			&i.TipNot,
			&i.Fecha,
			&i.NoFac,
			&i.NoCliente,
			&i.NoAgente,
			&i.NoEstado,
			&i.TotImp,
			&i.Subtotal,
			&i.DescNot,
			&i.TotNota,
			&i.Num,
			&i.Saldo,
			&i.TotDes,
			&i.Lugar,
			&i.CveFactu,
			&i.CveMon,
			&i.TipCam,
			&i.CveSuc,
			&i.Mes,
			&i.Aqo,
			&i.Usuario,
			&i.Trans,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditosByCliente = `-- name: ListCreditosByCliente :many
SELECT id, cve_dda, no_nota, tip_not, fecha, no_fac, no_cliente, no_agente, no_estado, tot_imp, subtotal, desc_not, tot_nota, num, saldo, tot_des, lugar, cve_factu, cve_mon, tip_cam, cve_suc, mes, aqo, usuario, trans FROM creditos_integracion
WHERE no_cliente = $1
ORDER BY fecha DESC
`

func (q *Queries) ListCreditosByCliente(ctx context.Context, noCliente pgtype.Int4) ([]CreditosIntegracion, error) {
	rows, err := q.db.Query(ctx, listCreditosByCliente, noCliente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditosIntegracion
	for rows.Next() {
		var i CreditosIntegracion
		if err := rows.Scan(
			&i.ID,
			&i.CveDda,
			&i.NoNota,
			&i.TipNot,
			&i.Fecha,
			&i.NoFac,
			&i.NoCliente,
			&i.NoAgente,
			&i.NoEstado,
			&i.TotImp,
			&i.Subtotal,
			&i.DescNot,
			&i.TotNota,
			&i.Num,
			&i.Saldo,
			&i.TotDes,
			&i.Lugar,
			&i.CveFactu,
			&i.CveMon,
			&i.TipCam,
			&i.CveSuc,
			&i.Mes,
			&i.Aqo,
			&i.Usuario,
			&i.Trans,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreditoSaldo = `-- name: UpdateCreditoSaldo :one
UPDATE creditos_integracion
SET 
    saldo = $2,
    usuario = $3
WHERE id = $1
RETURNING id, cve_dda, no_nota, tip_not, fecha, no_fac, no_cliente, no_agente, no_estado, tot_imp, subtotal, desc_not, tot_nota, num, saldo, tot_des, lugar, cve_factu, cve_mon, tip_cam, cve_suc, mes, aqo, usuario, trans
`

type UpdateCreditoSaldoParams struct {
	ID      int32          `json:"id"`
	Saldo   pgtype.Numeric `json:"saldo"`
	Usuario pgtype.Int4    `json:"usuario"`
}

func (q *Queries) UpdateCreditoSaldo(ctx context.Context, arg UpdateCreditoSaldoParams) (CreditosIntegracion, error) {
	row := q.db.QueryRow(ctx, updateCreditoSaldo, arg.ID, arg.Saldo, arg.Usuario)
	var i CreditosIntegracion
	err := row.Scan(
		&i.ID,
		&i.CveDda,
		&i.NoNota,
		&i.TipNot,
		&i.Fecha,
		&i.NoFac,
		&i.NoCliente,
		&i.NoAgente,
		&i.NoEstado,
		&i.TotImp,
		&i.Subtotal,
		&i.DescNot,
		&i.TotNota,
		&i.Num,
		&i.Saldo,
		&i.TotDes,
		&i.Lugar,
		&i.CveFactu,
		&i.CveMon,
		&i.TipCam,
		&i.CveSuc,
		&i.Mes,
		&i.Aqo,
		&i.Usuario,
		&i.Trans,
	)
	return i, err
}

const upsertCredito = `-- name: UpsertCredito :one
INSERT INTO creditos_integracion (
    cve_dda, no_nota, tip_not, fecha, no_fac, no_cliente, no_agente, 
    no_estado, tot_imp, subtotal, desc_not, tot_nota, num, saldo, 
    tot_des, lugar, cve_factu, cve_mon, tip_cam, cve_suc, mes, aqo, usuario, trans
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
)
ON CONFLICT (no_fac, cve_factu) DO UPDATE SET
    cve_dda = EXCLUDED.cve_dda,
    no_nota = EXCLUDED.no_nota,
    tip_not = EXCLUDED.tip_not,
    fecha = EXCLUDED.fecha,
    no_cliente = EXCLUDED.no_cliente,
    no_agente = EXCLUDED.no_agente,
    no_estado = EXCLUDED.no_estado,
    tot_imp = EXCLUDED.tot_imp,
    subtotal = EXCLUDED.subtotal,
    desc_not = EXCLUDED.desc_not,
    tot_nota = EXCLUDED.tot_nota,
    num = EXCLUDED.num,
    saldo = EXCLUDED.saldo,
    tot_des = EXCLUDED.tot_des,
    lugar = EXCLUDED.lugar,
    cve_mon = EXCLUDED.cve_mon,
    tip_cam = EXCLUDED.tip_cam,
    cve_suc = EXCLUDED.cve_suc,
    mes = EXCLUDED.mes,
    aqo = EXCLUDED.aqo,
    usuario = EXCLUDED.usuario,
    trans = EXCLUDED.trans
RETURNING id, cve_dda, no_nota, tip_not, fecha, no_fac, no_cliente, no_agente, no_estado, tot_imp, subtotal, desc_not, tot_nota, num, saldo, tot_des, lugar, cve_factu, cve_mon, tip_cam, cve_suc, mes, aqo, usuario, trans
`

type UpsertCreditoParams struct {
	CveDda    pgtype.Text      `json:"cve_dda"`
	NoNota    pgtype.Text      `json:"no_nota"`
	TipNot    pgtype.Text      `json:"tip_not"`
	Fecha     pgtype.Timestamp `json:"fecha"`
	NoFac     pgtype.Text      `json:"no_fac"`
	NoCliente pgtype.Int4      `json:"no_cliente"`
	NoAgente  pgtype.Int4      `json:"no_agente"`
	NoEstado  pgtype.Text      `json:"no_estado"`
	TotImp    pgtype.Numeric   `json:"tot_imp"`
	Subtotal  pgtype.Numeric   `json:"subtotal"`
	DescNot   pgtype.Numeric   `json:"desc_not"`
	TotNota   pgtype.Numeric   `json:"tot_nota"`
	Num       pgtype.Int4      `json:"num"`
	Saldo     pgtype.Numeric   `json:"saldo"`
	TotDes    pgtype.Numeric   `json:"tot_des"`
	Lugar     pgtype.Text      `json:"lugar"`
	CveFactu  pgtype.Text      `json:"cve_factu"`
	CveMon    pgtype.Int4      `json:"cve_mon"`
	TipCam    pgtype.Numeric   `json:"tip_cam"`
	CveSuc    pgtype.Text      `json:"cve_suc"`
	Mes       pgtype.Text      `json:"mes"`
	Aqo       pgtype.Text      `json:"aqo"`
	Usuario   pgtype.Int4      `json:"usuario"`
	Trans     pgtype.Int4      `json:"trans"`
}

func (q *Queries) UpsertCredito(ctx context.Context, arg UpsertCreditoParams) (CreditosIntegracion, error) {
	row := q.db.QueryRow(ctx, upsertCredito,
		arg.CveDda,
		arg.NoNota,
		arg.TipNot,
		arg.Fecha,
		arg.NoFac,
		arg.NoCliente,
		arg.NoAgente,
		arg.NoEstado,
		arg.TotImp,
		arg.Subtotal,
		arg.DescNot,
		arg.TotNota,
		arg.Num,
		arg.Saldo,
		arg.TotDes,
		arg.Lugar,
		arg.CveFactu,
		arg.CveMon,
		arg.TipCam,
		arg.CveSuc,
		arg.Mes,
		arg.Aqo,
		arg.Usuario,
		arg.Trans,
	)
	var i CreditosIntegracion
	err := row.Scan(
		&i.ID,
		&i.CveDda,
		&i.NoNota,
		&i.TipNot,
		&i.Fecha,
		&i.NoFac,
		&i.NoCliente,
		&i.NoAgente,
		&i.NoEstado,
		&i.TotImp,
		&i.Subtotal,
		&i.DescNot,
		&i.TotNota,
		&i.Num,
		&i.Saldo,
		&i.TotDes,
		&i.Lugar,
		&i.CveFactu,
		&i.CveMon,
		&i.TipCam,
		&i.CveSuc,
		&i.Mes,
		&i.Aqo,
		&i.Usuario,
		&i.Trans,
	)
	return i, err
}
