// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard_cliente.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const obtenerBackordersActivosCount = `-- name: ObtenerBackordersActivosCount :one
SELECT COUNT(*)::bigint AS total
FROM backorders
WHERE cliente_id = $1 AND deleted_at IS NULL
  AND estado_backorder NOT IN ('Convertido', 'Cancelado')
`

func (q *Queries) ObtenerBackordersActivosCount(ctx context.Context, clienteID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, obtenerBackordersActivosCount, clienteID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const obtenerDatosFinancierosDashboard = `-- name: ObtenerDatosFinancierosDashboard :one
SELECT
    c.dia_cre AS dias_credito,
    c.lim_cre AS limite_credito,
    CAST(COALESCE(SUM(f.saldo_fac), 0) AS DECIMAL(15,2)) AS saldo_pendiente_total,
    CAST(COALESCE(SUM(CASE WHEN f.f_pago < CURRENT_TIMESTAMP AND f.saldo_fac > 0 THEN f.saldo_fac ELSE 0 END), 0) AS DECIMAL(15,2)) AS saldo_vencido
FROM clientes_integracion c
LEFT JOIN facturas_integracion f ON c.cve_cte = f.cve_cte
WHERE c.cve_cte = $1
GROUP BY c.dia_cre, c.lim_cre
`

type ObtenerDatosFinancierosDashboardRow struct {
	DiasCredito         pgtype.Int4    `json:"dias_credito"`
	LimiteCredito       pgtype.Numeric `json:"limite_credito"`
	SaldoPendienteTotal pgtype.Numeric `json:"saldo_pendiente_total"`
	SaldoVencido        pgtype.Numeric `json:"saldo_vencido"`
}

func (q *Queries) ObtenerDatosFinancierosDashboard(ctx context.Context, cveCte pgtype.Int4) (ObtenerDatosFinancierosDashboardRow, error) {
	row := q.db.QueryRow(ctx, obtenerDatosFinancierosDashboard, cveCte)
	var i ObtenerDatosFinancierosDashboardRow
	err := row.Scan(
		&i.DiasCredito,
		&i.LimiteCredito,
		&i.SaldoPendienteTotal,
		&i.SaldoVencido,
	)
	return i, err
}

const obtenerDevolucionesEnProcesoCount = `-- name: ObtenerDevolucionesEnProcesoCount :one
SELECT COUNT(*)::bigint AS total
FROM devoluciones_garantias
WHERE cliente_id = $1 AND deleted_at IS NULL
  AND estatus != 'Cancelada'
`

func (q *Queries) ObtenerDevolucionesEnProcesoCount(ctx context.Context, clienteID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, obtenerDevolucionesEnProcesoCount, clienteID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const obtenerPedidosActivosCount = `-- name: ObtenerPedidosActivosCount :one
SELECT COUNT(*)::bigint AS total
FROM pedidos
WHERE cliente_id = $1 AND deleted_at IS NULL
  AND estado NOT IN ('Entregado', 'Cancelado')
`

func (q *Queries) ObtenerPedidosActivosCount(ctx context.Context, clienteID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, obtenerPedidosActivosCount, clienteID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
