// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devoluciones.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarEstatusDevolucion = `-- name: ActualizarEstatusDevolucion :one
UPDATE devoluciones_garantias
SET
    estatus = $2,
    nota_administrador = $3,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, folio, cliente_id, pedido_folio, tipo, numeros_parte, nota_cliente, evidencias, estatus, nota_administrador, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by, cantidades
`

type ActualizarEstatusDevolucionParams struct {
	ID                int32       `json:"id"`
	Estatus           string      `json:"estatus"`
	NotaAdministrador string      `json:"nota_administrador"`
	UpdatedBy         pgtype.Int4 `json:"updated_by"`
}

func (q *Queries) ActualizarEstatusDevolucion(ctx context.Context, arg ActualizarEstatusDevolucionParams) (DevolucionesGarantia, error) {
	row := q.db.QueryRow(ctx, actualizarEstatusDevolucion,
		arg.ID,
		arg.Estatus,
		arg.NotaAdministrador,
		arg.UpdatedBy,
	)
	var i DevolucionesGarantia
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.PedidoFolio,
		&i.Tipo,
		&i.NumerosParte,
		&i.NotaCliente,
		&i.Evidencias,
		&i.Estatus,
		&i.NotaAdministrador,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Cantidades,
	)
	return i, err
}

const crearDevolucion = `-- name: CrearDevolucion :one
INSERT INTO devoluciones_garantias (
    folio,
    cliente_id,
    pedido_folio,
    tipo,
    numeros_parte,
    cantidades,
    nota_cliente,
    evidencias,
    estatus,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 'Pendiente', $9
) RETURNING id, folio, cliente_id, pedido_folio, tipo, numeros_parte, nota_cliente, evidencias, estatus, nota_administrador, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by, cantidades
`

type CrearDevolucionParams struct {
	Folio        string      `json:"folio"`
	ClienteID    pgtype.Int4 `json:"cliente_id"`
	PedidoFolio  string      `json:"pedido_folio"`
	Tipo         string      `json:"tipo"`
	NumerosParte string      `json:"numeros_parte"`
	Cantidades   string      `json:"cantidades"`
	NotaCliente  string      `json:"nota_cliente"`
	Evidencias   string      `json:"evidencias"`
	CreatedBy    pgtype.Int4 `json:"created_by"`
}

func (q *Queries) CrearDevolucion(ctx context.Context, arg CrearDevolucionParams) (DevolucionesGarantia, error) {
	row := q.db.QueryRow(ctx, crearDevolucion,
		arg.Folio,
		arg.ClienteID,
		arg.PedidoFolio,
		arg.Tipo,
		arg.NumerosParte,
		arg.Cantidades,
		arg.NotaCliente,
		arg.Evidencias,
		arg.CreatedBy,
	)
	var i DevolucionesGarantia
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.PedidoFolio,
		&i.Tipo,
		&i.NumerosParte,
		&i.NotaCliente,
		&i.Evidencias,
		&i.Estatus,
		&i.NotaAdministrador,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Cantidades,
	)
	return i, err
}

const getDevolucion = `-- name: GetDevolucion :one
SELECT id, folio, cliente_id, pedido_folio, tipo, numeros_parte, nota_cliente, evidencias, estatus, nota_administrador, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by, cantidades FROM devoluciones_garantias
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetDevolucion(ctx context.Context, id int32) (DevolucionesGarantia, error) {
	row := q.db.QueryRow(ctx, getDevolucion, id)
	var i DevolucionesGarantia
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.PedidoFolio,
		&i.Tipo,
		&i.NumerosParte,
		&i.NotaCliente,
		&i.Evidencias,
		&i.Estatus,
		&i.NotaAdministrador,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.Cantidades,
	)
	return i, err
}

const listDevoluciones = `-- name: ListDevoluciones :many
SELECT id, folio, cliente_id, pedido_folio, tipo, numeros_parte, nota_cliente, evidencias, estatus, nota_administrador, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by, cantidades FROM devoluciones_garantias
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListDevoluciones(ctx context.Context) ([]DevolucionesGarantia, error) {
	rows, err := q.db.Query(ctx, listDevoluciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DevolucionesGarantia
	for rows.Next() {
		var i DevolucionesGarantia
		if err := rows.Scan(
			&i.ID,
			&i.Folio,
			&i.ClienteID,
			&i.PedidoFolio,
			&i.Tipo,
			&i.NumerosParte,
			&i.NotaCliente,
			&i.Evidencias,
			&i.Estatus,
			&i.NotaAdministrador,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Cantidades,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevolucionesByCliente = `-- name: ListDevolucionesByCliente :many
SELECT id, folio, cliente_id, pedido_folio, tipo, numeros_parte, nota_cliente, evidencias, estatus, nota_administrador, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by, cantidades FROM devoluciones_garantias
WHERE cliente_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListDevolucionesByCliente(ctx context.Context, clienteID pgtype.Int4) ([]DevolucionesGarantia, error) {
	rows, err := q.db.Query(ctx, listDevolucionesByCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DevolucionesGarantia
	for rows.Next() {
		var i DevolucionesGarantia
		if err := rows.Scan(
			&i.ID,
			&i.Folio,
			&i.ClienteID,
			&i.PedidoFolio,
			&i.Tipo,
			&i.NumerosParte,
			&i.NotaCliente,
			&i.Evidencias,
			&i.Estatus,
			&i.NotaAdministrador,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Cantidades,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevolucionesByClienteRango = `-- name: ListDevolucionesByClienteRango :many
SELECT id, folio, cliente_id, pedido_folio, tipo, numeros_parte, nota_cliente, evidencias, estatus, nota_administrador, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by, cantidades FROM devoluciones_garantias
WHERE cliente_id = $1 AND deleted_at IS NULL
  AND created_at >= $2
  AND created_at <= $3
ORDER BY created_at DESC
`

type ListDevolucionesByClienteRangoParams struct {
	ClienteID   pgtype.Int4      `json:"cliente_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

func (q *Queries) ListDevolucionesByClienteRango(ctx context.Context, arg ListDevolucionesByClienteRangoParams) ([]DevolucionesGarantia, error) {
	rows, err := q.db.Query(ctx, listDevolucionesByClienteRango, arg.ClienteID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DevolucionesGarantia
	for rows.Next() {
		var i DevolucionesGarantia
		if err := rows.Scan(
			&i.ID,
			&i.Folio,
			&i.ClienteID,
			&i.PedidoFolio,
			&i.Tipo,
			&i.NumerosParte,
			&i.NotaCliente,
			&i.Evidencias,
			&i.Estatus,
			&i.NotaAdministrador,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Cantidades,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevolucionesPorRango = `-- name: ListDevolucionesPorRango :many
SELECT id, folio, cliente_id, pedido_folio, tipo, numeros_parte, nota_cliente, evidencias, estatus, nota_administrador, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by, cantidades FROM devoluciones_garantias
WHERE deleted_at IS NULL
  AND created_at >= $1
  AND created_at <= $2
ORDER BY created_at DESC
`

type ListDevolucionesPorRangoParams struct {
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

func (q *Queries) ListDevolucionesPorRango(ctx context.Context, arg ListDevolucionesPorRangoParams) ([]DevolucionesGarantia, error) {
	rows, err := q.db.Query(ctx, listDevolucionesPorRango, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DevolucionesGarantia
	for rows.Next() {
		var i DevolucionesGarantia
		if err := rows.Scan(
			&i.ID,
			&i.Folio,
			&i.ClienteID,
			&i.PedidoFolio,
			&i.Tipo,
			&i.NumerosParte,
			&i.NotaCliente,
			&i.Evidencias,
			&i.Estatus,
			&i.NotaAdministrador,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.Cantidades,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
