// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: estado_cuenta.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const obtenerEstadoCuentaPorCveCte = `-- name: ObtenerEstadoCuentaPorCveCte :many
SELECT
    c.cve_cte,
    c.nom_cte,
    c.dia_cre AS dias_credito,
    c.lim_cre AS limite_credito,
    f.id AS factura_id,
    f.no_fac AS folio,
    f.falta_fac AS fecha_emision,
    f.f_pago AS fecha_vencimiento,
    f.total_fac AS monto_total,
    f.saldo_fac AS saldo_pendiente,
    f.status_fac AS estatus
FROM clientes_integracion c
INNER JOIN facturas_integracion f ON c.cve_cte = f.cve_cte
WHERE c.cve_cte = $1
ORDER BY f.falta_fac DESC
`

type ObtenerEstadoCuentaPorCveCteRow struct {
	CveCte           pgtype.Int4      `json:"cve_cte"`
	NomCte           pgtype.Text      `json:"nom_cte"`
	DiasCredito      pgtype.Int4      `json:"dias_credito"`
	LimiteCredito    pgtype.Numeric   `json:"limite_credito"`
	FacturaID        int32            `json:"factura_id"`
	Folio            string           `json:"folio"`
	FechaEmision     pgtype.Timestamp `json:"fecha_emision"`
	FechaVencimiento pgtype.Timestamp `json:"fecha_vencimiento"`
	MontoTotal       pgtype.Numeric   `json:"monto_total"`
	SaldoPendiente   pgtype.Numeric   `json:"saldo_pendiente"`
	Estatus          pgtype.Text      `json:"estatus"`
}

func (q *Queries) ObtenerEstadoCuentaPorCveCte(ctx context.Context, cveCte pgtype.Int4) ([]ObtenerEstadoCuentaPorCveCteRow, error) {
	rows, err := q.db.Query(ctx, obtenerEstadoCuentaPorCveCte, cveCte)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObtenerEstadoCuentaPorCveCteRow
	for rows.Next() {
		var i ObtenerEstadoCuentaPorCveCteRow
		if err := rows.Scan(
			&i.CveCte,
			&i.NomCte,
			&i.DiasCredito,
			&i.LimiteCredito,
			&i.FacturaID,
			&i.Folio,
			&i.FechaEmision,
			&i.FechaVencimiento,
			&i.MontoTotal,
			&i.SaldoPendiente,
			&i.Estatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
