// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: existencias_integracion.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const crearExistenciaIntegracion = `-- name: CrearExistenciaIntegracion :one
INSERT INTO existencias_integracion (
    cse_prod, cve_prod, lugar, existencia, med_prod, fech_umod, 
    inv_ini, lote, fech_lote, ref_lote, costo_prom, new_med, 
    costuepeps, costoprom2
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, cse_prod, cve_prod, lugar, existencia, med_prod, fech_umod, inv_ini, lote, fech_lote, ref_lote, costo_prom, new_med, costuepeps, costoprom2
`

type CrearExistenciaIntegracionParams struct {
	CseProd    pgtype.Text      `json:"cse_prod"`
	CveProd    string           `json:"cve_prod"`
	Lugar      string           `json:"lugar"`
	Existencia pgtype.Numeric   `json:"existencia"`
	MedProd    pgtype.Numeric   `json:"med_prod"`
	FechUmod   pgtype.Timestamp `json:"fech_umod"`
	InvIni     pgtype.Int8      `json:"inv_ini"`
	Lote       pgtype.Text      `json:"lote"`
	FechLote   pgtype.Timestamp `json:"fech_lote"`
	RefLote    pgtype.Text      `json:"ref_lote"`
	CostoProm  pgtype.Numeric   `json:"costo_prom"`
	NewMed     pgtype.Text      `json:"new_med"`
	Costuepeps pgtype.Numeric   `json:"costuepeps"`
	Costoprom2 pgtype.Numeric   `json:"costoprom2"`
}

func (q *Queries) CrearExistenciaIntegracion(ctx context.Context, arg CrearExistenciaIntegracionParams) (ExistenciasIntegracion, error) {
	row := q.db.QueryRow(ctx, crearExistenciaIntegracion,
		arg.CseProd,
		arg.CveProd,
		arg.Lugar,
		arg.Existencia,
		arg.MedProd,
		arg.FechUmod,
		arg.InvIni,
		arg.Lote,
		arg.FechLote,
		arg.RefLote,
		arg.CostoProm,
		arg.NewMed,
		arg.Costuepeps,
		arg.Costoprom2,
	)
	var i ExistenciasIntegracion
	err := row.Scan(
		&i.ID,
		&i.CseProd,
		&i.CveProd,
		&i.Lugar,
		&i.Existencia,
		&i.MedProd,
		&i.FechUmod,
		&i.InvIni,
		&i.Lote,
		&i.FechLote,
		&i.RefLote,
		&i.CostoProm,
		&i.NewMed,
		&i.Costuepeps,
		&i.Costoprom2,
	)
	return i, err
}

const obtenerExistenciaPorProductoYLugar = `-- name: ObtenerExistenciaPorProductoYLugar :one
SELECT id, cse_prod, cve_prod, lugar, existencia, med_prod, fech_umod, inv_ini, lote, fech_lote, ref_lote, costo_prom, new_med, costuepeps, costoprom2 FROM existencias_integracion
WHERE cve_prod = $1 AND lugar = $2 LIMIT 1
`

type ObtenerExistenciaPorProductoYLugarParams struct {
	CveProd string `json:"cve_prod"`
	Lugar   string `json:"lugar"`
}

func (q *Queries) ObtenerExistenciaPorProductoYLugar(ctx context.Context, arg ObtenerExistenciaPorProductoYLugarParams) (ExistenciasIntegracion, error) {
	row := q.db.QueryRow(ctx, obtenerExistenciaPorProductoYLugar, arg.CveProd, arg.Lugar)
	var i ExistenciasIntegracion
	err := row.Scan(
		&i.ID,
		&i.CseProd,
		&i.CveProd,
		&i.Lugar,
		&i.Existencia,
		&i.MedProd,
		&i.FechUmod,
		&i.InvIni,
		&i.Lote,
		&i.FechLote,
		&i.RefLote,
		&i.CostoProm,
		&i.NewMed,
		&i.Costuepeps,
		&i.Costoprom2,
	)
	return i, err
}

const obtenerExistenciasPorProducto = `-- name: ObtenerExistenciasPorProducto :many
SELECT id, cse_prod, cve_prod, lugar, existencia, med_prod, fech_umod, inv_ini, lote, fech_lote, ref_lote, costo_prom, new_med, costuepeps, costoprom2 FROM existencias_integracion
WHERE cve_prod = $1
`

func (q *Queries) ObtenerExistenciasPorProducto(ctx context.Context, cveProd string) ([]ExistenciasIntegracion, error) {
	rows, err := q.db.Query(ctx, obtenerExistenciasPorProducto, cveProd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExistenciasIntegracion
	for rows.Next() {
		var i ExistenciasIntegracion
		if err := rows.Scan(
			&i.ID,
			&i.CseProd,
			&i.CveProd,
			&i.Lugar,
			&i.Existencia,
			&i.MedProd,
			&i.FechUmod,
			&i.InvIni,
			&i.Lote,
			&i.FechLote,
			&i.RefLote,
			&i.CostoProm,
			&i.NewMed,
			&i.Costuepeps,
			&i.Costoprom2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerTodasLasExistencias = `-- name: ObtenerTodasLasExistencias :many
SELECT id, cse_prod, cve_prod, lugar, existencia, med_prod, fech_umod, inv_ini, lote, fech_lote, ref_lote, costo_prom, new_med, costuepeps, costoprom2 FROM existencias_integracion
`

func (q *Queries) ObtenerTodasLasExistencias(ctx context.Context) ([]ExistenciasIntegracion, error) {
	rows, err := q.db.Query(ctx, obtenerTodasLasExistencias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExistenciasIntegracion
	for rows.Next() {
		var i ExistenciasIntegracion
		if err := rows.Scan(
			&i.ID,
			&i.CseProd,
			&i.CveProd,
			&i.Lugar,
			&i.Existencia,
			&i.MedProd,
			&i.FechUmod,
			&i.InvIni,
			&i.Lote,
			&i.FechLote,
			&i.RefLote,
			&i.CostoProm,
			&i.NewMed,
			&i.Costuepeps,
			&i.Costoprom2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExistenciaIntegracion = `-- name: UpsertExistenciaIntegracion :one
INSERT INTO existencias_integracion (
    cse_prod, cve_prod, lugar, existencia, med_prod, fech_umod, 
    inv_ini, lote, fech_lote, ref_lote, costo_prom, new_med, 
    costuepeps, costoprom2
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (cve_prod, lugar) DO UPDATE SET
    cse_prod = EXCLUDED.cse_prod,
    existencia = EXCLUDED.existencia,
    med_prod = EXCLUDED.med_prod,
    fech_umod = EXCLUDED.fech_umod,
    inv_ini = EXCLUDED.inv_ini,
    lote = EXCLUDED.lote,
    fech_lote = EXCLUDED.fech_lote,
    ref_lote = EXCLUDED.ref_lote,
    costo_prom = EXCLUDED.costo_prom,
    new_med = EXCLUDED.new_med,
    costuepeps = EXCLUDED.costuepeps,
    costoprom2 = EXCLUDED.costoprom2
RETURNING id, cse_prod, cve_prod, lugar, existencia, med_prod, fech_umod, inv_ini, lote, fech_lote, ref_lote, costo_prom, new_med, costuepeps, costoprom2
`

type UpsertExistenciaIntegracionParams struct {
	CseProd    pgtype.Text      `json:"cse_prod"`
	CveProd    string           `json:"cve_prod"`
	Lugar      string           `json:"lugar"`
	Existencia pgtype.Numeric   `json:"existencia"`
	MedProd    pgtype.Numeric   `json:"med_prod"`
	FechUmod   pgtype.Timestamp `json:"fech_umod"`
	InvIni     pgtype.Int8      `json:"inv_ini"`
	Lote       pgtype.Text      `json:"lote"`
	FechLote   pgtype.Timestamp `json:"fech_lote"`
	RefLote    pgtype.Text      `json:"ref_lote"`
	CostoProm  pgtype.Numeric   `json:"costo_prom"`
	NewMed     pgtype.Text      `json:"new_med"`
	Costuepeps pgtype.Numeric   `json:"costuepeps"`
	Costoprom2 pgtype.Numeric   `json:"costoprom2"`
}

func (q *Queries) UpsertExistenciaIntegracion(ctx context.Context, arg UpsertExistenciaIntegracionParams) (ExistenciasIntegracion, error) {
	row := q.db.QueryRow(ctx, upsertExistenciaIntegracion,
		arg.CseProd,
		arg.CveProd,
		arg.Lugar,
		arg.Existencia,
		arg.MedProd,
		arg.FechUmod,
		arg.InvIni,
		arg.Lote,
		arg.FechLote,
		arg.RefLote,
		arg.CostoProm,
		arg.NewMed,
		arg.Costuepeps,
		arg.Costoprom2,
	)
	var i ExistenciasIntegracion
	err := row.Scan(
		&i.ID,
		&i.CseProd,
		&i.CveProd,
		&i.Lugar,
		&i.Existencia,
		&i.MedProd,
		&i.FechUmod,
		&i.InvIni,
		&i.Lote,
		&i.FechLote,
		&i.RefLote,
		&i.CostoProm,
		&i.NewMed,
		&i.Costuepeps,
		&i.Costoprom2,
	)
	return i, err
}
