// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: facturas_integracion.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const crearFacturaIntegracion = `-- name: CrearFacturaIntegracion :one
INSERT INTO facturas_integracion (
    no_fac, no_ped, cve_cte, cve_age, falta_fac, status_fac, subt_fac, descuento,
    descue, total_fac, saldo_fac, f_pago, contrarec, lugar, cve_factu, cve_mon,
    tip_cam, saldo_fac2, staley, cve_suc, mes, anio, usuario, trans, staley2,
    ped_int, com_cob, cierre, u_tip_cam, cve_age2, com_cob2, din_com, din_com2,
    fech_sal, fech_emb, cve_flet, tot_flet, tot_env, prec_flet, prv_real, timp_car,
    numpol, numpolcan, imp_carac, pesotot, retiva_fac, deposito, suc_depo, status_2,
    cvedirent, reimpre, descue2, descue3, descue4, no_peda, cve_suca, cve_factua,
    cve_entre, ieps
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59
) RETURNING id, no_fac, no_ped, cve_cte, cve_age, falta_fac, status_fac, subt_fac, descuento, descue, total_fac, saldo_fac, f_pago, contrarec, lugar, cve_factu, cve_mon, tip_cam, saldo_fac2, staley, cve_suc, mes, anio, usuario, trans, staley2, ped_int, com_cob, cierre, u_tip_cam, cve_age2, com_cob2, din_com, din_com2, fech_sal, fech_emb, cve_flet, tot_flet, tot_env, prec_flet, prv_real, timp_car, numpol, numpolcan, imp_carac, pesotot, retiva_fac, deposito, suc_depo, status_2, cvedirent, reimpre, descue2, descue3, descue4, no_peda, cve_suca, cve_factua, cve_entre, ieps
`

type CrearFacturaIntegracionParams struct {
	NoFac     string           `json:"no_fac"`
	NoPed     pgtype.Text      `json:"no_ped"`
	CveCte    pgtype.Int4      `json:"cve_cte"`
	CveAge    pgtype.Int4      `json:"cve_age"`
	FaltaFac  pgtype.Timestamp `json:"falta_fac"`
	StatusFac pgtype.Text      `json:"status_fac"`
	SubtFac   pgtype.Numeric   `json:"subt_fac"`
	Descuento pgtype.Numeric   `json:"descuento"`
	Descue    pgtype.Numeric   `json:"descue"`
	TotalFac  pgtype.Numeric   `json:"total_fac"`
	SaldoFac  pgtype.Numeric   `json:"saldo_fac"`
	FPago     pgtype.Timestamp `json:"f_pago"`
	Contrarec pgtype.Text      `json:"contrarec"`
	Lugar     pgtype.Text      `json:"lugar"`
	CveFactu  pgtype.Text      `json:"cve_factu"`
	CveMon    pgtype.Text      `json:"cve_mon"`
	TipCam    pgtype.Numeric   `json:"tip_cam"`
	SaldoFac2 pgtype.Numeric   `json:"saldo_fac2"`
	Staley    pgtype.Text      `json:"staley"`
	CveSuc    pgtype.Int4      `json:"cve_suc"`
	Mes       pgtype.Int4      `json:"mes"`
	Anio      pgtype.Int4      `json:"anio"`
	Usuario   pgtype.Text      `json:"usuario"`
	Trans     pgtype.Text      `json:"trans"`
	Staley2   pgtype.Text      `json:"staley2"`
	PedInt    pgtype.Text      `json:"ped_int"`
	ComCob    pgtype.Numeric   `json:"com_cob"`
	Cierre    pgtype.Timestamp `json:"cierre"`
	UTipCam   pgtype.Numeric   `json:"u_tip_cam"`
	CveAge2   pgtype.Int4      `json:"cve_age2"`
	ComCob2   pgtype.Numeric   `json:"com_cob2"`
	DinCom    pgtype.Numeric   `json:"din_com"`
	DinCom2   pgtype.Numeric   `json:"din_com2"`
	FechSal   pgtype.Timestamp `json:"fech_sal"`
	FechEmb   pgtype.Timestamp `json:"fech_emb"`
	CveFlet   pgtype.Text      `json:"cve_flet"`
	TotFlet   pgtype.Numeric   `json:"tot_flet"`
	TotEnv    pgtype.Numeric   `json:"tot_env"`
	PrecFlet  pgtype.Numeric   `json:"prec_flet"`
	PrvReal   pgtype.Text      `json:"prv_real"`
	TimpCar   pgtype.Numeric   `json:"timp_car"`
	Numpol    pgtype.Text      `json:"numpol"`
	Numpolcan pgtype.Text      `json:"numpolcan"`
	ImpCarac  pgtype.Numeric   `json:"imp_carac"`
	Pesotot   pgtype.Numeric   `json:"pesotot"`
	RetivaFac pgtype.Numeric   `json:"retiva_fac"`
	Deposito  pgtype.Numeric   `json:"deposito"`
	SucDepo   pgtype.Text      `json:"suc_depo"`
	Status2   pgtype.Text      `json:"status_2"`
	Cvedirent pgtype.Text      `json:"cvedirent"`
	Reimpre   pgtype.Int4      `json:"reimpre"`
	Descue2   pgtype.Numeric   `json:"descue2"`
	Descue3   pgtype.Numeric   `json:"descue3"`
	Descue4   pgtype.Numeric   `json:"descue4"`
	NoPeda    pgtype.Text      `json:"no_peda"`
	CveSuca   pgtype.Text      `json:"cve_suca"`
	CveFactua pgtype.Text      `json:"cve_factua"`
	CveEntre  pgtype.Text      `json:"cve_entre"`
	Ieps      pgtype.Numeric   `json:"ieps"`
}

func (q *Queries) CrearFacturaIntegracion(ctx context.Context, arg CrearFacturaIntegracionParams) (FacturasIntegracion, error) {
	row := q.db.QueryRow(ctx, crearFacturaIntegracion,
		arg.NoFac,
		arg.NoPed,
		arg.CveCte,
		arg.CveAge,
		arg.FaltaFac,
		arg.StatusFac,
		arg.SubtFac,
		arg.Descuento,
		arg.Descue,
		arg.TotalFac,
		arg.SaldoFac,
		arg.FPago,
		arg.Contrarec,
		arg.Lugar,
		arg.CveFactu,
		arg.CveMon,
		arg.TipCam,
		arg.SaldoFac2,
		arg.Staley,
		arg.CveSuc,
		arg.Mes,
		arg.Anio,
		arg.Usuario,
		arg.Trans,
		arg.Staley2,
		arg.PedInt,
		arg.ComCob,
		arg.Cierre,
		arg.UTipCam,
		arg.CveAge2,
		arg.ComCob2,
		arg.DinCom,
		arg.DinCom2,
		arg.FechSal,
		arg.FechEmb,
		arg.CveFlet,
		arg.TotFlet,
		arg.TotEnv,
		arg.PrecFlet,
		arg.PrvReal,
		arg.TimpCar,
		arg.Numpol,
		arg.Numpolcan,
		arg.ImpCarac,
		arg.Pesotot,
		arg.RetivaFac,
		arg.Deposito,
		arg.SucDepo,
		arg.Status2,
		arg.Cvedirent,
		arg.Reimpre,
		arg.Descue2,
		arg.Descue3,
		arg.Descue4,
		arg.NoPeda,
		arg.CveSuca,
		arg.CveFactua,
		arg.CveEntre,
		arg.Ieps,
	)
	var i FacturasIntegracion
	err := row.Scan(
		&i.ID,
		&i.NoFac,
		&i.NoPed,
		&i.CveCte,
		&i.CveAge,
		&i.FaltaFac,
		&i.StatusFac,
		&i.SubtFac,
		&i.Descuento,
		&i.Descue,
		&i.TotalFac,
		&i.SaldoFac,
		&i.FPago,
		&i.Contrarec,
		&i.Lugar,
		&i.CveFactu,
		&i.CveMon,
		&i.TipCam,
		&i.SaldoFac2,
		&i.Staley,
		&i.CveSuc,
		&i.Mes,
		&i.Anio,
		&i.Usuario,
		&i.Trans,
		&i.Staley2,
		&i.PedInt,
		&i.ComCob,
		&i.Cierre,
		&i.UTipCam,
		&i.CveAge2,
		&i.ComCob2,
		&i.DinCom,
		&i.DinCom2,
		&i.FechSal,
		&i.FechEmb,
		&i.CveFlet,
		&i.TotFlet,
		&i.TotEnv,
		&i.PrecFlet,
		&i.PrvReal,
		&i.TimpCar,
		&i.Numpol,
		&i.Numpolcan,
		&i.ImpCarac,
		&i.Pesotot,
		&i.RetivaFac,
		&i.Deposito,
		&i.SucDepo,
		&i.Status2,
		&i.Cvedirent,
		&i.Reimpre,
		&i.Descue2,
		&i.Descue3,
		&i.Descue4,
		&i.NoPeda,
		&i.CveSuca,
		&i.CveFactua,
		&i.CveEntre,
		&i.Ieps,
	)
	return i, err
}

const obtenerFacturaIntegracion = `-- name: ObtenerFacturaIntegracion :one
SELECT id, no_fac, no_ped, cve_cte, cve_age, falta_fac, status_fac, subt_fac, descuento, descue, total_fac, saldo_fac, f_pago, contrarec, lugar, cve_factu, cve_mon, tip_cam, saldo_fac2, staley, cve_suc, mes, anio, usuario, trans, staley2, ped_int, com_cob, cierre, u_tip_cam, cve_age2, com_cob2, din_com, din_com2, fech_sal, fech_emb, cve_flet, tot_flet, tot_env, prec_flet, prv_real, timp_car, numpol, numpolcan, imp_carac, pesotot, retiva_fac, deposito, suc_depo, status_2, cvedirent, reimpre, descue2, descue3, descue4, no_peda, cve_suca, cve_factua, cve_entre, ieps FROM facturas_integracion
WHERE id = $1 LIMIT 1
`

func (q *Queries) ObtenerFacturaIntegracion(ctx context.Context, id int32) (FacturasIntegracion, error) {
	row := q.db.QueryRow(ctx, obtenerFacturaIntegracion, id)
	var i FacturasIntegracion
	err := row.Scan(
		&i.ID,
		&i.NoFac,
		&i.NoPed,
		&i.CveCte,
		&i.CveAge,
		&i.FaltaFac,
		&i.StatusFac,
		&i.SubtFac,
		&i.Descuento,
		&i.Descue,
		&i.TotalFac,
		&i.SaldoFac,
		&i.FPago,
		&i.Contrarec,
		&i.Lugar,
		&i.CveFactu,
		&i.CveMon,
		&i.TipCam,
		&i.SaldoFac2,
		&i.Staley,
		&i.CveSuc,
		&i.Mes,
		&i.Anio,
		&i.Usuario,
		&i.Trans,
		&i.Staley2,
		&i.PedInt,
		&i.ComCob,
		&i.Cierre,
		&i.UTipCam,
		&i.CveAge2,
		&i.ComCob2,
		&i.DinCom,
		&i.DinCom2,
		&i.FechSal,
		&i.FechEmb,
		&i.CveFlet,
		&i.TotFlet,
		&i.TotEnv,
		&i.PrecFlet,
		&i.PrvReal,
		&i.TimpCar,
		&i.Numpol,
		&i.Numpolcan,
		&i.ImpCarac,
		&i.Pesotot,
		&i.RetivaFac,
		&i.Deposito,
		&i.SucDepo,
		&i.Status2,
		&i.Cvedirent,
		&i.Reimpre,
		&i.Descue2,
		&i.Descue3,
		&i.Descue4,
		&i.NoPeda,
		&i.CveSuca,
		&i.CveFactua,
		&i.CveEntre,
		&i.Ieps,
	)
	return i, err
}

const obtenerFacturaIntegracionPorNoFac = `-- name: ObtenerFacturaIntegracionPorNoFac :one
SELECT id, no_fac, no_ped, cve_cte, cve_age, falta_fac, status_fac, subt_fac, descuento, descue, total_fac, saldo_fac, f_pago, contrarec, lugar, cve_factu, cve_mon, tip_cam, saldo_fac2, staley, cve_suc, mes, anio, usuario, trans, staley2, ped_int, com_cob, cierre, u_tip_cam, cve_age2, com_cob2, din_com, din_com2, fech_sal, fech_emb, cve_flet, tot_flet, tot_env, prec_flet, prv_real, timp_car, numpol, numpolcan, imp_carac, pesotot, retiva_fac, deposito, suc_depo, status_2, cvedirent, reimpre, descue2, descue3, descue4, no_peda, cve_suca, cve_factua, cve_entre, ieps FROM facturas_integracion
WHERE no_fac = $1 LIMIT 1
`

func (q *Queries) ObtenerFacturaIntegracionPorNoFac(ctx context.Context, noFac string) (FacturasIntegracion, error) {
	row := q.db.QueryRow(ctx, obtenerFacturaIntegracionPorNoFac, noFac)
	var i FacturasIntegracion
	err := row.Scan(
		&i.ID,
		&i.NoFac,
		&i.NoPed,
		&i.CveCte,
		&i.CveAge,
		&i.FaltaFac,
		&i.StatusFac,
		&i.SubtFac,
		&i.Descuento,
		&i.Descue,
		&i.TotalFac,
		&i.SaldoFac,
		&i.FPago,
		&i.Contrarec,
		&i.Lugar,
		&i.CveFactu,
		&i.CveMon,
		&i.TipCam,
		&i.SaldoFac2,
		&i.Staley,
		&i.CveSuc,
		&i.Mes,
		&i.Anio,
		&i.Usuario,
		&i.Trans,
		&i.Staley2,
		&i.PedInt,
		&i.ComCob,
		&i.Cierre,
		&i.UTipCam,
		&i.CveAge2,
		&i.ComCob2,
		&i.DinCom,
		&i.DinCom2,
		&i.FechSal,
		&i.FechEmb,
		&i.CveFlet,
		&i.TotFlet,
		&i.TotEnv,
		&i.PrecFlet,
		&i.PrvReal,
		&i.TimpCar,
		&i.Numpol,
		&i.Numpolcan,
		&i.ImpCarac,
		&i.Pesotot,
		&i.RetivaFac,
		&i.Deposito,
		&i.SucDepo,
		&i.Status2,
		&i.Cvedirent,
		&i.Reimpre,
		&i.Descue2,
		&i.Descue3,
		&i.Descue4,
		&i.NoPeda,
		&i.CveSuca,
		&i.CveFactua,
		&i.CveEntre,
		&i.Ieps,
	)
	return i, err
}

const obtenerFacturasIntegracion = `-- name: ObtenerFacturasIntegracion :many
SELECT id, no_fac, no_ped, cve_cte, cve_age, falta_fac, status_fac, subt_fac, descuento, descue, total_fac, saldo_fac, f_pago, contrarec, lugar, cve_factu, cve_mon, tip_cam, saldo_fac2, staley, cve_suc, mes, anio, usuario, trans, staley2, ped_int, com_cob, cierre, u_tip_cam, cve_age2, com_cob2, din_com, din_com2, fech_sal, fech_emb, cve_flet, tot_flet, tot_env, prec_flet, prv_real, timp_car, numpol, numpolcan, imp_carac, pesotot, retiva_fac, deposito, suc_depo, status_2, cvedirent, reimpre, descue2, descue3, descue4, no_peda, cve_suca, cve_factua, cve_entre, ieps FROM facturas_integracion order by falta_fac desc, no_fac desc
`

func (q *Queries) ObtenerFacturasIntegracion(ctx context.Context) ([]FacturasIntegracion, error) {
	rows, err := q.db.Query(ctx, obtenerFacturasIntegracion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacturasIntegracion
	for rows.Next() {
		var i FacturasIntegracion
		if err := rows.Scan(
			&i.ID,
			&i.NoFac,
			&i.NoPed,
			&i.CveCte,
			&i.CveAge,
			&i.FaltaFac,
			&i.StatusFac,
			&i.SubtFac,
			&i.Descuento,
			&i.Descue,
			&i.TotalFac,
			&i.SaldoFac,
			&i.FPago,
			&i.Contrarec,
			&i.Lugar,
			&i.CveFactu,
			&i.CveMon,
			&i.TipCam,
			&i.SaldoFac2,
			&i.Staley,
			&i.CveSuc,
			&i.Mes,
			&i.Anio,
			&i.Usuario,
			&i.Trans,
			&i.Staley2,
			&i.PedInt,
			&i.ComCob,
			&i.Cierre,
			&i.UTipCam,
			&i.CveAge2,
			&i.ComCob2,
			&i.DinCom,
			&i.DinCom2,
			&i.FechSal,
			&i.FechEmb,
			&i.CveFlet,
			&i.TotFlet,
			&i.TotEnv,
			&i.PrecFlet,
			&i.PrvReal,
			&i.TimpCar,
			&i.Numpol,
			&i.Numpolcan,
			&i.ImpCarac,
			&i.Pesotot,
			&i.RetivaFac,
			&i.Deposito,
			&i.SucDepo,
			&i.Status2,
			&i.Cvedirent,
			&i.Reimpre,
			&i.Descue2,
			&i.Descue3,
			&i.Descue4,
			&i.NoPeda,
			&i.CveSuca,
			&i.CveFactua,
			&i.CveEntre,
			&i.Ieps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFacturaIntegracion = `-- name: UpsertFacturaIntegracion :one
INSERT INTO facturas_integracion (
    no_fac, no_ped, cve_cte, cve_age, falta_fac, status_fac, subt_fac, descuento,
    descue, total_fac, saldo_fac, f_pago, contrarec, lugar, cve_factu, cve_mon,
    tip_cam, saldo_fac2, staley, cve_suc, mes, anio, usuario, trans, staley2,
    ped_int, com_cob, cierre, u_tip_cam, cve_age2, com_cob2, din_com, din_com2,
    fech_sal, fech_emb, cve_flet, tot_flet, tot_env, prec_flet, prv_real, timp_car,
    numpol, numpolcan, imp_carac, pesotot, retiva_fac, deposito, suc_depo, status_2,
    cvedirent, reimpre, descue2, descue3, descue4, no_peda, cve_suca, cve_factua,
    cve_entre, ieps
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59
)
ON CONFLICT (no_fac, cve_factu) DO UPDATE SET
    no_ped = EXCLUDED.no_ped,
    cve_cte = EXCLUDED.cve_cte,
    cve_age = EXCLUDED.cve_age,
    falta_fac = EXCLUDED.falta_fac,
    status_fac = EXCLUDED.status_fac,
    subt_fac = EXCLUDED.subt_fac,
    descuento = EXCLUDED.descuento,
    descue = EXCLUDED.descue,
    total_fac = EXCLUDED.total_fac,
    saldo_fac = EXCLUDED.saldo_fac,
    f_pago = EXCLUDED.f_pago,
    contrarec = EXCLUDED.contrarec,
    lugar = EXCLUDED.lugar,
    cve_mon = EXCLUDED.cve_mon,
    tip_cam = EXCLUDED.tip_cam,
    saldo_fac2 = EXCLUDED.saldo_fac2,
    staley = EXCLUDED.staley,
    cve_suc = EXCLUDED.cve_suc,
    mes = EXCLUDED.mes,
    anio = EXCLUDED.anio,
    usuario = EXCLUDED.usuario,
    trans = EXCLUDED.trans,
    staley2 = EXCLUDED.staley2,
    ped_int = EXCLUDED.ped_int,
    com_cob = EXCLUDED.com_cob,
    cierre = EXCLUDED.cierre,
    u_tip_cam = EXCLUDED.u_tip_cam,
    cve_age2 = EXCLUDED.cve_age2,
    com_cob2 = EXCLUDED.com_cob2,
    din_com = EXCLUDED.din_com,
    din_com2 = EXCLUDED.din_com2,
    fech_sal = EXCLUDED.fech_sal,
    fech_emb = EXCLUDED.fech_emb,
    cve_flet = EXCLUDED.cve_flet,
    tot_flet = EXCLUDED.tot_flet,
    tot_env = EXCLUDED.tot_env,
    prec_flet = EXCLUDED.prec_flet,
    prv_real = EXCLUDED.prv_real,
    timp_car = EXCLUDED.timp_car,
    numpol = EXCLUDED.numpol,
    numpolcan = EXCLUDED.numpolcan,
    imp_carac = EXCLUDED.imp_carac,
    pesotot = EXCLUDED.pesotot,
    retiva_fac = EXCLUDED.retiva_fac,
    deposito = EXCLUDED.deposito,
    suc_depo = EXCLUDED.suc_depo,
    status_2 = EXCLUDED.status_2,
    cvedirent = EXCLUDED.cvedirent,
    reimpre = EXCLUDED.reimpre,
    descue2 = EXCLUDED.descue2,
    descue3 = EXCLUDED.descue3,
    descue4 = EXCLUDED.descue4,
    no_peda = EXCLUDED.no_peda,
    cve_suca = EXCLUDED.cve_suca,
    cve_factua = EXCLUDED.cve_factua,
    cve_entre = EXCLUDED.cve_entre,
    ieps = EXCLUDED.ieps
RETURNING id, no_fac, no_ped, cve_cte, cve_age, falta_fac, status_fac, subt_fac, descuento, descue, total_fac, saldo_fac, f_pago, contrarec, lugar, cve_factu, cve_mon, tip_cam, saldo_fac2, staley, cve_suc, mes, anio, usuario, trans, staley2, ped_int, com_cob, cierre, u_tip_cam, cve_age2, com_cob2, din_com, din_com2, fech_sal, fech_emb, cve_flet, tot_flet, tot_env, prec_flet, prv_real, timp_car, numpol, numpolcan, imp_carac, pesotot, retiva_fac, deposito, suc_depo, status_2, cvedirent, reimpre, descue2, descue3, descue4, no_peda, cve_suca, cve_factua, cve_entre, ieps
`

type UpsertFacturaIntegracionParams struct {
	NoFac     string           `json:"no_fac"`
	NoPed     pgtype.Text      `json:"no_ped"`
	CveCte    pgtype.Int4      `json:"cve_cte"`
	CveAge    pgtype.Int4      `json:"cve_age"`
	FaltaFac  pgtype.Timestamp `json:"falta_fac"`
	StatusFac pgtype.Text      `json:"status_fac"`
	SubtFac   pgtype.Numeric   `json:"subt_fac"`
	Descuento pgtype.Numeric   `json:"descuento"`
	Descue    pgtype.Numeric   `json:"descue"`
	TotalFac  pgtype.Numeric   `json:"total_fac"`
	SaldoFac  pgtype.Numeric   `json:"saldo_fac"`
	FPago     pgtype.Timestamp `json:"f_pago"`
	Contrarec pgtype.Text      `json:"contrarec"`
	Lugar     pgtype.Text      `json:"lugar"`
	CveFactu  pgtype.Text      `json:"cve_factu"`
	CveMon    pgtype.Text      `json:"cve_mon"`
	TipCam    pgtype.Numeric   `json:"tip_cam"`
	SaldoFac2 pgtype.Numeric   `json:"saldo_fac2"`
	Staley    pgtype.Text      `json:"staley"`
	CveSuc    pgtype.Int4      `json:"cve_suc"`
	Mes       pgtype.Int4      `json:"mes"`
	Anio      pgtype.Int4      `json:"anio"`
	Usuario   pgtype.Text      `json:"usuario"`
	Trans     pgtype.Text      `json:"trans"`
	Staley2   pgtype.Text      `json:"staley2"`
	PedInt    pgtype.Text      `json:"ped_int"`
	ComCob    pgtype.Numeric   `json:"com_cob"`
	Cierre    pgtype.Timestamp `json:"cierre"`
	UTipCam   pgtype.Numeric   `json:"u_tip_cam"`
	CveAge2   pgtype.Int4      `json:"cve_age2"`
	ComCob2   pgtype.Numeric   `json:"com_cob2"`
	DinCom    pgtype.Numeric   `json:"din_com"`
	DinCom2   pgtype.Numeric   `json:"din_com2"`
	FechSal   pgtype.Timestamp `json:"fech_sal"`
	FechEmb   pgtype.Timestamp `json:"fech_emb"`
	CveFlet   pgtype.Text      `json:"cve_flet"`
	TotFlet   pgtype.Numeric   `json:"tot_flet"`
	TotEnv    pgtype.Numeric   `json:"tot_env"`
	PrecFlet  pgtype.Numeric   `json:"prec_flet"`
	PrvReal   pgtype.Text      `json:"prv_real"`
	TimpCar   pgtype.Numeric   `json:"timp_car"`
	Numpol    pgtype.Text      `json:"numpol"`
	Numpolcan pgtype.Text      `json:"numpolcan"`
	ImpCarac  pgtype.Numeric   `json:"imp_carac"`
	Pesotot   pgtype.Numeric   `json:"pesotot"`
	RetivaFac pgtype.Numeric   `json:"retiva_fac"`
	Deposito  pgtype.Numeric   `json:"deposito"`
	SucDepo   pgtype.Text      `json:"suc_depo"`
	Status2   pgtype.Text      `json:"status_2"`
	Cvedirent pgtype.Text      `json:"cvedirent"`
	Reimpre   pgtype.Int4      `json:"reimpre"`
	Descue2   pgtype.Numeric   `json:"descue2"`
	Descue3   pgtype.Numeric   `json:"descue3"`
	Descue4   pgtype.Numeric   `json:"descue4"`
	NoPeda    pgtype.Text      `json:"no_peda"`
	CveSuca   pgtype.Text      `json:"cve_suca"`
	CveFactua pgtype.Text      `json:"cve_factua"`
	CveEntre  pgtype.Text      `json:"cve_entre"`
	Ieps      pgtype.Numeric   `json:"ieps"`
}

func (q *Queries) UpsertFacturaIntegracion(ctx context.Context, arg UpsertFacturaIntegracionParams) (FacturasIntegracion, error) {
	row := q.db.QueryRow(ctx, upsertFacturaIntegracion,
		arg.NoFac,
		arg.NoPed,
		arg.CveCte,
		arg.CveAge,
		arg.FaltaFac,
		arg.StatusFac,
		arg.SubtFac,
		arg.Descuento,
		arg.Descue,
		arg.TotalFac,
		arg.SaldoFac,
		arg.FPago,
		arg.Contrarec,
		arg.Lugar,
		arg.CveFactu,
		arg.CveMon,
		arg.TipCam,
		arg.SaldoFac2,
		arg.Staley,
		arg.CveSuc,
		arg.Mes,
		arg.Anio,
		arg.Usuario,
		arg.Trans,
		arg.Staley2,
		arg.PedInt,
		arg.ComCob,
		arg.Cierre,
		arg.UTipCam,
		arg.CveAge2,
		arg.ComCob2,
		arg.DinCom,
		arg.DinCom2,
		arg.FechSal,
		arg.FechEmb,
		arg.CveFlet,
		arg.TotFlet,
		arg.TotEnv,
		arg.PrecFlet,
		arg.PrvReal,
		arg.TimpCar,
		arg.Numpol,
		arg.Numpolcan,
		arg.ImpCarac,
		arg.Pesotot,
		arg.RetivaFac,
		arg.Deposito,
		arg.SucDepo,
		arg.Status2,
		arg.Cvedirent,
		arg.Reimpre,
		arg.Descue2,
		arg.Descue3,
		arg.Descue4,
		arg.NoPeda,
		arg.CveSuca,
		arg.CveFactua,
		arg.CveEntre,
		arg.Ieps,
	)
	var i FacturasIntegracion
	err := row.Scan(
		&i.ID,
		&i.NoFac,
		&i.NoPed,
		&i.CveCte,
		&i.CveAge,
		&i.FaltaFac,
		&i.StatusFac,
		&i.SubtFac,
		&i.Descuento,
		&i.Descue,
		&i.TotalFac,
		&i.SaldoFac,
		&i.FPago,
		&i.Contrarec,
		&i.Lugar,
		&i.CveFactu,
		&i.CveMon,
		&i.TipCam,
		&i.SaldoFac2,
		&i.Staley,
		&i.CveSuc,
		&i.Mes,
		&i.Anio,
		&i.Usuario,
		&i.Trans,
		&i.Staley2,
		&i.PedInt,
		&i.ComCob,
		&i.Cierre,
		&i.UTipCam,
		&i.CveAge2,
		&i.ComCob2,
		&i.DinCom,
		&i.DinCom2,
		&i.FechSal,
		&i.FechEmb,
		&i.CveFlet,
		&i.TotFlet,
		&i.TotEnv,
		&i.PrecFlet,
		&i.PrvReal,
		&i.TimpCar,
		&i.Numpol,
		&i.Numpolcan,
		&i.ImpCarac,
		&i.Pesotot,
		&i.RetivaFac,
		&i.Deposito,
		&i.SucDepo,
		&i.Status2,
		&i.Cvedirent,
		&i.Reimpre,
		&i.Descue2,
		&i.Descue3,
		&i.Descue4,
		&i.NoPeda,
		&i.CveSuca,
		&i.CveFactua,
		&i.CveEntre,
		&i.Ieps,
	)
	return i, err
}
