// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cliente struct {
	ID                    int32            `json:"id"`
	NombreComercial       string           `json:"nombre_comercial"`
	RazonSocial           string           `json:"razon_social"`
	Rfc                   string           `json:"rfc"`
	Estado                string           `json:"estado"`
	MontoMinimoCompra     pgtype.Numeric   `json:"monto_minimo_compra"`
	LineaCreditoTotal     pgtype.Numeric   `json:"linea_credito_total"`
	LineaCreditoUtilizada pgtype.Numeric   `json:"linea_credito_utilizada"`
	DiasCredito           int32            `json:"dias_credito"`
	PermitirPagoCredito   bool             `json:"permitir_pago_credito"`
	MetodoPagoPreferente  string           `json:"metodo_pago_preferente"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	DeletedAt             pgtype.Timestamp `json:"deleted_at"`
	CreatedBy             pgtype.Int4      `json:"created_by"`
	UpdatedBy             pgtype.Int4      `json:"updated_by"`
	DeletedBy             pgtype.Int4      `json:"deleted_by"`
}

type ClientesIntegracion struct {
	ID        int32          `json:"id"`
	CveCte    pgtype.Int4    `json:"cve_cte"`
	NomCte    pgtype.Text    `json:"nom_cte"`
	DirCte    pgtype.Text    `json:"dir_cte"`
	ColCte    pgtype.Text    `json:"col_cte"`
	CdCte     pgtype.Text    `json:"cd_cte"`
	EdoCte    pgtype.Text    `json:"edo_cte"`
	RfcCte    pgtype.Text    `json:"rfc_cte"`
	CpCte     pgtype.Text    `json:"cp_cte"`
	Contacto  pgtype.Text    `json:"contacto"`
	Tel1Cte   pgtype.Text    `json:"tel1_cte"`
	LimCre    pgtype.Numeric `json:"lim_cre"`
	DiaCre    pgtype.Int4    `json:"dia_cre"`
	CveAge    pgtype.Int4    `json:"cve_age"`
	LadaCte   pgtype.Text    `json:"lada_cte"`
	CveZon    pgtype.Int4    `json:"cve_zon"`
	CveSub    pgtype.Int4    `json:"cve_sub"`
	CveCan    pgtype.Int4    `json:"cve_can"`
	Cuentacon pgtype.Text    `json:"cuentacon"`
	Contado   pgtype.Int4    `json:"contado"`
	PaisCte   pgtype.Text    `json:"pais_cte"`
	EmailCte  pgtype.Text    `json:"email_cte"`
}

type Pedido struct {
	ID          int32            `json:"id"`
	Folio       string           `json:"folio"`
	ClienteID   pgtype.Int4      `json:"cliente_id"`
	UsuarioID   pgtype.Int4      `json:"usuario_id"`
	Estado      string           `json:"estado"`
	MetodoPago  string           `json:"metodo_pago"`
	Subtotal    pgtype.Numeric   `json:"subtotal"`
	Iva         pgtype.Numeric   `json:"iva"`
	TotalOrden  pgtype.Numeric   `json:"total_orden"`
	EsBackorder pgtype.Bool      `json:"es_backorder"`
	FechaPedido pgtype.Timestamp `json:"fecha_pedido"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
	CreatedBy   pgtype.Int4      `json:"created_by"`
	UpdatedBy   pgtype.Int4      `json:"updated_by"`
	DeletedBy   pgtype.Int4      `json:"deleted_by"`
}

type PedidoDetalle struct {
	ID                     int32            `json:"id"`
	PedidoID               pgtype.Int4      `json:"pedido_id"`
	VarianteID             pgtype.Int4      `json:"variante_id"`
	Cantidad               int32            `json:"cantidad"`
	PrecioUnitarioAplicado pgtype.Numeric   `json:"precio_unitario_aplicado"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	DeletedAt              pgtype.Timestamp `json:"deleted_at"`
	CreatedBy              pgtype.Int4      `json:"created_by"`
	UpdatedBy              pgtype.Int4      `json:"updated_by"`
	DeletedBy              pgtype.Int4      `json:"deleted_by"`
}

type ProductosPadre struct {
	ID               int32            `json:"id"`
	NombreTecnico    string           `json:"nombre_tecnico"`
	Descripcion      pgtype.Text      `json:"descripcion"`
	Categoria        string           `json:"categoria"`
	Marca            pgtype.Text      `json:"marca"`
	DocumentacionUrl pgtype.Text      `json:"documentacion_url"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
	CreatedBy        pgtype.Int4      `json:"created_by"`
	UpdatedBy        pgtype.Int4      `json:"updated_by"`
	DeletedBy        pgtype.Int4      `json:"deleted_by"`
}

type ProductosVariante struct {
	ID           int32            `json:"id"`
	PadreID      pgtype.Int4      `json:"padre_id"`
	Sku          string           `json:"sku"`
	Medida       pgtype.Text      `json:"medida"`
	PrecioLista  pgtype.Numeric   `json:"precio_lista"`
	StockActual  int32            `json:"stock_actual"`
	UnidadMedida string           `json:"unidad_medida"`
	LeadTimeDias pgtype.Int4      `json:"lead_time_dias"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
	CreatedBy    pgtype.Int4      `json:"created_by"`
	UpdatedBy    pgtype.Int4      `json:"updated_by"`
	DeletedBy    pgtype.Int4      `json:"deleted_by"`
}

type SolicitudRegistroNuevoCliente struct {
	ID                int32            `json:"id"`
	NombreComercial   string           `json:"nombre_comercial"`
	RazonSocial       string           `json:"razon_social"`
	Rfc               string           `json:"rfc"`
	TipoContribuyente string           `json:"tipo_contribuyente"`
	SolicitudEstado   string           `json:"solicitud_estado"`
	Observacion       pgtype.Text      `json:"observacion"`
	Comentarios       pgtype.Text      `json:"comentarios"`
	ConstanciaSatUrl  pgtype.Text      `json:"constancia_sat_url"`
	Calle             string           `json:"calle"`
	Numero            string           `json:"numero"`
	Colonia           string           `json:"colonia"`
	Ciudad            string           `json:"ciudad"`
	Estado            string           `json:"estado"`
	Cp                string           `json:"cp"`
	NombreContacto    string           `json:"nombre_contacto"`
	PuestoContacto    string           `json:"puesto_contacto"`
	CorreoContacto    string           `json:"correo_contacto"`
	TelefonoContacto  string           `json:"telefono_contacto"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	DeletedAt         pgtype.Timestamp `json:"deleted_at"`
	CreatedBy         pgtype.Int4      `json:"created_by"`
	UpdatedBy         pgtype.Int4      `json:"updated_by"`
	DeletedBy         pgtype.Int4      `json:"deleted_by"`
}

type Usuario struct {
	ID           int32            `json:"id"`
	ClienteID    pgtype.Int4      `json:"cliente_id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Rol          string           `json:"rol"`
	IsActive     pgtype.Bool      `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
	CreatedBy    pgtype.Int4      `json:"created_by"`
	UpdatedBy    pgtype.Int4      `json:"updated_by"`
	DeletedBy    pgtype.Int4      `json:"deleted_by"`
}
