// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cliente struct {
	ID                    int32            `json:"id"`
	NombreComercial       string           `json:"nombre_comercial"`
	RazonSocial           string           `json:"razon_social"`
	Rfc                   string           `json:"rfc"`
	Estado                string           `json:"estado"`
	MontoMinimoCompra     pgtype.Numeric   `json:"monto_minimo_compra"`
	LineaCreditoTotal     pgtype.Numeric   `json:"linea_credito_total"`
	LineaCreditoUtilizada pgtype.Numeric   `json:"linea_credito_utilizada"`
	DiasCredito           int32            `json:"dias_credito"`
	PermitirPagoCredito   bool             `json:"permitir_pago_credito"`
	MetodoPagoPreferente  string           `json:"metodo_pago_preferente"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	DeletedAt             pgtype.Timestamp `json:"deleted_at"`
	CreatedBy             pgtype.Int4      `json:"created_by"`
	UpdatedBy             pgtype.Int4      `json:"updated_by"`
	DeletedBy             pgtype.Int4      `json:"deleted_by"`
}

type ClientesIntegracion struct {
	ID        int32          `json:"id"`
	CveCte    pgtype.Int4    `json:"cve_cte"`
	NomCte    pgtype.Text    `json:"nom_cte"`
	DirCte    pgtype.Text    `json:"dir_cte"`
	ColCte    pgtype.Text    `json:"col_cte"`
	CdCte     pgtype.Text    `json:"cd_cte"`
	EdoCte    pgtype.Text    `json:"edo_cte"`
	RfcCte    pgtype.Text    `json:"rfc_cte"`
	CpCte     pgtype.Text    `json:"cp_cte"`
	Contacto  pgtype.Text    `json:"contacto"`
	Tel1Cte   pgtype.Text    `json:"tel1_cte"`
	LimCre    pgtype.Numeric `json:"lim_cre"`
	DiaCre    pgtype.Int4    `json:"dia_cre"`
	CveAge    pgtype.Int4    `json:"cve_age"`
	LadaCte   pgtype.Text    `json:"lada_cte"`
	CveZon    pgtype.Int4    `json:"cve_zon"`
	CveSub    pgtype.Int4    `json:"cve_sub"`
	CveCan    pgtype.Int4    `json:"cve_can"`
	Cuentacon pgtype.Text    `json:"cuentacon"`
	Contado   pgtype.Int4    `json:"contado"`
	PaisCte   pgtype.Text    `json:"pais_cte"`
	EmailCte  pgtype.Text    `json:"email_cte"`
}

type CreditosIntegracion struct {
	ID        int32            `json:"id"`
	CveDda    pgtype.Text      `json:"cve_dda"`
	NoNota    pgtype.Text      `json:"no_nota"`
	TipNot    pgtype.Text      `json:"tip_not"`
	Fecha     pgtype.Timestamp `json:"fecha"`
	NoFac     pgtype.Text      `json:"no_fac"`
	NoCliente pgtype.Int4      `json:"no_cliente"`
	NoAgente  pgtype.Int4      `json:"no_agente"`
	NoEstado  pgtype.Text      `json:"no_estado"`
	TotImp    pgtype.Numeric   `json:"tot_imp"`
	Subtotal  pgtype.Numeric   `json:"subtotal"`
	DescNot   pgtype.Numeric   `json:"desc_not"`
	TotNota   pgtype.Numeric   `json:"tot_nota"`
	Num       pgtype.Int4      `json:"num"`
	Saldo     pgtype.Numeric   `json:"saldo"`
	TotDes    pgtype.Numeric   `json:"tot_des"`
	Lugar     pgtype.Text      `json:"lugar"`
	CveFactu  pgtype.Text      `json:"cve_factu"`
	CveMon    pgtype.Int4      `json:"cve_mon"`
	TipCam    pgtype.Numeric   `json:"tip_cam"`
	CveSuc    pgtype.Text      `json:"cve_suc"`
	Mes       pgtype.Text      `json:"mes"`
	Aqo       pgtype.Text      `json:"aqo"`
	Usuario   pgtype.Int4      `json:"usuario"`
	Trans     pgtype.Int4      `json:"trans"`
}

type ExistenciasIntegracion struct {
	ID         int32            `json:"id"`
	CseProd    pgtype.Text      `json:"cse_prod"`
	CveProd    string           `json:"cve_prod"`
	Lugar      string           `json:"lugar"`
	Existencia pgtype.Numeric   `json:"existencia"`
	MedProd    pgtype.Numeric   `json:"med_prod"`
	FechUmod   pgtype.Timestamp `json:"fech_umod"`
	InvIni     pgtype.Int8      `json:"inv_ini"`
	Lote       pgtype.Text      `json:"lote"`
	FechLote   pgtype.Timestamp `json:"fech_lote"`
	RefLote    pgtype.Text      `json:"ref_lote"`
	CostoProm  pgtype.Numeric   `json:"costo_prom"`
	NewMed     pgtype.Text      `json:"new_med"`
	Costuepeps pgtype.Numeric   `json:"costuepeps"`
	Costoprom2 pgtype.Numeric   `json:"costoprom2"`
}

type FacturasIntegracion struct {
	ID        int32            `json:"id"`
	NoFac     string           `json:"no_fac"`
	NoPed     pgtype.Text      `json:"no_ped"`
	CveCte    pgtype.Int4      `json:"cve_cte"`
	CveAge    pgtype.Int4      `json:"cve_age"`
	FaltaFac  pgtype.Timestamp `json:"falta_fac"`
	StatusFac pgtype.Text      `json:"status_fac"`
	SubtFac   pgtype.Numeric   `json:"subt_fac"`
	Descuento pgtype.Numeric   `json:"descuento"`
	Descue    pgtype.Numeric   `json:"descue"`
	TotalFac  pgtype.Numeric   `json:"total_fac"`
	SaldoFac  pgtype.Numeric   `json:"saldo_fac"`
	FPago     pgtype.Timestamp `json:"f_pago"`
	Contrarec pgtype.Text      `json:"contrarec"`
	Lugar     pgtype.Text      `json:"lugar"`
	CveFactu  pgtype.Text      `json:"cve_factu"`
	CveMon    pgtype.Text      `json:"cve_mon"`
	TipCam    pgtype.Numeric   `json:"tip_cam"`
	SaldoFac2 pgtype.Numeric   `json:"saldo_fac2"`
	Staley    pgtype.Text      `json:"staley"`
	CveSuc    pgtype.Int4      `json:"cve_suc"`
	Mes       pgtype.Int4      `json:"mes"`
	Anio      pgtype.Int4      `json:"anio"`
	Usuario   pgtype.Text      `json:"usuario"`
	Trans     pgtype.Text      `json:"trans"`
	Staley2   pgtype.Text      `json:"staley2"`
	PedInt    pgtype.Text      `json:"ped_int"`
	ComCob    pgtype.Numeric   `json:"com_cob"`
	Cierre    pgtype.Timestamp `json:"cierre"`
	UTipCam   pgtype.Numeric   `json:"u_tip_cam"`
	CveAge2   pgtype.Int4      `json:"cve_age2"`
	ComCob2   pgtype.Numeric   `json:"com_cob2"`
	DinCom    pgtype.Numeric   `json:"din_com"`
	DinCom2   pgtype.Numeric   `json:"din_com2"`
	FechSal   pgtype.Timestamp `json:"fech_sal"`
	FechEmb   pgtype.Timestamp `json:"fech_emb"`
	CveFlet   pgtype.Text      `json:"cve_flet"`
	TotFlet   pgtype.Numeric   `json:"tot_flet"`
	TotEnv    pgtype.Numeric   `json:"tot_env"`
	PrecFlet  pgtype.Numeric   `json:"prec_flet"`
	PrvReal   pgtype.Text      `json:"prv_real"`
	TimpCar   pgtype.Numeric   `json:"timp_car"`
	Numpol    pgtype.Text      `json:"numpol"`
	Numpolcan pgtype.Text      `json:"numpolcan"`
	ImpCarac  pgtype.Numeric   `json:"imp_carac"`
	Pesotot   pgtype.Numeric   `json:"pesotot"`
	RetivaFac pgtype.Numeric   `json:"retiva_fac"`
	Deposito  pgtype.Numeric   `json:"deposito"`
	SucDepo   pgtype.Text      `json:"suc_depo"`
	Status2   pgtype.Text      `json:"status_2"`
	Cvedirent pgtype.Text      `json:"cvedirent"`
	Reimpre   pgtype.Int4      `json:"reimpre"`
	Descue2   pgtype.Numeric   `json:"descue2"`
	Descue3   pgtype.Numeric   `json:"descue3"`
	Descue4   pgtype.Numeric   `json:"descue4"`
	NoPeda    pgtype.Text      `json:"no_peda"`
	CveSuca   pgtype.Text      `json:"cve_suca"`
	CveFactua pgtype.Text      `json:"cve_factua"`
	CveEntre  pgtype.Text      `json:"cve_entre"`
	Ieps      pgtype.Numeric   `json:"ieps"`
}

type Pedido struct {
	ID          int32            `json:"id"`
	Folio       string           `json:"folio"`
	ClienteID   pgtype.Int4      `json:"cliente_id"`
	UsuarioID   pgtype.Int4      `json:"usuario_id"`
	Estado      string           `json:"estado"`
	MetodoPago  string           `json:"metodo_pago"`
	Subtotal    pgtype.Numeric   `json:"subtotal"`
	Iva         pgtype.Numeric   `json:"iva"`
	TotalOrden  pgtype.Numeric   `json:"total_orden"`
	EsBackorder pgtype.Bool      `json:"es_backorder"`
	Guia        pgtype.Text      `json:"guia"`
	NotasAdmin  pgtype.Text      `json:"notas_admin"`
	FechaPedido pgtype.Timestamp `json:"fecha_pedido"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
	CreatedBy   pgtype.Int4      `json:"created_by"`
	UpdatedBy   pgtype.Int4      `json:"updated_by"`
	DeletedBy   pgtype.Int4      `json:"deleted_by"`
}

type PedidoDetalle struct {
	ID                     int32            `json:"id"`
	PedidoID               pgtype.Int4      `json:"pedido_id"`
	VarianteID             pgtype.Int4      `json:"variante_id"`
	Cantidad               int32            `json:"cantidad"`
	PrecioUnitarioAplicado pgtype.Numeric   `json:"precio_unitario_aplicado"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	DeletedAt              pgtype.Timestamp `json:"deleted_at"`
	CreatedBy              pgtype.Int4      `json:"created_by"`
	UpdatedBy              pgtype.Int4      `json:"updated_by"`
	DeletedBy              pgtype.Int4      `json:"deleted_by"`
}

type ProductosIntegracion struct {
	ID        int32            `json:"id"`
	CseProd   pgtype.Text      `json:"cse_prod"`
	CveProd   pgtype.Text      `json:"cve_prod"`
	NomProd   pgtype.Text      `json:"nom_prod"`
	DescProd  pgtype.Text      `json:"desc_prod"`
	UniMed    pgtype.Text      `json:"uni_med"`
	UniMedP   pgtype.Text      `json:"uni_med_p"`
	CostoProd pgtype.Numeric   `json:"costo_prod"`
	FActCto   pgtype.Timestamp `json:"f_act_cto"`
	FActPre   pgtype.Timestamp `json:"f_act_pre"`
	CtoEnt    pgtype.Numeric   `json:"cto_ent"`
	FecEnt    pgtype.Timestamp `json:"fec_ent"`
	FecAnt    pgtype.Timestamp `json:"fec_ant"`
}

type ProductosPadre struct {
	ID                   int32            `json:"id"`
	CveProdIntegracion   pgtype.Text      `json:"cve_prod_integracion"`
	Descripcion          pgtype.Text      `json:"descripcion"`
	FotoUrl              pgtype.Text      `json:"foto_url"`
	FichaTecnica         pgtype.Text      `json:"ficha_tecnica"`
	DescripcionExtendida pgtype.Text      `json:"descripcion_extendida"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	DeletedAt            pgtype.Timestamp `json:"deleted_at"`
	CreatedBy            pgtype.Int4      `json:"created_by"`
	UpdatedBy            pgtype.Int4      `json:"updated_by"`
	DeletedBy            pgtype.Int4      `json:"deleted_by"`
}

type ProductosVariante struct {
	ID                 int32            `json:"id"`
	PadreID            pgtype.Int4      `json:"padre_id"`
	Sku                string           `json:"sku"`
	Medida             pgtype.Text      `json:"medida"`
	PrecioDistribuidor pgtype.Numeric   `json:"precio_distribuidor"`
	PrecioLista        pgtype.Numeric   `json:"precio_lista"`
	PrecioPublico      pgtype.Numeric   `json:"precio_publico"`
	StockActual        int32            `json:"stock_actual"`
	UnidadMedida       string           `json:"unidad_medida"`
	LeadTimeDias       pgtype.Int4      `json:"lead_time_dias"`
	Especificaciones   pgtype.Text      `json:"especificaciones"`
	Multiplos          pgtype.Int4      `json:"multiplos"`
	Categoria          pgtype.Text      `json:"categoria"`
	Subgrupo           pgtype.Text      `json:"subgrupo"`
	Modelo             pgtype.Text      `json:"modelo"`
	Tipo               pgtype.Text      `json:"tipo"`
	Marca              pgtype.Text      `json:"marca"`
	PermitirBackorder  pgtype.Bool      `json:"permitir_backorder"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	DeletedAt          pgtype.Timestamp `json:"deleted_at"`
	CreatedBy          pgtype.Int4      `json:"created_by"`
	UpdatedBy          pgtype.Int4      `json:"updated_by"`
	DeletedBy          pgtype.Int4      `json:"deleted_by"`
}

type SolicitudRegistroNuevoCliente struct {
	ID                int32            `json:"id"`
	NombreComercial   string           `json:"nombre_comercial"`
	RazonSocial       string           `json:"razon_social"`
	Rfc               string           `json:"rfc"`
	TipoContribuyente string           `json:"tipo_contribuyente"`
	SolicitudEstado   string           `json:"solicitud_estado"`
	Observacion       pgtype.Text      `json:"observacion"`
	Comentarios       pgtype.Text      `json:"comentarios"`
	ConstanciaSatUrl  pgtype.Text      `json:"constancia_sat_url"`
	Calle             string           `json:"calle"`
	Numero            string           `json:"numero"`
	Colonia           string           `json:"colonia"`
	Ciudad            string           `json:"ciudad"`
	Estado            string           `json:"estado"`
	Cp                string           `json:"cp"`
	NombreContacto    string           `json:"nombre_contacto"`
	PuestoContacto    string           `json:"puesto_contacto"`
	CorreoContacto    string           `json:"correo_contacto"`
	TelefonoContacto  string           `json:"telefono_contacto"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	DeletedAt         pgtype.Timestamp `json:"deleted_at"`
	CreatedBy         pgtype.Int4      `json:"created_by"`
	UpdatedBy         pgtype.Int4      `json:"updated_by"`
	DeletedBy         pgtype.Int4      `json:"deleted_by"`
}

type Usuario struct {
	ID           int32            `json:"id"`
	ClienteID    pgtype.Int4      `json:"cliente_id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Rol          string           `json:"rol"`
	IsActive     pgtype.Bool      `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
	CreatedBy    pgtype.Int4      `json:"created_by"`
	UpdatedBy    pgtype.Int4      `json:"updated_by"`
	DeletedBy    pgtype.Int4      `json:"deleted_by"`
}
