// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pago_facturas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const crearHistorialPagoFactura = `-- name: CrearHistorialPagoFactura :one
INSERT INTO historial_facturas_pagadas (
    factura_id,
    cliente_id,
    no_factura,
    monto_pagado,
    metodo_pago,
    tarjeta_terminacion,
    respuesta_simulada,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, factura_id, cliente_id, no_factura, monto_pagado, metodo_pago, tarjeta_terminacion, respuesta_simulada, created_at, created_by
`

type CrearHistorialPagoFacturaParams struct {
	FacturaID          int32          `json:"factura_id"`
	ClienteID          int32          `json:"cliente_id"`
	NoFactura          string         `json:"no_factura"`
	MontoPagado        pgtype.Numeric `json:"monto_pagado"`
	MetodoPago         string         `json:"metodo_pago"`
	TarjetaTerminacion string         `json:"tarjeta_terminacion"`
	RespuestaSimulada  string         `json:"respuesta_simulada"`
	CreatedBy          pgtype.Int4    `json:"created_by"`
}

func (q *Queries) CrearHistorialPagoFactura(ctx context.Context, arg CrearHistorialPagoFacturaParams) (HistorialFacturasPagada, error) {
	row := q.db.QueryRow(ctx, crearHistorialPagoFactura,
		arg.FacturaID,
		arg.ClienteID,
		arg.NoFactura,
		arg.MontoPagado,
		arg.MetodoPago,
		arg.TarjetaTerminacion,
		arg.RespuestaSimulada,
		arg.CreatedBy,
	)
	var i HistorialFacturasPagada
	err := row.Scan(
		&i.ID,
		&i.FacturaID,
		&i.ClienteID,
		&i.NoFactura,
		&i.MontoPagado,
		&i.MetodoPago,
		&i.TarjetaTerminacion,
		&i.RespuestaSimulada,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const crearPagoFactura = `-- name: CrearPagoFactura :one
INSERT INTO pagos_facturas (
    cliente_id,
    metodo_pago,
    tarjeta_terminacion,
    monto_total,
    respuesta_simulada,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, cliente_id, metodo_pago, tarjeta_terminacion, monto_total, respuesta_simulada, created_at, created_by
`

type CrearPagoFacturaParams struct {
	ClienteID          int32          `json:"cliente_id"`
	MetodoPago         string         `json:"metodo_pago"`
	TarjetaTerminacion string         `json:"tarjeta_terminacion"`
	MontoTotal         pgtype.Numeric `json:"monto_total"`
	RespuestaSimulada  string         `json:"respuesta_simulada"`
	CreatedBy          pgtype.Int4    `json:"created_by"`
}

func (q *Queries) CrearPagoFactura(ctx context.Context, arg CrearPagoFacturaParams) (PagosFactura, error) {
	row := q.db.QueryRow(ctx, crearPagoFactura,
		arg.ClienteID,
		arg.MetodoPago,
		arg.TarjetaTerminacion,
		arg.MontoTotal,
		arg.RespuestaSimulada,
		arg.CreatedBy,
	)
	var i PagosFactura
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.MetodoPago,
		&i.TarjetaTerminacion,
		&i.MontoTotal,
		&i.RespuestaSimulada,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const crearPagoFacturaDetalle = `-- name: CrearPagoFacturaDetalle :exec
INSERT INTO pagos_facturas_detalles (
    pago_id,
    factura_id,
    no_factura,
    monto_pagado
) VALUES (
    $1, $2, $3, $4
)
`

type CrearPagoFacturaDetalleParams struct {
	PagoID      int32          `json:"pago_id"`
	FacturaID   int32          `json:"factura_id"`
	NoFactura   string         `json:"no_factura"`
	MontoPagado pgtype.Numeric `json:"monto_pagado"`
}

func (q *Queries) CrearPagoFacturaDetalle(ctx context.Context, arg CrearPagoFacturaDetalleParams) error {
	_, err := q.db.Exec(ctx, crearPagoFacturaDetalle,
		arg.PagoID,
		arg.FacturaID,
		arg.NoFactura,
		arg.MontoPagado,
	)
	return err
}

const getCveCteByClienteId = `-- name: GetCveCteByClienteId :one
SELECT ci.cve_cte FROM clientes_integracion ci
JOIN clientes c ON c.rfc = ci.rfc_cte
WHERE c.id = $1 LIMIT 1
`

func (q *Queries) GetCveCteByClienteId(ctx context.Context, id int32) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getCveCteByClienteId, id)
	var cve_cte pgtype.Int4
	err := row.Scan(&cve_cte)
	return cve_cte, err
}

const getFacturaIntegracionPorId = `-- name: GetFacturaIntegracionPorId :one
SELECT id, no_fac, no_ped, cve_cte, cve_age, falta_fac, status_fac, subt_fac, descuento, descue, total_fac, saldo_fac, f_pago, contrarec, lugar, cve_factu, cve_mon, tip_cam, saldo_fac2, staley, cve_suc, mes, anio, usuario, trans, staley2, ped_int, com_cob, cierre, u_tip_cam, cve_age2, com_cob2, din_com, din_com2, fech_sal, fech_emb, cve_flet, tot_flet, tot_env, prec_flet, prv_real, timp_car, numpol, numpolcan, imp_carac, pesotot, retiva_fac, deposito, suc_depo, status_2, cvedirent, reimpre, descue2, descue3, descue4, no_peda, cve_suca, cve_factua, cve_entre, ieps FROM facturas_integracion
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFacturaIntegracionPorId(ctx context.Context, id int32) (FacturasIntegracion, error) {
	row := q.db.QueryRow(ctx, getFacturaIntegracionPorId, id)
	var i FacturasIntegracion
	err := row.Scan(
		&i.ID,
		&i.NoFac,
		&i.NoPed,
		&i.CveCte,
		&i.CveAge,
		&i.FaltaFac,
		&i.StatusFac,
		&i.SubtFac,
		&i.Descuento,
		&i.Descue,
		&i.TotalFac,
		&i.SaldoFac,
		&i.FPago,
		&i.Contrarec,
		&i.Lugar,
		&i.CveFactu,
		&i.CveMon,
		&i.TipCam,
		&i.SaldoFac2,
		&i.Staley,
		&i.CveSuc,
		&i.Mes,
		&i.Anio,
		&i.Usuario,
		&i.Trans,
		&i.Staley2,
		&i.PedInt,
		&i.ComCob,
		&i.Cierre,
		&i.UTipCam,
		&i.CveAge2,
		&i.ComCob2,
		&i.DinCom,
		&i.DinCom2,
		&i.FechSal,
		&i.FechEmb,
		&i.CveFlet,
		&i.TotFlet,
		&i.TotEnv,
		&i.PrecFlet,
		&i.PrvReal,
		&i.TimpCar,
		&i.Numpol,
		&i.Numpolcan,
		&i.ImpCarac,
		&i.Pesotot,
		&i.RetivaFac,
		&i.Deposito,
		&i.SucDepo,
		&i.Status2,
		&i.Cvedirent,
		&i.Reimpre,
		&i.Descue2,
		&i.Descue3,
		&i.Descue4,
		&i.NoPeda,
		&i.CveSuca,
		&i.CveFactua,
		&i.CveEntre,
		&i.Ieps,
	)
	return i, err
}

const getHistorialFacturaPagada = `-- name: GetHistorialFacturaPagada :one
SELECT id, factura_id, cliente_id, no_factura, monto_pagado, metodo_pago, tarjeta_terminacion, respuesta_simulada, created_at, created_by FROM historial_facturas_pagadas
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHistorialFacturaPagada(ctx context.Context, id int32) (HistorialFacturasPagada, error) {
	row := q.db.QueryRow(ctx, getHistorialFacturaPagada, id)
	var i HistorialFacturasPagada
	err := row.Scan(
		&i.ID,
		&i.FacturaID,
		&i.ClienteID,
		&i.NoFactura,
		&i.MontoPagado,
		&i.MetodoPago,
		&i.TarjetaTerminacion,
		&i.RespuestaSimulada,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getPagoFactura = `-- name: GetPagoFactura :one
SELECT id, cliente_id, metodo_pago, tarjeta_terminacion, monto_total, respuesta_simulada, created_at, created_by FROM pagos_facturas
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPagoFactura(ctx context.Context, id int32) (PagosFactura, error) {
	row := q.db.QueryRow(ctx, getPagoFactura, id)
	var i PagosFactura
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.MetodoPago,
		&i.TarjetaTerminacion,
		&i.MontoTotal,
		&i.RespuestaSimulada,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getPagoFacturaDetalles = `-- name: GetPagoFacturaDetalles :many
SELECT pfd.id, pfd.pago_id, pfd.factura_id, pfd.no_factura, pfd.monto_pagado, fi.falta_fac, fi.total_fac AS total_factura
FROM pagos_facturas_detalles pfd
LEFT JOIN facturas_integracion fi ON fi.id = pfd.factura_id
WHERE pfd.pago_id = $1
ORDER BY pfd.id
`

type GetPagoFacturaDetallesRow struct {
	ID           int32            `json:"id"`
	PagoID       int32            `json:"pago_id"`
	FacturaID    int32            `json:"factura_id"`
	NoFactura    string           `json:"no_factura"`
	MontoPagado  pgtype.Numeric   `json:"monto_pagado"`
	FaltaFac     pgtype.Timestamp `json:"falta_fac"`
	TotalFactura pgtype.Numeric   `json:"total_factura"`
}

func (q *Queries) GetPagoFacturaDetalles(ctx context.Context, pagoID int32) ([]GetPagoFacturaDetallesRow, error) {
	rows, err := q.db.Query(ctx, getPagoFacturaDetalles, pagoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPagoFacturaDetallesRow
	for rows.Next() {
		var i GetPagoFacturaDetallesRow
		if err := rows.Scan(
			&i.ID,
			&i.PagoID,
			&i.FacturaID,
			&i.NoFactura,
			&i.MontoPagado,
			&i.FaltaFac,
			&i.TotalFactura,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacturasEmitidasPorCveCte = `-- name: ListFacturasEmitidasPorCveCte :many
SELECT id, no_fac, no_ped, cve_cte, cve_age, falta_fac, status_fac, subt_fac, descuento, descue, total_fac, saldo_fac, f_pago, contrarec, lugar, cve_factu, cve_mon, tip_cam, saldo_fac2, staley, cve_suc, mes, anio, usuario, trans, staley2, ped_int, com_cob, cierre, u_tip_cam, cve_age2, com_cob2, din_com, din_com2, fech_sal, fech_emb, cve_flet, tot_flet, tot_env, prec_flet, prv_real, timp_car, numpol, numpolcan, imp_carac, pesotot, retiva_fac, deposito, suc_depo, status_2, cvedirent, reimpre, descue2, descue3, descue4, no_peda, cve_suca, cve_factua, cve_entre, ieps FROM facturas_integracion
WHERE cve_cte = $1 AND status_fac = 'Emitida'
ORDER BY falta_fac DESC
`

func (q *Queries) ListFacturasEmitidasPorCveCte(ctx context.Context, cveCte pgtype.Int4) ([]FacturasIntegracion, error) {
	rows, err := q.db.Query(ctx, listFacturasEmitidasPorCveCte, cveCte)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacturasIntegracion
	for rows.Next() {
		var i FacturasIntegracion
		if err := rows.Scan(
			&i.ID,
			&i.NoFac,
			&i.NoPed,
			&i.CveCte,
			&i.CveAge,
			&i.FaltaFac,
			&i.StatusFac,
			&i.SubtFac,
			&i.Descuento,
			&i.Descue,
			&i.TotalFac,
			&i.SaldoFac,
			&i.FPago,
			&i.Contrarec,
			&i.Lugar,
			&i.CveFactu,
			&i.CveMon,
			&i.TipCam,
			&i.SaldoFac2,
			&i.Staley,
			&i.CveSuc,
			&i.Mes,
			&i.Anio,
			&i.Usuario,
			&i.Trans,
			&i.Staley2,
			&i.PedInt,
			&i.ComCob,
			&i.Cierre,
			&i.UTipCam,
			&i.CveAge2,
			&i.ComCob2,
			&i.DinCom,
			&i.DinCom2,
			&i.FechSal,
			&i.FechEmb,
			&i.CveFlet,
			&i.TotFlet,
			&i.TotEnv,
			&i.PrecFlet,
			&i.PrvReal,
			&i.TimpCar,
			&i.Numpol,
			&i.Numpolcan,
			&i.ImpCarac,
			&i.Pesotot,
			&i.RetivaFac,
			&i.Deposito,
			&i.SucDepo,
			&i.Status2,
			&i.Cvedirent,
			&i.Reimpre,
			&i.Descue2,
			&i.Descue3,
			&i.Descue4,
			&i.NoPeda,
			&i.CveSuca,
			&i.CveFactua,
			&i.CveEntre,
			&i.Ieps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacturasEmitidasPorCveCteRango = `-- name: ListFacturasEmitidasPorCveCteRango :many
SELECT id, no_fac, no_ped, cve_cte, cve_age, falta_fac, status_fac, subt_fac, descuento, descue, total_fac, saldo_fac, f_pago, contrarec, lugar, cve_factu, cve_mon, tip_cam, saldo_fac2, staley, cve_suc, mes, anio, usuario, trans, staley2, ped_int, com_cob, cierre, u_tip_cam, cve_age2, com_cob2, din_com, din_com2, fech_sal, fech_emb, cve_flet, tot_flet, tot_env, prec_flet, prv_real, timp_car, numpol, numpolcan, imp_carac, pesotot, retiva_fac, deposito, suc_depo, status_2, cvedirent, reimpre, descue2, descue3, descue4, no_peda, cve_suca, cve_factua, cve_entre, ieps FROM facturas_integracion
WHERE cve_cte = $1 AND status_fac = 'Emitida'
  AND (falta_fac IS NULL OR (falta_fac >= $2 AND falta_fac <= $3))
ORDER BY falta_fac DESC
`

type ListFacturasEmitidasPorCveCteRangoParams struct {
	CveCte     pgtype.Int4      `json:"cve_cte"`
	FaltaFac   pgtype.Timestamp `json:"falta_fac"`
	FaltaFac_2 pgtype.Timestamp `json:"falta_fac_2"`
}

func (q *Queries) ListFacturasEmitidasPorCveCteRango(ctx context.Context, arg ListFacturasEmitidasPorCveCteRangoParams) ([]FacturasIntegracion, error) {
	rows, err := q.db.Query(ctx, listFacturasEmitidasPorCveCteRango, arg.CveCte, arg.FaltaFac, arg.FaltaFac_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacturasIntegracion
	for rows.Next() {
		var i FacturasIntegracion
		if err := rows.Scan(
			&i.ID,
			&i.NoFac,
			&i.NoPed,
			&i.CveCte,
			&i.CveAge,
			&i.FaltaFac,
			&i.StatusFac,
			&i.SubtFac,
			&i.Descuento,
			&i.Descue,
			&i.TotalFac,
			&i.SaldoFac,
			&i.FPago,
			&i.Contrarec,
			&i.Lugar,
			&i.CveFactu,
			&i.CveMon,
			&i.TipCam,
			&i.SaldoFac2,
			&i.Staley,
			&i.CveSuc,
			&i.Mes,
			&i.Anio,
			&i.Usuario,
			&i.Trans,
			&i.Staley2,
			&i.PedInt,
			&i.ComCob,
			&i.Cierre,
			&i.UTipCam,
			&i.CveAge2,
			&i.ComCob2,
			&i.DinCom,
			&i.DinCom2,
			&i.FechSal,
			&i.FechEmb,
			&i.CveFlet,
			&i.TotFlet,
			&i.TotEnv,
			&i.PrecFlet,
			&i.PrvReal,
			&i.TimpCar,
			&i.Numpol,
			&i.Numpolcan,
			&i.ImpCarac,
			&i.Pesotot,
			&i.RetivaFac,
			&i.Deposito,
			&i.SucDepo,
			&i.Status2,
			&i.Cvedirent,
			&i.Reimpre,
			&i.Descue2,
			&i.Descue3,
			&i.Descue4,
			&i.NoPeda,
			&i.CveSuca,
			&i.CveFactua,
			&i.CveEntre,
			&i.Ieps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistorialFacturasPagadas = `-- name: ListHistorialFacturasPagadas :many
SELECT id, factura_id, cliente_id, no_factura, monto_pagado, metodo_pago, tarjeta_terminacion, respuesta_simulada, created_at, created_by FROM historial_facturas_pagadas
ORDER BY created_at DESC
`

func (q *Queries) ListHistorialFacturasPagadas(ctx context.Context) ([]HistorialFacturasPagada, error) {
	rows, err := q.db.Query(ctx, listHistorialFacturasPagadas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistorialFacturasPagada
	for rows.Next() {
		var i HistorialFacturasPagada
		if err := rows.Scan(
			&i.ID,
			&i.FacturaID,
			&i.ClienteID,
			&i.NoFactura,
			&i.MontoPagado,
			&i.MetodoPago,
			&i.TarjetaTerminacion,
			&i.RespuestaSimulada,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistorialFacturasPagadasRango = `-- name: ListHistorialFacturasPagadasRango :many
SELECT id, factura_id, cliente_id, no_factura, monto_pagado, metodo_pago, tarjeta_terminacion, respuesta_simulada, created_at, created_by FROM historial_facturas_pagadas
WHERE created_at >= $1
  AND created_at <= $2
ORDER BY created_at DESC
`

type ListHistorialFacturasPagadasRangoParams struct {
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

func (q *Queries) ListHistorialFacturasPagadasRango(ctx context.Context, arg ListHistorialFacturasPagadasRangoParams) ([]HistorialFacturasPagada, error) {
	rows, err := q.db.Query(ctx, listHistorialFacturasPagadasRango, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistorialFacturasPagada
	for rows.Next() {
		var i HistorialFacturasPagada
		if err := rows.Scan(
			&i.ID,
			&i.FacturaID,
			&i.ClienteID,
			&i.NoFactura,
			&i.MontoPagado,
			&i.MetodoPago,
			&i.TarjetaTerminacion,
			&i.RespuestaSimulada,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagosFacturas = `-- name: ListPagosFacturas :many
SELECT id, cliente_id, metodo_pago, tarjeta_terminacion, monto_total, respuesta_simulada, created_at, created_by FROM pagos_facturas
ORDER BY created_at DESC
`

func (q *Queries) ListPagosFacturas(ctx context.Context) ([]PagosFactura, error) {
	rows, err := q.db.Query(ctx, listPagosFacturas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PagosFactura
	for rows.Next() {
		var i PagosFactura
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.MetodoPago,
			&i.TarjetaTerminacion,
			&i.MontoTotal,
			&i.RespuestaSimulada,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagosFacturasRango = `-- name: ListPagosFacturasRango :many
SELECT id, cliente_id, metodo_pago, tarjeta_terminacion, monto_total, respuesta_simulada, created_at, created_by FROM pagos_facturas
WHERE created_at >= $1
  AND created_at <= $2
ORDER BY created_at DESC
`

type ListPagosFacturasRangoParams struct {
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

func (q *Queries) ListPagosFacturasRango(ctx context.Context, arg ListPagosFacturasRangoParams) ([]PagosFactura, error) {
	rows, err := q.db.Query(ctx, listPagosFacturasRango, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PagosFactura
	for rows.Next() {
		var i PagosFactura
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.MetodoPago,
			&i.TarjetaTerminacion,
			&i.MontoTotal,
			&i.RespuestaSimulada,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
