// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pagos_tarjeta.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const crearTransaccionBanregio = `-- name: CrearTransaccionBanregio :one
INSERT INTO transacciones_banregio (
    bnrg_monto_trans,
    bnrg_id_afiliacion,
    bnrg_fecha_local,
    bnrg_codigo_aut,
    bnrg_folio,
    bnrg_texto,
    bnrg_referencia,
    bnrg_id_mediop,
    bnrg_codigo_proc,
    bnrg_hora_local,
    bnrg_codigo_emisor,
    pedido_id,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, bnrg_monto_trans, bnrg_id_afiliacion, bnrg_fecha_local, bnrg_codigo_aut, bnrg_folio, bnrg_texto, bnrg_referencia, bnrg_id_mediop, bnrg_codigo_proc, bnrg_hora_local, bnrg_codigo_emisor, pedido_id, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CrearTransaccionBanregioParams struct {
	BnrgMontoTrans   pgtype.Numeric `json:"bnrg_monto_trans"`
	BnrgIDAfiliacion pgtype.Text    `json:"bnrg_id_afiliacion"`
	BnrgFechaLocal   pgtype.Date    `json:"bnrg_fecha_local"`
	BnrgCodigoAut    pgtype.Text    `json:"bnrg_codigo_aut"`
	BnrgFolio        pgtype.Text    `json:"bnrg_folio"`
	BnrgTexto        pgtype.Text    `json:"bnrg_texto"`
	BnrgReferencia   pgtype.Text    `json:"bnrg_referencia"`
	BnrgIDMediop     pgtype.Text    `json:"bnrg_id_mediop"`
	BnrgCodigoProc   pgtype.Text    `json:"bnrg_codigo_proc"`
	BnrgHoraLocal    pgtype.Time    `json:"bnrg_hora_local"`
	BnrgCodigoEmisor pgtype.Text    `json:"bnrg_codigo_emisor"`
	PedidoID         pgtype.Int4    `json:"pedido_id"`
	CreatedBy        pgtype.Int4    `json:"created_by"`
}

func (q *Queries) CrearTransaccionBanregio(ctx context.Context, arg CrearTransaccionBanregioParams) (TransaccionesBanregio, error) {
	row := q.db.QueryRow(ctx, crearTransaccionBanregio,
		arg.BnrgMontoTrans,
		arg.BnrgIDAfiliacion,
		arg.BnrgFechaLocal,
		arg.BnrgCodigoAut,
		arg.BnrgFolio,
		arg.BnrgTexto,
		arg.BnrgReferencia,
		arg.BnrgIDMediop,
		arg.BnrgCodigoProc,
		arg.BnrgHoraLocal,
		arg.BnrgCodigoEmisor,
		arg.PedidoID,
		arg.CreatedBy,
	)
	var i TransaccionesBanregio
	err := row.Scan(
		&i.ID,
		&i.BnrgMontoTrans,
		&i.BnrgIDAfiliacion,
		&i.BnrgFechaLocal,
		&i.BnrgCodigoAut,
		&i.BnrgFolio,
		&i.BnrgTexto,
		&i.BnrgReferencia,
		&i.BnrgIDMediop,
		&i.BnrgCodigoProc,
		&i.BnrgHoraLocal,
		&i.BnrgCodigoEmisor,
		&i.PedidoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getTransaccionBanregio = `-- name: GetTransaccionBanregio :one
SELECT id, bnrg_monto_trans, bnrg_id_afiliacion, bnrg_fecha_local, bnrg_codigo_aut, bnrg_folio, bnrg_texto, bnrg_referencia, bnrg_id_mediop, bnrg_codigo_proc, bnrg_hora_local, bnrg_codigo_emisor, pedido_id, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM transacciones_banregio
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetTransaccionBanregio(ctx context.Context, id int32) (TransaccionesBanregio, error) {
	row := q.db.QueryRow(ctx, getTransaccionBanregio, id)
	var i TransaccionesBanregio
	err := row.Scan(
		&i.ID,
		&i.BnrgMontoTrans,
		&i.BnrgIDAfiliacion,
		&i.BnrgFechaLocal,
		&i.BnrgCodigoAut,
		&i.BnrgFolio,
		&i.BnrgTexto,
		&i.BnrgReferencia,
		&i.BnrgIDMediop,
		&i.BnrgCodigoProc,
		&i.BnrgHoraLocal,
		&i.BnrgCodigoEmisor,
		&i.PedidoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const listarTransaccionesBanregio = `-- name: ListarTransaccionesBanregio :many
SELECT id, bnrg_monto_trans, bnrg_id_afiliacion, bnrg_fecha_local, bnrg_codigo_aut, bnrg_folio, bnrg_texto, bnrg_referencia, bnrg_id_mediop, bnrg_codigo_proc, bnrg_hora_local, bnrg_codigo_emisor, pedido_id, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM transacciones_banregio
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListarTransaccionesBanregio(ctx context.Context) ([]TransaccionesBanregio, error) {
	rows, err := q.db.Query(ctx, listarTransaccionesBanregio)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransaccionesBanregio
	for rows.Next() {
		var i TransaccionesBanregio
		if err := rows.Scan(
			&i.ID,
			&i.BnrgMontoTrans,
			&i.BnrgIDAfiliacion,
			&i.BnrgFechaLocal,
			&i.BnrgCodigoAut,
			&i.BnrgFolio,
			&i.BnrgTexto,
			&i.BnrgReferencia,
			&i.BnrgIDMediop,
			&i.BnrgCodigoProc,
			&i.BnrgHoraLocal,
			&i.BnrgCodigoEmisor,
			&i.PedidoID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarTransaccionesPorCliente = `-- name: ListarTransaccionesPorCliente :many
SELECT t.id, t.bnrg_monto_trans, t.bnrg_id_afiliacion, t.bnrg_fecha_local, t.bnrg_codigo_aut, t.bnrg_folio, t.bnrg_texto, t.bnrg_referencia, t.bnrg_id_mediop, t.bnrg_codigo_proc, t.bnrg_hora_local, t.bnrg_codigo_emisor, t.pedido_id, t.created_at, t.updated_at, t.deleted_at, t.created_by, t.updated_by, t.deleted_by, p.folio AS pedido_folio
FROM transacciones_banregio t
JOIN pedidos p ON t.pedido_id = p.id
WHERE p.cliente_id = $1 AND t.deleted_at IS NULL AND p.deleted_at IS NULL
ORDER BY t.created_at DESC
`

type ListarTransaccionesPorClienteRow struct {
	ID               int32            `json:"id"`
	BnrgMontoTrans   pgtype.Numeric   `json:"bnrg_monto_trans"`
	BnrgIDAfiliacion pgtype.Text      `json:"bnrg_id_afiliacion"`
	BnrgFechaLocal   pgtype.Date      `json:"bnrg_fecha_local"`
	BnrgCodigoAut    pgtype.Text      `json:"bnrg_codigo_aut"`
	BnrgFolio        pgtype.Text      `json:"bnrg_folio"`
	BnrgTexto        pgtype.Text      `json:"bnrg_texto"`
	BnrgReferencia   pgtype.Text      `json:"bnrg_referencia"`
	BnrgIDMediop     pgtype.Text      `json:"bnrg_id_mediop"`
	BnrgCodigoProc   pgtype.Text      `json:"bnrg_codigo_proc"`
	BnrgHoraLocal    pgtype.Time      `json:"bnrg_hora_local"`
	BnrgCodigoEmisor pgtype.Text      `json:"bnrg_codigo_emisor"`
	PedidoID         pgtype.Int4      `json:"pedido_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
	CreatedBy        pgtype.Int4      `json:"created_by"`
	UpdatedBy        pgtype.Int4      `json:"updated_by"`
	DeletedBy        pgtype.Int4      `json:"deleted_by"`
	PedidoFolio      string           `json:"pedido_folio"`
}

func (q *Queries) ListarTransaccionesPorCliente(ctx context.Context, clienteID pgtype.Int4) ([]ListarTransaccionesPorClienteRow, error) {
	rows, err := q.db.Query(ctx, listarTransaccionesPorCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarTransaccionesPorClienteRow
	for rows.Next() {
		var i ListarTransaccionesPorClienteRow
		if err := rows.Scan(
			&i.ID,
			&i.BnrgMontoTrans,
			&i.BnrgIDAfiliacion,
			&i.BnrgFechaLocal,
			&i.BnrgCodigoAut,
			&i.BnrgFolio,
			&i.BnrgTexto,
			&i.BnrgReferencia,
			&i.BnrgIDMediop,
			&i.BnrgCodigoProc,
			&i.BnrgHoraLocal,
			&i.BnrgCodigoEmisor,
			&i.PedidoID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.PedidoFolio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransaccionBanregioPorFolio = `-- name: GetTransaccionBanregioPorFolio :one
SELECT id, bnrg_monto_trans, bnrg_id_afiliacion, bnrg_fecha_local, bnrg_codigo_aut, bnrg_folio, bnrg_texto, bnrg_referencia, bnrg_id_mediop, bnrg_codigo_proc, bnrg_hora_local, bnrg_codigo_emisor, pedido_id, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM transacciones_banregio
WHERE bnrg_folio = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetTransaccionBanregioPorFolio(ctx context.Context, bnrgFolio pgtype.Text) (TransaccionesBanregio, error) {
	row := q.db.QueryRow(ctx, getTransaccionBanregioPorFolio, bnrgFolio)
	var i TransaccionesBanregio
	err := row.Scan(
		&i.ID,
		&i.BnrgMontoTrans,
		&i.BnrgIDAfiliacion,
		&i.BnrgFechaLocal,
		&i.BnrgCodigoAut,
		&i.BnrgFolio,
		&i.BnrgTexto,
		&i.BnrgReferencia,
		&i.BnrgIDMediop,
		&i.BnrgCodigoProc,
		&i.BnrgHoraLocal,
		&i.BnrgCodigoEmisor,
		&i.PedidoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteTransaccionBanregio = `-- name: SoftDeleteTransaccionBanregio :exec
UPDATE transacciones_banregio
SET
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteTransaccionBanregioParams struct {
	ID        int32       `json:"id"`
	DeletedBy pgtype.Int4 `json:"deleted_by"`
}

func (q *Queries) SoftDeleteTransaccionBanregio(ctx context.Context, arg SoftDeleteTransaccionBanregioParams) error {
	_, err := q.db.Exec(ctx, softDeleteTransaccionBanregio, arg.ID, arg.DeletedBy)
	return err
}
