// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pedidos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarEstadoPedido = `-- name: ActualizarEstadoPedido :exec
UPDATE pedidos
SET 
    estado = $2,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $3
WHERE id = $1
`

type ActualizarEstadoPedidoParams struct {
	ID        int32       `json:"id"`
	Estado    string      `json:"estado"`
	UpdatedBy pgtype.Int4 `json:"updated_by"`
}

// Controla el workflow: Pendiente -> Picking -> Tránsito -> Entregado (cite: 248)
func (q *Queries) ActualizarEstadoPedido(ctx context.Context, arg ActualizarEstadoPedidoParams) error {
	_, err := q.db.Exec(ctx, actualizarEstadoPedido, arg.ID, arg.Estado, arg.UpdatedBy)
	return err
}

const actualizarPartidaPedido = `-- name: ActualizarPartidaPedido :exec
UPDATE pedido_detalles
SET 
    cantidad = $2,
    precio_unitario_aplicado = $3,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $4
WHERE id = $1
`

type ActualizarPartidaPedidoParams struct {
	ID                     int32          `json:"id"`
	Cantidad               int32          `json:"cantidad"`
	PrecioUnitarioAplicado pgtype.Numeric `json:"precio_unitario_aplicado"`
	UpdatedBy              pgtype.Int4    `json:"updated_by"`
}

func (q *Queries) ActualizarPartidaPedido(ctx context.Context, arg ActualizarPartidaPedidoParams) error {
	_, err := q.db.Exec(ctx, actualizarPartidaPedido,
		arg.ID,
		arg.Cantidad,
		arg.PrecioUnitarioAplicado,
		arg.UpdatedBy,
	)
	return err
}

const crearPedido = `-- name: CrearPedido :one

INSERT INTO pedidos (
    folio, 
    cliente_id, 
    usuario_id, 
    estado, 
    metodo_pago, 
    subtotal, 
    iva, 
    total_orden, 
    es_backorder, 
    fecha_pedido,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, folio, cliente_id, usuario_id, estado, metodo_pago, subtotal, iva, total_orden, es_backorder, fecha_pedido, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CrearPedidoParams struct {
	Folio       string           `json:"folio"`
	ClienteID   pgtype.Int4      `json:"cliente_id"`
	UsuarioID   pgtype.Int4      `json:"usuario_id"`
	Estado      string           `json:"estado"`
	MetodoPago  string           `json:"metodo_pago"`
	Subtotal    pgtype.Numeric   `json:"subtotal"`
	Iva         pgtype.Numeric   `json:"iva"`
	TotalOrden  pgtype.Numeric   `json:"total_orden"`
	EsBackorder pgtype.Bool      `json:"es_backorder"`
	FechaPedido pgtype.Timestamp `json:"fecha_pedido"`
	CreatedBy   pgtype.Int4      `json:"created_by"`
}

// internal/sql/pedidos.sql
// Inicia el flujo de venta y reserva de crédito (cite: 234, 274)
func (q *Queries) CrearPedido(ctx context.Context, arg CrearPedidoParams) (Pedido, error) {
	row := q.db.QueryRow(ctx, crearPedido,
		arg.Folio,
		arg.ClienteID,
		arg.UsuarioID,
		arg.Estado,
		arg.MetodoPago,
		arg.Subtotal,
		arg.Iva,
		arg.TotalOrden,
		arg.EsBackorder,
		arg.FechaPedido,
		arg.CreatedBy,
	)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.UsuarioID,
		&i.Estado,
		&i.MetodoPago,
		&i.Subtotal,
		&i.Iva,
		&i.TotalOrden,
		&i.EsBackorder,
		&i.FechaPedido,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getPedido = `-- name: GetPedido :one
SELECT id, folio, cliente_id, usuario_id, estado, metodo_pago, subtotal, iva, total_orden, es_backorder, fecha_pedido, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM pedidos 
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

// Obtiene el encabezado con los datos de auditoría
func (q *Queries) GetPedido(ctx context.Context, id int32) (Pedido, error) {
	row := q.db.QueryRow(ctx, getPedido, id)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.UsuarioID,
		&i.Estado,
		&i.MetodoPago,
		&i.Subtotal,
		&i.Iva,
		&i.TotalOrden,
		&i.EsBackorder,
		&i.FechaPedido,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const listarPedidosPorCliente = `-- name: ListarPedidosPorCliente :many
SELECT id, folio, cliente_id, usuario_id, estado, metodo_pago, subtotal, iva, total_orden, es_backorder, fecha_pedido, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM pedidos 
WHERE cliente_id = $1 AND deleted_at IS NULL 
ORDER BY fecha_pedido DESC
`

// Para el historial y re-order del cliente (cite: 215, 217)
func (q *Queries) ListarPedidosPorCliente(ctx context.Context, clienteID pgtype.Int4) ([]Pedido, error) {
	rows, err := q.db.Query(ctx, listarPedidosPorCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pedido
	for rows.Next() {
		var i Pedido
		if err := rows.Scan(
			&i.ID,
			&i.Folio,
			&i.ClienteID,
			&i.UsuarioID,
			&i.Estado,
			&i.MetodoPago,
			&i.Subtotal,
			&i.Iva,
			&i.TotalOrden,
			&i.EsBackorder,
			&i.FechaPedido,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrarPartidaPedido = `-- name: RegistrarPartidaPedido :one
INSERT INTO pedido_detalles (
    pedido_id, 
    variante_id, 
    cantidad, 
    precio_unitario_aplicado,
    created_by
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, pedido_id, variante_id, cantidad, precio_unitario_aplicado, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type RegistrarPartidaPedidoParams struct {
	PedidoID               pgtype.Int4    `json:"pedido_id"`
	VarianteID             pgtype.Int4    `json:"variante_id"`
	Cantidad               int32          `json:"cantidad"`
	PrecioUnitarioAplicado pgtype.Numeric `json:"precio_unitario_aplicado"`
	CreatedBy              pgtype.Int4    `json:"created_by"`
}

// Agrega cada producto al detalle del pedido (cite: 259)
func (q *Queries) RegistrarPartidaPedido(ctx context.Context, arg RegistrarPartidaPedidoParams) (PedidoDetalle, error) {
	row := q.db.QueryRow(ctx, registrarPartidaPedido,
		arg.PedidoID,
		arg.VarianteID,
		arg.Cantidad,
		arg.PrecioUnitarioAplicado,
		arg.CreatedBy,
	)
	var i PedidoDetalle
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.VarianteID,
		&i.Cantidad,
		&i.PrecioUnitarioAplicado,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const softDeletePedido = `-- name: SoftDeletePedido :exec
UPDATE pedidos
SET 
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2,
    estado = 'Cancelado'
WHERE id = $1
`

type SoftDeletePedidoParams struct {
	ID        int32       `json:"id"`
	DeletedBy pgtype.Int4 `json:"deleted_by"`
}

// Cancelación lógica del pedido
func (q *Queries) SoftDeletePedido(ctx context.Context, arg SoftDeletePedidoParams) error {
	_, err := q.db.Exec(ctx, softDeletePedido, arg.ID, arg.DeletedBy)
	return err
}

const softDeletePedidoDetalle = `-- name: SoftDeletePedidoDetalle :exec
UPDATE pedido_detalles
SET 
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2
WHERE id = $1
`

type SoftDeletePedidoDetalleParams struct {
	ID        int32       `json:"id"`
	DeletedBy pgtype.Int4 `json:"deleted_by"`
}

// Borrado lógico del detalle del pedido
func (q *Queries) SoftDeletePedidoDetalle(ctx context.Context, arg SoftDeletePedidoDetalleParams) error {
	_, err := q.db.Exec(ctx, softDeletePedidoDetalle, arg.ID, arg.DeletedBy)
	return err
}
