// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pedidos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarBackorderPedido = `-- name: ActualizarBackorderPedido :one
UPDATE pedidos
SET 
    guia_backorder = $2,
    notas_admin_backorder = $3,
    estado_backorder = $4,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, folio, cliente_id, usuario_id, estado, metodo_pago, subtotal, iva, total_orden, es_backorder, guia_backorder, notas_admin_backorder, estado_backorder, guia, notas_admin, fecha_pedido, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type ActualizarBackorderPedidoParams struct {
	ID                  int32       `json:"id"`
	GuiaBackorder       pgtype.Text `json:"guia_backorder"`
	NotasAdminBackorder pgtype.Text `json:"notas_admin_backorder"`
	EstadoBackorder     string      `json:"estado_backorder"`
	UpdatedBy           pgtype.Int4 `json:"updated_by"`
}

func (q *Queries) ActualizarBackorderPedido(ctx context.Context, arg ActualizarBackorderPedidoParams) (Pedido, error) {
	row := q.db.QueryRow(ctx, actualizarBackorderPedido,
		arg.ID,
		arg.GuiaBackorder,
		arg.NotasAdminBackorder,
		arg.EstadoBackorder,
		arg.UpdatedBy,
	)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.UsuarioID,
		&i.Estado,
		&i.MetodoPago,
		&i.Subtotal,
		&i.Iva,
		&i.TotalOrden,
		&i.EsBackorder,
		&i.GuiaBackorder,
		&i.NotasAdminBackorder,
		&i.EstadoBackorder,
		&i.Guia,
		&i.NotasAdmin,
		&i.FechaPedido,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const actualizarEstadoPedido = `-- name: ActualizarEstadoPedido :one
UPDATE pedidos
SET 
    estado = $2,
    guia = $4,
    notas_admin = $5,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, folio, cliente_id, usuario_id, estado, metodo_pago, subtotal, iva, total_orden, es_backorder, guia_backorder, notas_admin_backorder, estado_backorder, guia, notas_admin, fecha_pedido, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type ActualizarEstadoPedidoParams struct {
	ID         int32       `json:"id"`
	Estado     string      `json:"estado"`
	UpdatedBy  pgtype.Int4 `json:"updated_by"`
	Guia       pgtype.Text `json:"guia"`
	NotasAdmin pgtype.Text `json:"notas_admin"`
}

func (q *Queries) ActualizarEstadoPedido(ctx context.Context, arg ActualizarEstadoPedidoParams) (Pedido, error) {
	row := q.db.QueryRow(ctx, actualizarEstadoPedido,
		arg.ID,
		arg.Estado,
		arg.UpdatedBy,
		arg.Guia,
		arg.NotasAdmin,
	)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.UsuarioID,
		&i.Estado,
		&i.MetodoPago,
		&i.Subtotal,
		&i.Iva,
		&i.TotalOrden,
		&i.EsBackorder,
		&i.GuiaBackorder,
		&i.NotasAdminBackorder,
		&i.EstadoBackorder,
		&i.Guia,
		&i.NotasAdmin,
		&i.FechaPedido,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const cancelarDetallePedido = `-- name: CancelarDetallePedido :exec
UPDATE pedido_detalles
SET deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type CancelarDetallePedidoParams struct {
	ID        int32       `json:"id"`
	DeletedBy pgtype.Int4 `json:"deleted_by"`
}

func (q *Queries) CancelarDetallePedido(ctx context.Context, arg CancelarDetallePedidoParams) error {
	_, err := q.db.Exec(ctx, cancelarDetallePedido, arg.ID, arg.DeletedBy)
	return err
}

const crearPedido = `-- name: CrearPedido :one
INSERT INTO pedidos (
    folio, 
    cliente_id, 
    usuario_id, 
    estado, 
    metodo_pago, 
    subtotal, 
    iva, 
    total_orden, 
    es_backorder, 
    guia_backorder,
    notas_admin_backorder,
    estado_backorder,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, folio, cliente_id, usuario_id, estado, metodo_pago, subtotal, iva, total_orden, es_backorder, guia_backorder, notas_admin_backorder, estado_backorder, guia, notas_admin, fecha_pedido, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CrearPedidoParams struct {
	Folio               string         `json:"folio"`
	ClienteID           pgtype.Int4    `json:"cliente_id"`
	UsuarioID           pgtype.Int4    `json:"usuario_id"`
	Estado              string         `json:"estado"`
	MetodoPago          string         `json:"metodo_pago"`
	Subtotal            pgtype.Numeric `json:"subtotal"`
	Iva                 pgtype.Numeric `json:"iva"`
	TotalOrden          pgtype.Numeric `json:"total_orden"`
	EsBackorder         pgtype.Bool    `json:"es_backorder"`
	GuiaBackorder       pgtype.Text    `json:"guia_backorder"`
	NotasAdminBackorder pgtype.Text    `json:"notas_admin_backorder"`
	EstadoBackorder     string         `json:"estado_backorder"`
	CreatedBy           pgtype.Int4    `json:"created_by"`
}

func (q *Queries) CrearPedido(ctx context.Context, arg CrearPedidoParams) (Pedido, error) {
	row := q.db.QueryRow(ctx, crearPedido,
		arg.Folio,
		arg.ClienteID,
		arg.UsuarioID,
		arg.Estado,
		arg.MetodoPago,
		arg.Subtotal,
		arg.Iva,
		arg.TotalOrden,
		arg.EsBackorder,
		arg.GuiaBackorder,
		arg.NotasAdminBackorder,
		arg.EstadoBackorder,
		arg.CreatedBy,
	)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.UsuarioID,
		&i.Estado,
		&i.MetodoPago,
		&i.Subtotal,
		&i.Iva,
		&i.TotalOrden,
		&i.EsBackorder,
		&i.GuiaBackorder,
		&i.NotasAdminBackorder,
		&i.EstadoBackorder,
		&i.Guia,
		&i.NotasAdmin,
		&i.FechaPedido,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const crearPedidoDetalle = `-- name: CrearPedidoDetalle :one
INSERT INTO pedido_detalles (
    pedido_id, 
    variante_id, 
    cantidad, 
    precio_unitario_aplicado, 
    tipo_registro,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, pedido_id, variante_id, cantidad, precio_unitario_aplicado, tipo_registro, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CrearPedidoDetalleParams struct {
	PedidoID               pgtype.Int4    `json:"pedido_id"`
	VarianteID             pgtype.Int4    `json:"variante_id"`
	Cantidad               int32          `json:"cantidad"`
	PrecioUnitarioAplicado pgtype.Numeric `json:"precio_unitario_aplicado"`
	TipoRegistro           string         `json:"tipo_registro"`
	CreatedBy              pgtype.Int4    `json:"created_by"`
}

func (q *Queries) CrearPedidoDetalle(ctx context.Context, arg CrearPedidoDetalleParams) (PedidoDetalle, error) {
	row := q.db.QueryRow(ctx, crearPedidoDetalle,
		arg.PedidoID,
		arg.VarianteID,
		arg.Cantidad,
		arg.PrecioUnitarioAplicado,
		arg.TipoRegistro,
		arg.CreatedBy,
	)
	var i PedidoDetalle
	err := row.Scan(
		&i.ID,
		&i.PedidoID,
		&i.VarianteID,
		&i.Cantidad,
		&i.PrecioUnitarioAplicado,
		&i.TipoRegistro,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getCommittedStock = `-- name: GetCommittedStock :one
SELECT COALESCE(SUM(pd.cantidad), 0)::INT as committed_stock
FROM pedido_detalles pd
JOIN pedidos p ON pd.pedido_id = p.id
WHERE pd.variante_id = $1 
  AND p.estado IN ('Pendiente', 'En Proceso') -- Estados que reservan stock
  AND pd.deleted_at IS NULL 
  AND p.deleted_at IS NULL
`

func (q *Queries) GetCommittedStock(ctx context.Context, varianteID pgtype.Int4) (int32, error) {
	row := q.db.QueryRow(ctx, getCommittedStock, varianteID)
	var committed_stock int32
	err := row.Scan(&committed_stock)
	return committed_stock, err
}

const getPedido = `-- name: GetPedido :one
SELECT id, folio, cliente_id, usuario_id, estado, metodo_pago, subtotal, iva, total_orden, es_backorder, guia_backorder, notas_admin_backorder, estado_backorder, guia, notas_admin, fecha_pedido, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM pedidos
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetPedido(ctx context.Context, id int32) (Pedido, error) {
	row := q.db.QueryRow(ctx, getPedido, id)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.UsuarioID,
		&i.Estado,
		&i.MetodoPago,
		&i.Subtotal,
		&i.Iva,
		&i.TotalOrden,
		&i.EsBackorder,
		&i.GuiaBackorder,
		&i.NotasAdminBackorder,
		&i.EstadoBackorder,
		&i.Guia,
		&i.NotasAdmin,
		&i.FechaPedido,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getPedidoByFolio = `-- name: GetPedidoByFolio :one
SELECT id, folio, cliente_id, usuario_id, estado, metodo_pago, subtotal, iva, total_orden, es_backorder, guia_backorder, notas_admin_backorder, estado_backorder, guia, notas_admin, fecha_pedido, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM pedidos
WHERE folio = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetPedidoByFolio(ctx context.Context, folio string) (Pedido, error) {
	row := q.db.QueryRow(ctx, getPedidoByFolio, folio)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.Folio,
		&i.ClienteID,
		&i.UsuarioID,
		&i.Estado,
		&i.MetodoPago,
		&i.Subtotal,
		&i.Iva,
		&i.TotalOrden,
		&i.EsBackorder,
		&i.GuiaBackorder,
		&i.NotasAdminBackorder,
		&i.EstadoBackorder,
		&i.Guia,
		&i.NotasAdmin,
		&i.FechaPedido,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const listarPedidos = `-- name: ListarPedidos :many
SELECT id, folio, cliente_id, usuario_id, estado, metodo_pago, subtotal, iva, total_orden, es_backorder, guia_backorder, notas_admin_backorder, estado_backorder, guia, notas_admin, fecha_pedido, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM pedidos
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListarPedidos(ctx context.Context) ([]Pedido, error) {
	rows, err := q.db.Query(ctx, listarPedidos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pedido
	for rows.Next() {
		var i Pedido
		if err := rows.Scan(
			&i.ID,
			&i.Folio,
			&i.ClienteID,
			&i.UsuarioID,
			&i.Estado,
			&i.MetodoPago,
			&i.Subtotal,
			&i.Iva,
			&i.TotalOrden,
			&i.EsBackorder,
			&i.GuiaBackorder,
			&i.NotasAdminBackorder,
			&i.EstadoBackorder,
			&i.Guia,
			&i.NotasAdmin,
			&i.FechaPedido,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPedidosDetalle = `-- name: ListarPedidosDetalle :many
SELECT d.id, d.pedido_id, d.variante_id, d.cantidad, d.precio_unitario_aplicado, d.tipo_registro, d.created_at, d.updated_at, d.deleted_at, d.created_by, d.updated_by, d.deleted_by,
       v.sku AS variante_sku,
       p.descripcion AS padre_descripcion,
       p.descripcion_extendida AS padre_descripcion_extendida,
       p.foto_url AS padre_foto_url
FROM pedido_detalles d
LEFT JOIN productos_variantes v ON d.variante_id = v.id
LEFT JOIN productos_padre p ON v.padre_id = p.id
WHERE d.pedido_id = $1 AND d.deleted_at IS NULL
`

type ListarPedidosDetalleRow struct {
	ID                        int32            `json:"id"`
	PedidoID                  pgtype.Int4      `json:"pedido_id"`
	VarianteID                pgtype.Int4      `json:"variante_id"`
	Cantidad                  int32            `json:"cantidad"`
	PrecioUnitarioAplicado    pgtype.Numeric   `json:"precio_unitario_aplicado"`
	TipoRegistro              string           `json:"tipo_registro"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
	UpdatedAt                 pgtype.Timestamp `json:"updated_at"`
	DeletedAt                 pgtype.Timestamp `json:"deleted_at"`
	CreatedBy                 pgtype.Int4      `json:"created_by"`
	UpdatedBy                 pgtype.Int4      `json:"updated_by"`
	DeletedBy                 pgtype.Int4      `json:"deleted_by"`
	VarianteSku               pgtype.Text      `json:"variante_sku"`
	PadreDescripcion          pgtype.Text      `json:"padre_descripcion"`
	PadreDescripcionExtendida pgtype.Text      `json:"padre_descripcion_extendida"`
	PadreFotoUrl              pgtype.Text      `json:"padre_foto_url"`
}

func (q *Queries) ListarPedidosDetalle(ctx context.Context, pedidoID pgtype.Int4) ([]ListarPedidosDetalleRow, error) {
	rows, err := q.db.Query(ctx, listarPedidosDetalle, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPedidosDetalleRow
	for rows.Next() {
		var i ListarPedidosDetalleRow
		if err := rows.Scan(
			&i.ID,
			&i.PedidoID,
			&i.VarianteID,
			&i.Cantidad,
			&i.PrecioUnitarioAplicado,
			&i.TipoRegistro,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.VarianteSku,
			&i.PadreDescripcion,
			&i.PadreDescripcionExtendida,
			&i.PadreFotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPedidosPorCliente = `-- name: ListarPedidosPorCliente :many
SELECT id, folio, cliente_id, usuario_id, estado, metodo_pago, subtotal, iva, total_orden, es_backorder, guia_backorder, notas_admin_backorder, estado_backorder, guia, notas_admin, fecha_pedido, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM pedidos
WHERE cliente_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListarPedidosPorCliente(ctx context.Context, clienteID pgtype.Int4) ([]Pedido, error) {
	rows, err := q.db.Query(ctx, listarPedidosPorCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pedido
	for rows.Next() {
		var i Pedido
		if err := rows.Scan(
			&i.ID,
			&i.Folio,
			&i.ClienteID,
			&i.UsuarioID,
			&i.Estado,
			&i.MetodoPago,
			&i.Subtotal,
			&i.Iva,
			&i.TotalOrden,
			&i.EsBackorder,
			&i.GuiaBackorder,
			&i.NotasAdminBackorder,
			&i.EstadoBackorder,
			&i.Guia,
			&i.NotasAdmin,
			&i.FechaPedido,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pedidoDentroVentanaModificacion = `-- name: PedidoDentroVentanaModificacion :one
SELECT (CURRENT_TIMESTAMP - COALESCE(fecha_pedido, created_at)) < INTERVAL '2 hours' AS dentro_ventana
FROM pedidos WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) PedidoDentroVentanaModificacion(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, pedidoDentroVentanaModificacion, id)
	var dentro_ventana bool
	err := row.Scan(&dentro_ventana)
	return dentro_ventana, err
}
