// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permisos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarPermisoUsuario = `-- name: ActualizarPermisoUsuario :exec
INSERT INTO usuario_permisos (usuario_id, permiso_id, activo, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (usuario_id, permiso_id)
DO UPDATE SET
    activo = EXCLUDED.activo,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by
`

type ActualizarPermisoUsuarioParams struct {
	UsuarioID int32       `json:"usuario_id"`
	PermisoID int32       `json:"permiso_id"`
	Activo    bool        `json:"activo"`
	UpdatedBy pgtype.Int4 `json:"updated_by"`
}

// Activa/desactiva un módulo para un usuario (upsert)
func (q *Queries) ActualizarPermisoUsuario(ctx context.Context, arg ActualizarPermisoUsuarioParams) error {
	_, err := q.db.Exec(ctx, actualizarPermisoUsuario,
		arg.UsuarioID,
		arg.PermisoID,
		arg.Activo,
		arg.UpdatedBy,
	)
	return err
}

const contarPermisosConfiguradosDeUsuario = `-- name: ContarPermisosConfiguradosDeUsuario :one
SELECT COUNT(*) FROM usuario_permisos WHERE usuario_id = $1
`

// Cuenta cuántos permisos han sido configurados explícitamente para un usuario
func (q *Queries) ContarPermisosConfiguradosDeUsuario(ctx context.Context, usuarioID int32) (int64, error) {
	row := q.db.QueryRow(ctx, contarPermisosConfiguradosDeUsuario, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listarPermisos = `-- name: ListarPermisos :many
SELECT id, clave, nombre, grupo, orden
FROM permisos
ORDER BY orden ASC, id ASC
`

type ListarPermisosRow struct {
	ID     int32  `json:"id"`
	Clave  string `json:"clave"`
	Nombre string `json:"nombre"`
	Grupo  string `json:"grupo"`
	Orden  int32  `json:"orden"`
}

// Lista todos los módulos/permisos del menú del Panel de Control
func (q *Queries) ListarPermisos(ctx context.Context) ([]ListarPermisosRow, error) {
	rows, err := q.db.Query(ctx, listarPermisos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPermisosRow
	for rows.Next() {
		var i ListarPermisosRow
		if err := rows.Scan(
			&i.ID,
			&i.Clave,
			&i.Nombre,
			&i.Grupo,
			&i.Orden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPermisosActivosDeUsuario = `-- name: ListarPermisosActivosDeUsuario :many
SELECT p.clave
FROM permisos p
JOIN usuario_permisos up ON up.permiso_id = p.id AND up.usuario_id = $1
WHERE up.activo = TRUE
ORDER BY p.orden ASC, p.id ASC
`

// Claves de los módulos activos de un usuario (para el login/perfil)
func (q *Queries) ListarPermisosActivosDeUsuario(ctx context.Context, usuarioID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listarPermisosActivosDeUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var clave string
		if err := rows.Scan(&clave); err != nil {
			return nil, err
		}
		items = append(items, clave)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPermisosDeUsuario = `-- name: ListarPermisosDeUsuario :many
SELECT p.id, p.clave, p.nombre, p.grupo, p.orden, COALESCE(up.activo, FALSE) AS activo
FROM permisos p
LEFT JOIN usuario_permisos up ON up.permiso_id = p.id AND up.usuario_id = $1
ORDER BY p.orden ASC, p.id ASC
`

type ListarPermisosDeUsuarioRow struct {
	ID     int32  `json:"id"`
	Clave  string `json:"clave"`
	Nombre string `json:"nombre"`
	Grupo  string `json:"grupo"`
	Orden  int32  `json:"orden"`
	Activo bool   `json:"activo"`
}

// Lista los módulos con el estado (activo/inactivo) configurado para un usuario
func (q *Queries) ListarPermisosDeUsuario(ctx context.Context, usuarioID int32) ([]ListarPermisosDeUsuarioRow, error) {
	rows, err := q.db.Query(ctx, listarPermisosDeUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPermisosDeUsuarioRow
	for rows.Next() {
		var i ListarPermisosDeUsuarioRow
		if err := rows.Scan(
			&i.ID,
			&i.Clave,
			&i.Nombre,
			&i.Grupo,
			&i.Orden,
			&i.Activo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
