// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: productos_integracion.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProducto = `-- name: CreateProducto :one
INSERT INTO productos_integracion (
    cse_prod, cve_prod, nom_prod, desc_prod, uni_med, uni_med_p, 
    costo_prod, f_act_cto, f_act_pre, cto_ent, fec_ent, fec_ant
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, cse_prod, cve_prod, nom_prod, desc_prod, uni_med, uni_med_p, costo_prod, f_act_cto, f_act_pre, cto_ent, fec_ent, fec_ant
`

type CreateProductoParams struct {
	CseProd   pgtype.Text      `json:"cse_prod"`
	CveProd   pgtype.Text      `json:"cve_prod"`
	NomProd   pgtype.Text      `json:"nom_prod"`
	DescProd  pgtype.Text      `json:"desc_prod"`
	UniMed    pgtype.Text      `json:"uni_med"`
	UniMedP   pgtype.Text      `json:"uni_med_p"`
	CostoProd pgtype.Numeric   `json:"costo_prod"`
	FActCto   pgtype.Timestamp `json:"f_act_cto"`
	FActPre   pgtype.Timestamp `json:"f_act_pre"`
	CtoEnt    pgtype.Numeric   `json:"cto_ent"`
	FecEnt    pgtype.Timestamp `json:"fec_ent"`
	FecAnt    pgtype.Timestamp `json:"fec_ant"`
}

func (q *Queries) CreateProducto(ctx context.Context, arg CreateProductoParams) (ProductosIntegracion, error) {
	row := q.db.QueryRow(ctx, createProducto,
		arg.CseProd,
		arg.CveProd,
		arg.NomProd,
		arg.DescProd,
		arg.UniMed,
		arg.UniMedP,
		arg.CostoProd,
		arg.FActCto,
		arg.FActPre,
		arg.CtoEnt,
		arg.FecEnt,
		arg.FecAnt,
	)
	var i ProductosIntegracion
	err := row.Scan(
		&i.ID,
		&i.CseProd,
		&i.CveProd,
		&i.NomProd,
		&i.DescProd,
		&i.UniMed,
		&i.UniMedP,
		&i.CostoProd,
		&i.FActCto,
		&i.FActPre,
		&i.CtoEnt,
		&i.FecEnt,
		&i.FecAnt,
	)
	return i, err
}

const getProductoByClave = `-- name: GetProductoByClave :one
SELECT id, cse_prod, cve_prod, nom_prod, desc_prod, uni_med, uni_med_p, costo_prod, f_act_cto, f_act_pre, cto_ent, fec_ent, fec_ant FROM productos_integracion
WHERE cve_prod = $1 LIMIT 1
`

// Aprovecha el índice UNIQUE que definiste en cve_prod
func (q *Queries) GetProductoByClave(ctx context.Context, cveProd pgtype.Text) (ProductosIntegracion, error) {
	row := q.db.QueryRow(ctx, getProductoByClave, cveProd)
	var i ProductosIntegracion
	err := row.Scan(
		&i.ID,
		&i.CseProd,
		&i.CveProd,
		&i.NomProd,
		&i.DescProd,
		&i.UniMed,
		&i.UniMedP,
		&i.CostoProd,
		&i.FActCto,
		&i.FActPre,
		&i.CtoEnt,
		&i.FecEnt,
		&i.FecAnt,
	)
	return i, err
}

const getProductoByID = `-- name: GetProductoByID :one
SELECT id, cse_prod, cve_prod, nom_prod, desc_prod, uni_med, uni_med_p, costo_prod, f_act_cto, f_act_pre, cto_ent, fec_ent, fec_ant FROM productos_integracion
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductoByID(ctx context.Context, id int32) (ProductosIntegracion, error) {
	row := q.db.QueryRow(ctx, getProductoByID, id)
	var i ProductosIntegracion
	err := row.Scan(
		&i.ID,
		&i.CseProd,
		&i.CveProd,
		&i.NomProd,
		&i.DescProd,
		&i.UniMed,
		&i.UniMedP,
		&i.CostoProd,
		&i.FActCto,
		&i.FActPre,
		&i.CtoEnt,
		&i.FecEnt,
		&i.FecAnt,
	)
	return i, err
}

const listProductos = `-- name: ListProductos :many
SELECT id, cse_prod, cve_prod, nom_prod, desc_prod, uni_med, uni_med_p, costo_prod, f_act_cto, f_act_pre, cto_ent, fec_ent, fec_ant FROM productos_integracion
ORDER BY nom_prod ASC
`

func (q *Queries) ListProductos(ctx context.Context) ([]ProductosIntegracion, error) {
	rows, err := q.db.Query(ctx, listProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductosIntegracion
	for rows.Next() {
		var i ProductosIntegracion
		if err := rows.Scan(
			&i.ID,
			&i.CseProd,
			&i.CveProd,
			&i.NomProd,
			&i.DescProd,
			&i.UniMed,
			&i.UniMedP,
			&i.CostoProd,
			&i.FActCto,
			&i.FActPre,
			&i.CtoEnt,
			&i.FecEnt,
			&i.FecAnt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCostos = `-- name: UpdateCostos :one
UPDATE productos_integracion
SET 
    costo_prod = $2,
    f_act_cto = $3,
    cto_ent = $4,
    fec_ent = $5,
    fec_ant = $6
WHERE id = $1
RETURNING id, cse_prod, cve_prod, nom_prod, desc_prod, uni_med, uni_med_p, costo_prod, f_act_cto, f_act_pre, cto_ent, fec_ent, fec_ant
`

type UpdateCostosParams struct {
	ID        int32            `json:"id"`
	CostoProd pgtype.Numeric   `json:"costo_prod"`
	FActCto   pgtype.Timestamp `json:"f_act_cto"`
	CtoEnt    pgtype.Numeric   `json:"cto_ent"`
	FecEnt    pgtype.Timestamp `json:"fec_ent"`
	FecAnt    pgtype.Timestamp `json:"fec_ant"`
}

// Consulta específica para cuando se actualizan precios/costos y sus fechas
func (q *Queries) UpdateCostos(ctx context.Context, arg UpdateCostosParams) (ProductosIntegracion, error) {
	row := q.db.QueryRow(ctx, updateCostos,
		arg.ID,
		arg.CostoProd,
		arg.FActCto,
		arg.CtoEnt,
		arg.FecEnt,
		arg.FecAnt,
	)
	var i ProductosIntegracion
	err := row.Scan(
		&i.ID,
		&i.CseProd,
		&i.CveProd,
		&i.NomProd,
		&i.DescProd,
		&i.UniMed,
		&i.UniMedP,
		&i.CostoProd,
		&i.FActCto,
		&i.FActPre,
		&i.CtoEnt,
		&i.FecEnt,
		&i.FecAnt,
	)
	return i, err
}

const updateProducto = `-- name: UpdateProducto :one
UPDATE productos_integracion
SET 
    cse_prod = $2,
    nom_prod = $3,
    desc_prod = $4,
    uni_med = $5,
    uni_med_p = $6
WHERE id = $1
RETURNING id, cse_prod, cve_prod, nom_prod, desc_prod, uni_med, uni_med_p, costo_prod, f_act_cto, f_act_pre, cto_ent, fec_ent, fec_ant
`

type UpdateProductoParams struct {
	ID       int32       `json:"id"`
	CseProd  pgtype.Text `json:"cse_prod"`
	NomProd  pgtype.Text `json:"nom_prod"`
	DescProd pgtype.Text `json:"desc_prod"`
	UniMed   pgtype.Text `json:"uni_med"`
	UniMedP  pgtype.Text `json:"uni_med_p"`
}

func (q *Queries) UpdateProducto(ctx context.Context, arg UpdateProductoParams) (ProductosIntegracion, error) {
	row := q.db.QueryRow(ctx, updateProducto,
		arg.ID,
		arg.CseProd,
		arg.NomProd,
		arg.DescProd,
		arg.UniMed,
		arg.UniMedP,
	)
	var i ProductosIntegracion
	err := row.Scan(
		&i.ID,
		&i.CseProd,
		&i.CveProd,
		&i.NomProd,
		&i.DescProd,
		&i.UniMed,
		&i.UniMedP,
		&i.CostoProd,
		&i.FActCto,
		&i.FActPre,
		&i.CtoEnt,
		&i.FecEnt,
		&i.FecAnt,
	)
	return i, err
}

const upsertProducto = `-- name: UpsertProducto :one
INSERT INTO productos_integracion (
    cse_prod, cve_prod, nom_prod, desc_prod, uni_med, uni_med_p, 
    costo_prod, f_act_cto, f_act_pre, cto_ent, fec_ent, fec_ant
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (cve_prod) DO UPDATE SET
    cse_prod = EXCLUDED.cse_prod,
    nom_prod = EXCLUDED.nom_prod,
    desc_prod = EXCLUDED.desc_prod,
    uni_med = EXCLUDED.uni_med,
    uni_med_p = EXCLUDED.uni_med_p,
    costo_prod = EXCLUDED.costo_prod,
    f_act_cto = EXCLUDED.f_act_cto,
    f_act_pre = EXCLUDED.f_act_pre,
    cto_ent = EXCLUDED.cto_ent,
    fec_ent = EXCLUDED.fec_ent,
    fec_ant = EXCLUDED.fec_ant
RETURNING id, cse_prod, cve_prod, nom_prod, desc_prod, uni_med, uni_med_p, costo_prod, f_act_cto, f_act_pre, cto_ent, fec_ent, fec_ant
`

type UpsertProductoParams struct {
	CseProd   pgtype.Text      `json:"cse_prod"`
	CveProd   pgtype.Text      `json:"cve_prod"`
	NomProd   pgtype.Text      `json:"nom_prod"`
	DescProd  pgtype.Text      `json:"desc_prod"`
	UniMed    pgtype.Text      `json:"uni_med"`
	UniMedP   pgtype.Text      `json:"uni_med_p"`
	CostoProd pgtype.Numeric   `json:"costo_prod"`
	FActCto   pgtype.Timestamp `json:"f_act_cto"`
	FActPre   pgtype.Timestamp `json:"f_act_pre"`
	CtoEnt    pgtype.Numeric   `json:"cto_ent"`
	FecEnt    pgtype.Timestamp `json:"fec_ent"`
	FecAnt    pgtype.Timestamp `json:"fec_ant"`
}

func (q *Queries) UpsertProducto(ctx context.Context, arg UpsertProductoParams) (ProductosIntegracion, error) {
	row := q.db.QueryRow(ctx, upsertProducto,
		arg.CseProd,
		arg.CveProd,
		arg.NomProd,
		arg.DescProd,
		arg.UniMed,
		arg.UniMedP,
		arg.CostoProd,
		arg.FActCto,
		arg.FActPre,
		arg.CtoEnt,
		arg.FecEnt,
		arg.FecAnt,
	)
	var i ProductosIntegracion
	err := row.Scan(
		&i.ID,
		&i.CseProd,
		&i.CveProd,
		&i.NomProd,
		&i.DescProd,
		&i.UniMed,
		&i.UniMedP,
		&i.CostoProd,
		&i.FActCto,
		&i.FActPre,
		&i.CtoEnt,
		&i.FecEnt,
		&i.FecAnt,
	)
	return i, err
}
