// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: productos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarProductoPadre = `-- name: ActualizarProductoPadre :one
UPDATE productos_padre
SET 
    cve_prod_integracion = $2,
    descripcion = $3,
    foto_url = $4,
    ficha_tecnica = $5,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, cve_prod_integracion, descripcion, foto_url, ficha_tecnica, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type ActualizarProductoPadreParams struct {
	ID                 int32       `json:"id"`
	CveProdIntegracion pgtype.Text `json:"cve_prod_integracion"`
	Descripcion        pgtype.Text `json:"descripcion"`
	FotoUrl            pgtype.Text `json:"foto_url"`
	FichaTecnica       pgtype.Text `json:"ficha_tecnica"`
	UpdatedBy          pgtype.Int4 `json:"updated_by"`
}

func (q *Queries) ActualizarProductoPadre(ctx context.Context, arg ActualizarProductoPadreParams) (ProductosPadre, error) {
	row := q.db.QueryRow(ctx, actualizarProductoPadre,
		arg.ID,
		arg.CveProdIntegracion,
		arg.Descripcion,
		arg.FotoUrl,
		arg.FichaTecnica,
		arg.UpdatedBy,
	)
	var i ProductosPadre
	err := row.Scan(
		&i.ID,
		&i.CveProdIntegracion,
		&i.Descripcion,
		&i.FotoUrl,
		&i.FichaTecnica,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const actualizarStock = `-- name: ActualizarStock :exec
UPDATE productos_variantes
SET 
    stock_actual = $2,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $3
WHERE id = $1
`

type ActualizarStockParams struct {
	ID          int32       `json:"id"`
	StockActual int32       `json:"stock_actual"`
	UpdatedBy   pgtype.Int4 `json:"updated_by"`
}

// Sincronización de inventario en tiempo real (cite: 43)
func (q *Queries) ActualizarStock(ctx context.Context, arg ActualizarStockParams) error {
	_, err := q.db.Exec(ctx, actualizarStock, arg.ID, arg.StockActual, arg.UpdatedBy)
	return err
}

const actualizarVariante = `-- name: ActualizarVariante :one
UPDATE productos_variantes
SET 
    padre_id = $2,
    sku = $3,
    medida = $4,
    precio_distribuidor = $5,
    precio_lista = $6,
    precio_publico = $7,
    stock_actual = $8,
    unidad_medida = $9,
    lead_time_dias = $10,
    especificaciones = $11,
    categoria = $12,
    subgrupo = $13,
    modelo = $14,
    tipo = $15,
    marca = $16,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $17
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, padre_id, sku, medida, precio_distribuidor, precio_lista, precio_publico, stock_actual, unidad_medida, lead_time_dias, especificaciones, categoria, subgrupo, modelo, tipo, marca, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type ActualizarVarianteParams struct {
	ID                 int32          `json:"id"`
	PadreID            pgtype.Int4    `json:"padre_id"`
	Sku                string         `json:"sku"`
	Medida             pgtype.Text    `json:"medida"`
	PrecioDistribuidor pgtype.Numeric `json:"precio_distribuidor"`
	PrecioLista        pgtype.Numeric `json:"precio_lista"`
	PrecioPublico      pgtype.Numeric `json:"precio_publico"`
	StockActual        int32          `json:"stock_actual"`
	UnidadMedida       string         `json:"unidad_medida"`
	LeadTimeDias       pgtype.Int4    `json:"lead_time_dias"`
	Especificaciones   pgtype.Text    `json:"especificaciones"`
	Categoria          pgtype.Text    `json:"categoria"`
	Subgrupo           pgtype.Text    `json:"subgrupo"`
	Modelo             pgtype.Text    `json:"modelo"`
	Tipo               pgtype.Text    `json:"tipo"`
	Marca              pgtype.Text    `json:"marca"`
	UpdatedBy          pgtype.Int4    `json:"updated_by"`
}

func (q *Queries) ActualizarVariante(ctx context.Context, arg ActualizarVarianteParams) (ProductosVariante, error) {
	row := q.db.QueryRow(ctx, actualizarVariante,
		arg.ID,
		arg.PadreID,
		arg.Sku,
		arg.Medida,
		arg.PrecioDistribuidor,
		arg.PrecioLista,
		arg.PrecioPublico,
		arg.StockActual,
		arg.UnidadMedida,
		arg.LeadTimeDias,
		arg.Especificaciones,
		arg.Categoria,
		arg.Subgrupo,
		arg.Modelo,
		arg.Tipo,
		arg.Marca,
		arg.UpdatedBy,
	)
	var i ProductosVariante
	err := row.Scan(
		&i.ID,
		&i.PadreID,
		&i.Sku,
		&i.Medida,
		&i.PrecioDistribuidor,
		&i.PrecioLista,
		&i.PrecioPublico,
		&i.StockActual,
		&i.UnidadMedida,
		&i.LeadTimeDias,
		&i.Especificaciones,
		&i.Categoria,
		&i.Subgrupo,
		&i.Modelo,
		&i.Tipo,
		&i.Marca,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const crearProductoPadre = `-- name: CrearProductoPadre :one


INSERT INTO productos_padre (
    cve_prod_integracion, 
    descripcion, 
    foto_url, 
    ficha_tecnica, 
    created_by
) VALUES (
    $1, 
    $2, 
    $3, 
    $4, 
    $5
) RETURNING id, cve_prod_integracion, descripcion, foto_url, ficha_tecnica, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CrearProductoPadreParams struct {
	CveProdIntegracion pgtype.Text `json:"cve_prod_integracion"`
	Descripcion        pgtype.Text `json:"descripcion"`
	FotoUrl            pgtype.Text `json:"foto_url"`
	FichaTecnica       pgtype.Text `json:"ficha_tecnica"`
	CreatedBy          pgtype.Int4 `json:"created_by"`
}

// internal/sql/productos.sql
// ==========================================
// CRUD PRODUCTOS PADRE (Contenedores)
// ==========================================
func (q *Queries) CrearProductoPadre(ctx context.Context, arg CrearProductoPadreParams) (ProductosPadre, error) {
	row := q.db.QueryRow(ctx, crearProductoPadre,
		arg.CveProdIntegracion,
		arg.Descripcion,
		arg.FotoUrl,
		arg.FichaTecnica,
		arg.CreatedBy,
	)
	var i ProductosPadre
	err := row.Scan(
		&i.ID,
		&i.CveProdIntegracion,
		&i.Descripcion,
		&i.FotoUrl,
		&i.FichaTecnica,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const crearVariante = `-- name: CrearVariante :one

INSERT INTO productos_variantes (
padre_id, sku, medida, precio_distribuidor, precio_lista, precio_publico, 
    stock_actual, unidad_medida, lead_time_dias, especificaciones, 
    categoria, subgrupo, modelo, tipo, marca, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, padre_id, sku, medida, precio_distribuidor, precio_lista, precio_publico, stock_actual, unidad_medida, lead_time_dias, especificaciones, categoria, subgrupo, modelo, tipo, marca, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CrearVarianteParams struct {
	PadreID            pgtype.Int4    `json:"padre_id"`
	Sku                string         `json:"sku"`
	Medida             pgtype.Text    `json:"medida"`
	PrecioDistribuidor pgtype.Numeric `json:"precio_distribuidor"`
	PrecioLista        pgtype.Numeric `json:"precio_lista"`
	PrecioPublico      pgtype.Numeric `json:"precio_publico"`
	StockActual        int32          `json:"stock_actual"`
	UnidadMedida       string         `json:"unidad_medida"`
	LeadTimeDias       pgtype.Int4    `json:"lead_time_dias"`
	Especificaciones   pgtype.Text    `json:"especificaciones"`
	Categoria          pgtype.Text    `json:"categoria"`
	Subgrupo           pgtype.Text    `json:"subgrupo"`
	Modelo             pgtype.Text    `json:"modelo"`
	Tipo               pgtype.Text    `json:"tipo"`
	Marca              pgtype.Text    `json:"marca"`
	CreatedBy          pgtype.Int4    `json:"created_by"`
}

// ==========================================
// CRUD VARIANTES (SKUs Específicos)
// ==========================================
// Registra una variante (ej. Tornillo de 1/2") ligada a un Padre (cite: 187, 191)
func (q *Queries) CrearVariante(ctx context.Context, arg CrearVarianteParams) (ProductosVariante, error) {
	row := q.db.QueryRow(ctx, crearVariante,
		arg.PadreID,
		arg.Sku,
		arg.Medida,
		arg.PrecioDistribuidor,
		arg.PrecioLista,
		arg.PrecioPublico,
		arg.StockActual,
		arg.UnidadMedida,
		arg.LeadTimeDias,
		arg.Especificaciones,
		arg.Categoria,
		arg.Subgrupo,
		arg.Modelo,
		arg.Tipo,
		arg.Marca,
		arg.CreatedBy,
	)
	var i ProductosVariante
	err := row.Scan(
		&i.ID,
		&i.PadreID,
		&i.Sku,
		&i.Medida,
		&i.PrecioDistribuidor,
		&i.PrecioLista,
		&i.PrecioPublico,
		&i.StockActual,
		&i.UnidadMedida,
		&i.LeadTimeDias,
		&i.Especificaciones,
		&i.Categoria,
		&i.Subgrupo,
		&i.Modelo,
		&i.Tipo,
		&i.Marca,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getProductoPadre = `-- name: GetProductoPadre :one
SELECT p.id, p.cve_prod_integracion, p.descripcion, p.foto_url, p.ficha_tecnica, p.created_at, p.updated_at, p.deleted_at, p.created_by, p.updated_by, p.deleted_by, 
       COALESCE(pi.nom_prod, '') AS nombre_tecnico, 
       COALESCE(pi.cse_prod, '') AS categoria
FROM productos_padre p
LEFT JOIN productos_integracion pi ON p.cve_prod_integracion = pi.cve_prod
WHERE p.id = $1 AND p.deleted_at IS NULL LIMIT 1
`

type GetProductoPadreRow struct {
	ID                 int32            `json:"id"`
	CveProdIntegracion pgtype.Text      `json:"cve_prod_integracion"`
	Descripcion        pgtype.Text      `json:"descripcion"`
	FotoUrl            pgtype.Text      `json:"foto_url"`
	FichaTecnica       pgtype.Text      `json:"ficha_tecnica"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	DeletedAt          pgtype.Timestamp `json:"deleted_at"`
	CreatedBy          pgtype.Int4      `json:"created_by"`
	UpdatedBy          pgtype.Int4      `json:"updated_by"`
	DeletedBy          pgtype.Int4      `json:"deleted_by"`
	NombreTecnico      string           `json:"nombre_tecnico"`
	Categoria          string           `json:"categoria"`
}

func (q *Queries) GetProductoPadre(ctx context.Context, id int32) (GetProductoPadreRow, error) {
	row := q.db.QueryRow(ctx, getProductoPadre, id)
	var i GetProductoPadreRow
	err := row.Scan(
		&i.ID,
		&i.CveProdIntegracion,
		&i.Descripcion,
		&i.FotoUrl,
		&i.FichaTecnica,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.NombreTecnico,
		&i.Categoria,
	)
	return i, err
}

const getProductoPadreByDescripcion = `-- name: GetProductoPadreByDescripcion :one
SELECT p.id, p.cve_prod_integracion, p.descripcion, p.foto_url, p.ficha_tecnica, p.created_at, p.updated_at, p.deleted_at, p.created_by, p.updated_by, p.deleted_by, 
       COALESCE(pi.nom_prod, '') AS nombre_tecnico, 
       COALESCE(pi.cse_prod, '') AS categoria
FROM productos_padre p
LEFT JOIN productos_integracion pi ON p.cve_prod_integracion = pi.cve_prod
WHERE p.descripcion = $1 AND p.deleted_at IS NULL LIMIT 1
`

type GetProductoPadreByDescripcionRow struct {
	ID                 int32            `json:"id"`
	CveProdIntegracion pgtype.Text      `json:"cve_prod_integracion"`
	Descripcion        pgtype.Text      `json:"descripcion"`
	FotoUrl            pgtype.Text      `json:"foto_url"`
	FichaTecnica       pgtype.Text      `json:"ficha_tecnica"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	DeletedAt          pgtype.Timestamp `json:"deleted_at"`
	CreatedBy          pgtype.Int4      `json:"created_by"`
	UpdatedBy          pgtype.Int4      `json:"updated_by"`
	DeletedBy          pgtype.Int4      `json:"deleted_by"`
	NombreTecnico      string           `json:"nombre_tecnico"`
	Categoria          string           `json:"categoria"`
}

func (q *Queries) GetProductoPadreByDescripcion(ctx context.Context, descripcion pgtype.Text) (GetProductoPadreByDescripcionRow, error) {
	row := q.db.QueryRow(ctx, getProductoPadreByDescripcion, descripcion)
	var i GetProductoPadreByDescripcionRow
	err := row.Scan(
		&i.ID,
		&i.CveProdIntegracion,
		&i.Descripcion,
		&i.FotoUrl,
		&i.FichaTecnica,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.NombreTecnico,
		&i.Categoria,
	)
	return i, err
}

const getVariante = `-- name: GetVariante :one
SELECT id, padre_id, sku, medida, precio_distribuidor, precio_lista, precio_publico, stock_actual, unidad_medida, lead_time_dias, especificaciones, categoria, subgrupo, modelo, tipo, marca, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM productos_variantes 
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetVariante(ctx context.Context, id int32) (ProductosVariante, error) {
	row := q.db.QueryRow(ctx, getVariante, id)
	var i ProductosVariante
	err := row.Scan(
		&i.ID,
		&i.PadreID,
		&i.Sku,
		&i.Medida,
		&i.PrecioDistribuidor,
		&i.PrecioLista,
		&i.PrecioPublico,
		&i.StockActual,
		&i.UnidadMedida,
		&i.LeadTimeDias,
		&i.Especificaciones,
		&i.Categoria,
		&i.Subgrupo,
		&i.Modelo,
		&i.Tipo,
		&i.Marca,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getVarianteBySKU = `-- name: GetVarianteBySKU :one
SELECT id, padre_id, sku, medida, precio_distribuidor, precio_lista, precio_publico, stock_actual, unidad_medida, lead_time_dias, especificaciones, categoria, subgrupo, modelo, tipo, marca, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM productos_variantes 
WHERE sku = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetVarianteBySKU(ctx context.Context, sku string) (ProductosVariante, error) {
	row := q.db.QueryRow(ctx, getVarianteBySKU, sku)
	var i ProductosVariante
	err := row.Scan(
		&i.ID,
		&i.PadreID,
		&i.Sku,
		&i.Medida,
		&i.PrecioDistribuidor,
		&i.PrecioLista,
		&i.PrecioPublico,
		&i.StockActual,
		&i.UnidadMedida,
		&i.LeadTimeDias,
		&i.Especificaciones,
		&i.Categoria,
		&i.Subgrupo,
		&i.Modelo,
		&i.Tipo,
		&i.Marca,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const listarProductosPadre = `-- name: ListarProductosPadre :many
SELECT p.id, p.cve_prod_integracion, p.descripcion, p.foto_url, p.ficha_tecnica, p.created_at, p.updated_at, p.deleted_at, p.created_by, p.updated_by, p.deleted_by, 
       COALESCE(pi.nom_prod, '') AS nombre_tecnico, 
       COALESCE(pi.cse_prod, '') AS categoria
FROM productos_padre p
LEFT JOIN productos_integracion pi ON p.cve_prod_integracion = pi.cve_prod
WHERE p.deleted_at IS NULL
`

type ListarProductosPadreRow struct {
	ID                 int32            `json:"id"`
	CveProdIntegracion pgtype.Text      `json:"cve_prod_integracion"`
	Descripcion        pgtype.Text      `json:"descripcion"`
	FotoUrl            pgtype.Text      `json:"foto_url"`
	FichaTecnica       pgtype.Text      `json:"ficha_tecnica"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	DeletedAt          pgtype.Timestamp `json:"deleted_at"`
	CreatedBy          pgtype.Int4      `json:"created_by"`
	UpdatedBy          pgtype.Int4      `json:"updated_by"`
	DeletedBy          pgtype.Int4      `json:"deleted_by"`
	NombreTecnico      string           `json:"nombre_tecnico"`
	Categoria          string           `json:"categoria"`
}

func (q *Queries) ListarProductosPadre(ctx context.Context) ([]ListarProductosPadreRow, error) {
	rows, err := q.db.Query(ctx, listarProductosPadre)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarProductosPadreRow
	for rows.Next() {
		var i ListarProductosPadreRow
		if err := rows.Scan(
			&i.ID,
			&i.CveProdIntegracion,
			&i.Descripcion,
			&i.FotoUrl,
			&i.FichaTecnica,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.NombreTecnico,
			&i.Categoria,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarVariantesPorPadre = `-- name: ListarVariantesPorPadre :many
SELECT id, padre_id, sku, medida, precio_distribuidor, precio_lista, precio_publico, stock_actual, unidad_medida, lead_time_dias, especificaciones, categoria, subgrupo, modelo, tipo, marca, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM productos_variantes 
WHERE padre_id = $1 AND deleted_at IS NULL
`

// Para mostrar todas las medidas de un mismo producto (cite: 184)
func (q *Queries) ListarVariantesPorPadre(ctx context.Context, padreID pgtype.Int4) ([]ProductosVariante, error) {
	rows, err := q.db.Query(ctx, listarVariantesPorPadre, padreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductosVariante
	for rows.Next() {
		var i ProductosVariante
		if err := rows.Scan(
			&i.ID,
			&i.PadreID,
			&i.Sku,
			&i.Medida,
			&i.PrecioDistribuidor,
			&i.PrecioLista,
			&i.PrecioPublico,
			&i.StockActual,
			&i.UnidadMedida,
			&i.LeadTimeDias,
			&i.Especificaciones,
			&i.Categoria,
			&i.Subgrupo,
			&i.Modelo,
			&i.Tipo,
			&i.Marca,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProductoPadre = `-- name: SoftDeleteProductoPadre :exec
UPDATE productos_padre
SET 
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2
WHERE id = $1
`

type SoftDeleteProductoPadreParams struct {
	ID        int32       `json:"id"`
	DeletedBy pgtype.Int4 `json:"deleted_by"`
}

// Borrado lógico del contenedor principal (afecta la visibilidad del catálogo)
func (q *Queries) SoftDeleteProductoPadre(ctx context.Context, arg SoftDeleteProductoPadreParams) error {
	_, err := q.db.Exec(ctx, softDeleteProductoPadre, arg.ID, arg.DeletedBy)
	return err
}

const softDeleteVariante = `-- name: SoftDeleteVariante :exec
UPDATE productos_variantes
SET 
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2
WHERE id = $1
`

type SoftDeleteVarianteParams struct {
	ID        int32       `json:"id"`
	DeletedBy pgtype.Int4 `json:"deleted_by"`
}

func (q *Queries) SoftDeleteVariante(ctx context.Context, arg SoftDeleteVarianteParams) error {
	_, err := q.db.Exec(ctx, softDeleteVariante, arg.ID, arg.DeletedBy)
	return err
}
