// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: productos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarProductoPadre = `-- name: ActualizarProductoPadre :one
UPDATE productos_padre
SET 
    nombre_tecnico = $2,
    descripcion = $3,
    categoria = $4,
    marca = $5,
    documentacion_url = $6,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $7
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, nombre_tecnico, descripcion, categoria, marca, documentacion_url, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type ActualizarProductoPadreParams struct {
	ID               int32       `json:"id"`
	NombreTecnico    string      `json:"nombre_tecnico"`
	Descripcion      pgtype.Text `json:"descripcion"`
	Categoria        string      `json:"categoria"`
	Marca            pgtype.Text `json:"marca"`
	DocumentacionUrl pgtype.Text `json:"documentacion_url"`
	UpdatedBy        pgtype.Int4 `json:"updated_by"`
}

func (q *Queries) ActualizarProductoPadre(ctx context.Context, arg ActualizarProductoPadreParams) (ProductosPadre, error) {
	row := q.db.QueryRow(ctx, actualizarProductoPadre,
		arg.ID,
		arg.NombreTecnico,
		arg.Descripcion,
		arg.Categoria,
		arg.Marca,
		arg.DocumentacionUrl,
		arg.UpdatedBy,
	)
	var i ProductosPadre
	err := row.Scan(
		&i.ID,
		&i.NombreTecnico,
		&i.Descripcion,
		&i.Categoria,
		&i.Marca,
		&i.DocumentacionUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const actualizarStock = `-- name: ActualizarStock :exec
UPDATE productos_variantes
SET 
    stock_actual = $2,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $3
WHERE id = $1
`

type ActualizarStockParams struct {
	ID          int32       `json:"id"`
	StockActual int32       `json:"stock_actual"`
	UpdatedBy   pgtype.Int4 `json:"updated_by"`
}

// Sincronización de inventario en tiempo real (cite: 43)
func (q *Queries) ActualizarStock(ctx context.Context, arg ActualizarStockParams) error {
	_, err := q.db.Exec(ctx, actualizarStock, arg.ID, arg.StockActual, arg.UpdatedBy)
	return err
}

const crearProductoPadre = `-- name: CrearProductoPadre :one


INSERT INTO productos_padre (
    nombre_tecnico, 
    descripcion, 
    categoria, 
    marca, 
    documentacion_url, 
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, nombre_tecnico, descripcion, categoria, marca, documentacion_url, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CrearProductoPadreParams struct {
	NombreTecnico    string      `json:"nombre_tecnico"`
	Descripcion      pgtype.Text `json:"descripcion"`
	Categoria        string      `json:"categoria"`
	Marca            pgtype.Text `json:"marca"`
	DocumentacionUrl pgtype.Text `json:"documentacion_url"`
	CreatedBy        pgtype.Int4 `json:"created_by"`
}

// internal/sql/productos.sql
// ==========================================
// CRUD PRODUCTOS PADRE (Contenedores)
// ==========================================
func (q *Queries) CrearProductoPadre(ctx context.Context, arg CrearProductoPadreParams) (ProductosPadre, error) {
	row := q.db.QueryRow(ctx, crearProductoPadre,
		arg.NombreTecnico,
		arg.Descripcion,
		arg.Categoria,
		arg.Marca,
		arg.DocumentacionUrl,
		arg.CreatedBy,
	)
	var i ProductosPadre
	err := row.Scan(
		&i.ID,
		&i.NombreTecnico,
		&i.Descripcion,
		&i.Categoria,
		&i.Marca,
		&i.DocumentacionUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const crearVariante = `-- name: CrearVariante :one

INSERT INTO productos_variantes (
    padre_id, 
    sku, 
    medida, 
    precio_lista, 
    stock_actual, 
    unidad_medida, 
    lead_time_dias, 
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, padre_id, sku, medida, precio_lista, stock_actual, unidad_medida, lead_time_dias, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CrearVarianteParams struct {
	PadreID      pgtype.Int4    `json:"padre_id"`
	Sku          string         `json:"sku"`
	Medida       pgtype.Text    `json:"medida"`
	PrecioLista  pgtype.Numeric `json:"precio_lista"`
	StockActual  int32          `json:"stock_actual"`
	UnidadMedida string         `json:"unidad_medida"`
	LeadTimeDias pgtype.Int4    `json:"lead_time_dias"`
	CreatedBy    pgtype.Int4    `json:"created_by"`
}

// ==========================================
// CRUD VARIANTES (SKUs Específicos)
// ==========================================
// Registra una variante (ej. Tornillo de 1/2") ligada a un Padre (cite: 187, 191)
func (q *Queries) CrearVariante(ctx context.Context, arg CrearVarianteParams) (ProductosVariante, error) {
	row := q.db.QueryRow(ctx, crearVariante,
		arg.PadreID,
		arg.Sku,
		arg.Medida,
		arg.PrecioLista,
		arg.StockActual,
		arg.UnidadMedida,
		arg.LeadTimeDias,
		arg.CreatedBy,
	)
	var i ProductosVariante
	err := row.Scan(
		&i.ID,
		&i.PadreID,
		&i.Sku,
		&i.Medida,
		&i.PrecioLista,
		&i.StockActual,
		&i.UnidadMedida,
		&i.LeadTimeDias,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getProductoPadre = `-- name: GetProductoPadre :one
SELECT id, nombre_tecnico, descripcion, categoria, marca, documentacion_url, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM productos_padre 
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetProductoPadre(ctx context.Context, id int32) (ProductosPadre, error) {
	row := q.db.QueryRow(ctx, getProductoPadre, id)
	var i ProductosPadre
	err := row.Scan(
		&i.ID,
		&i.NombreTecnico,
		&i.Descripcion,
		&i.Categoria,
		&i.Marca,
		&i.DocumentacionUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getVarianteBySKU = `-- name: GetVarianteBySKU :one
SELECT id, padre_id, sku, medida, precio_lista, stock_actual, unidad_medida, lead_time_dias, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM productos_variantes 
WHERE sku = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetVarianteBySKU(ctx context.Context, sku string) (ProductosVariante, error) {
	row := q.db.QueryRow(ctx, getVarianteBySKU, sku)
	var i ProductosVariante
	err := row.Scan(
		&i.ID,
		&i.PadreID,
		&i.Sku,
		&i.Medida,
		&i.PrecioLista,
		&i.StockActual,
		&i.UnidadMedida,
		&i.LeadTimeDias,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const listarProductosPadre = `-- name: ListarProductosPadre :many
SELECT id, nombre_tecnico, descripcion, categoria, marca, documentacion_url, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM productos_padre 
WHERE deleted_at IS NULL
`

func (q *Queries) ListarProductosPadre(ctx context.Context) ([]ProductosPadre, error) {
	rows, err := q.db.Query(ctx, listarProductosPadre)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductosPadre
	for rows.Next() {
		var i ProductosPadre
		if err := rows.Scan(
			&i.ID,
			&i.NombreTecnico,
			&i.Descripcion,
			&i.Categoria,
			&i.Marca,
			&i.DocumentacionUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarVariantesPorPadre = `-- name: ListarVariantesPorPadre :many
SELECT id, padre_id, sku, medida, precio_lista, stock_actual, unidad_medida, lead_time_dias, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM productos_variantes 
WHERE padre_id = $1 AND deleted_at IS NULL
`

// Para mostrar todas las medidas de un mismo producto (cite: 184)
func (q *Queries) ListarVariantesPorPadre(ctx context.Context, padreID pgtype.Int4) ([]ProductosVariante, error) {
	rows, err := q.db.Query(ctx, listarVariantesPorPadre, padreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductosVariante
	for rows.Next() {
		var i ProductosVariante
		if err := rows.Scan(
			&i.ID,
			&i.PadreID,
			&i.Sku,
			&i.Medida,
			&i.PrecioLista,
			&i.StockActual,
			&i.UnidadMedida,
			&i.LeadTimeDias,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProductoPadre = `-- name: SoftDeleteProductoPadre :exec
UPDATE productos_padre
SET 
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2
WHERE id = $1
`

type SoftDeleteProductoPadreParams struct {
	ID        int32       `json:"id"`
	DeletedBy pgtype.Int4 `json:"deleted_by"`
}

// Borrado lógico del contenedor principal (afecta la visibilidad del catálogo)
func (q *Queries) SoftDeleteProductoPadre(ctx context.Context, arg SoftDeleteProductoPadreParams) error {
	_, err := q.db.Exec(ctx, softDeleteProductoPadre, arg.ID, arg.DeletedBy)
	return err
}

const softDeleteVariante = `-- name: SoftDeleteVariante :exec
UPDATE productos_variantes
SET 
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2
WHERE id = $1
`

type SoftDeleteVarianteParams struct {
	ID        int32       `json:"id"`
	DeletedBy pgtype.Int4 `json:"deleted_by"`
}

func (q *Queries) SoftDeleteVariante(ctx context.Context, arg SoftDeleteVarianteParams) error {
	_, err := q.db.Exec(ctx, softDeleteVariante, arg.ID, arg.DeletedBy)
	return err
}
