// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: solicitud_registro.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarSolicitudEstado = `-- name: ActualizarSolicitudEstado :exec
UPDATE solicitud_registro_nuevo_cliente
SET 
    solicitud_estado = $2,
    observacion = $3,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $4
WHERE id = $1
`

type ActualizarSolicitudEstadoParams struct {
	ID              int32       `json:"id"`
	SolicitudEstado string      `json:"solicitud_estado"`
	Observacion     pgtype.Text `json:"observacion"`
	UpdatedBy       pgtype.Int4 `json:"updated_by"`
}

func (q *Queries) ActualizarSolicitudEstado(ctx context.Context, arg ActualizarSolicitudEstadoParams) error {
	_, err := q.db.Exec(ctx, actualizarSolicitudEstado,
		arg.ID,
		arg.SolicitudEstado,
		arg.Observacion,
		arg.UpdatedBy,
	)
	return err
}

const buscarSolicitudByCP = `-- name: BuscarSolicitudByCP :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE cp = $1 AND deleted_at IS NULL
`

func (q *Queries) BuscarSolicitudByCP(ctx context.Context, cp string) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, buscarSolicitudByCP, cp)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const buscarSolicitudByCalle = `-- name: BuscarSolicitudByCalle :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE calle = $1 AND deleted_at IS NULL
`

func (q *Queries) BuscarSolicitudByCalle(ctx context.Context, calle string) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, buscarSolicitudByCalle, calle)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const buscarSolicitudByCiudad = `-- name: BuscarSolicitudByCiudad :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE ciudad = $1 AND deleted_at IS NULL
`

func (q *Queries) BuscarSolicitudByCiudad(ctx context.Context, ciudad string) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, buscarSolicitudByCiudad, ciudad)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const buscarSolicitudByColonia = `-- name: BuscarSolicitudByColonia :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE colonia = $1 AND deleted_at IS NULL
`

func (q *Queries) BuscarSolicitudByColonia(ctx context.Context, colonia string) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, buscarSolicitudByColonia, colonia)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const buscarSolicitudByCorreoContacto = `-- name: BuscarSolicitudByCorreoContacto :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE correo_contacto = $1 AND deleted_at IS NULL
`

func (q *Queries) BuscarSolicitudByCorreoContacto(ctx context.Context, correoContacto string) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, buscarSolicitudByCorreoContacto, correoContacto)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const buscarSolicitudByEstado = `-- name: BuscarSolicitudByEstado :many
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE solicitud_estado = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) BuscarSolicitudByEstado(ctx context.Context, solicitudEstado string) ([]SolicitudRegistroNuevoCliente, error) {
	rows, err := q.db.Query(ctx, buscarSolicitudByEstado, solicitudEstado)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SolicitudRegistroNuevoCliente
	for rows.Next() {
		var i SolicitudRegistroNuevoCliente
		if err := rows.Scan(
			&i.ID,
			&i.NombreComercial,
			&i.RazonSocial,
			&i.Rfc,
			&i.TipoContribuyente,
			&i.SolicitudEstado,
			&i.Observacion,
			&i.Comentarios,
			&i.ConstanciaSatUrl,
			&i.Calle,
			&i.Numero,
			&i.Colonia,
			&i.Ciudad,
			&i.Estado,
			&i.Cp,
			&i.NombreContacto,
			&i.PuestoContacto,
			&i.CorreoContacto,
			&i.TelefonoContacto,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarSolicitudByNombreComercial = `-- name: BuscarSolicitudByNombreComercial :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE nombre_comercial = $1 AND deleted_at IS NULL
`

func (q *Queries) BuscarSolicitudByNombreComercial(ctx context.Context, nombreComercial string) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, buscarSolicitudByNombreComercial, nombreComercial)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const buscarSolicitudByNombreContacto = `-- name: BuscarSolicitudByNombreContacto :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE nombre_contacto = $1 AND deleted_at IS NULL
`

func (q *Queries) BuscarSolicitudByNombreContacto(ctx context.Context, nombreContacto string) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, buscarSolicitudByNombreContacto, nombreContacto)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const buscarSolicitudByNumero = `-- name: BuscarSolicitudByNumero :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE numero = $1 AND deleted_at IS NULL
`

func (q *Queries) BuscarSolicitudByNumero(ctx context.Context, numero string) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, buscarSolicitudByNumero, numero)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const buscarSolicitudByPuestoContacto = `-- name: BuscarSolicitudByPuestoContacto :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE puesto_contacto = $1 AND deleted_at IS NULL
`

func (q *Queries) BuscarSolicitudByPuestoContacto(ctx context.Context, puestoContacto string) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, buscarSolicitudByPuestoContacto, puestoContacto)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const buscarSolicitudByRFC = `-- name: BuscarSolicitudByRFC :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE rfc = $1 AND deleted_at IS NULL
`

func (q *Queries) BuscarSolicitudByRFC(ctx context.Context, rfc string) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, buscarSolicitudByRFC, rfc)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const buscarSolicitudByRazonSocial = `-- name: BuscarSolicitudByRazonSocial :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE razon_social = $1 AND deleted_at IS NULL
`

func (q *Queries) BuscarSolicitudByRazonSocial(ctx context.Context, razonSocial string) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, buscarSolicitudByRazonSocial, razonSocial)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const buscarSolicitudByTelefonoContacto = `-- name: BuscarSolicitudByTelefonoContacto :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE telefono_contacto = $1 AND deleted_at IS NULL
`

func (q *Queries) BuscarSolicitudByTelefonoContacto(ctx context.Context, telefonoContacto string) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, buscarSolicitudByTelefonoContacto, telefonoContacto)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const crearSolicitudRegistroNuevoCliente = `-- name: CrearSolicitudRegistroNuevoCliente :one
INSERT INTO solicitud_registro_nuevo_cliente (
    nombre_comercial,
    razon_social,
    rfc,
    tipo_contribuyente,
    calle,
    numero,
    colonia,
    ciudad,
    estado,
    cp,
    nombre_contacto,
    puesto_contacto,
    correo_contacto,
    telefono_contacto,
    comentarios,
    constancia_sat_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id
`

type CrearSolicitudRegistroNuevoClienteParams struct {
	NombreComercial   string      `json:"nombre_comercial"`
	RazonSocial       string      `json:"razon_social"`
	Rfc               string      `json:"rfc"`
	TipoContribuyente string      `json:"tipo_contribuyente"`
	Calle             string      `json:"calle"`
	Numero            string      `json:"numero"`
	Colonia           string      `json:"colonia"`
	Ciudad            string      `json:"ciudad"`
	Estado            string      `json:"estado"`
	Cp                string      `json:"cp"`
	NombreContacto    string      `json:"nombre_contacto"`
	PuestoContacto    string      `json:"puesto_contacto"`
	CorreoContacto    string      `json:"correo_contacto"`
	TelefonoContacto  string      `json:"telefono_contacto"`
	Comentarios       pgtype.Text `json:"comentarios"`
	ConstanciaSatUrl  pgtype.Text `json:"constancia_sat_url"`
}

func (q *Queries) CrearSolicitudRegistroNuevoCliente(ctx context.Context, arg CrearSolicitudRegistroNuevoClienteParams) (int32, error) {
	row := q.db.QueryRow(ctx, crearSolicitudRegistroNuevoCliente,
		arg.NombreComercial,
		arg.RazonSocial,
		arg.Rfc,
		arg.TipoContribuyente,
		arg.Calle,
		arg.Numero,
		arg.Colonia,
		arg.Ciudad,
		arg.Estado,
		arg.Cp,
		arg.NombreContacto,
		arg.PuestoContacto,
		arg.CorreoContacto,
		arg.TelefonoContacto,
		arg.Comentarios,
		arg.ConstanciaSatUrl,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listarSolicitudesPendientes = `-- name: ListarSolicitudesPendientes :many
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE solicitud_estado = 'Pendiente' AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListarSolicitudesPendientes(ctx context.Context) ([]SolicitudRegistroNuevoCliente, error) {
	rows, err := q.db.Query(ctx, listarSolicitudesPendientes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SolicitudRegistroNuevoCliente
	for rows.Next() {
		var i SolicitudRegistroNuevoCliente
		if err := rows.Scan(
			&i.ID,
			&i.NombreComercial,
			&i.RazonSocial,
			&i.Rfc,
			&i.TipoContribuyente,
			&i.SolicitudEstado,
			&i.Observacion,
			&i.Comentarios,
			&i.ConstanciaSatUrl,
			&i.Calle,
			&i.Numero,
			&i.Colonia,
			&i.Ciudad,
			&i.Estado,
			&i.Cp,
			&i.NombreContacto,
			&i.PuestoContacto,
			&i.CorreoContacto,
			&i.TelefonoContacto,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarTodasLasSolicitudes = `-- name: ListarTodasLasSolicitudes :many
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListarTodasLasSolicitudes(ctx context.Context) ([]SolicitudRegistroNuevoCliente, error) {
	rows, err := q.db.Query(ctx, listarTodasLasSolicitudes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SolicitudRegistroNuevoCliente
	for rows.Next() {
		var i SolicitudRegistroNuevoCliente
		if err := rows.Scan(
			&i.ID,
			&i.NombreComercial,
			&i.RazonSocial,
			&i.Rfc,
			&i.TipoContribuyente,
			&i.SolicitudEstado,
			&i.Observacion,
			&i.Comentarios,
			&i.ConstanciaSatUrl,
			&i.Calle,
			&i.Numero,
			&i.Colonia,
			&i.Ciudad,
			&i.Estado,
			&i.Cp,
			&i.NombreContacto,
			&i.PuestoContacto,
			&i.CorreoContacto,
			&i.TelefonoContacto,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerSolicitudByID = `-- name: ObtenerSolicitudByID :one
SELECT id, nombre_comercial, razon_social, rfc, tipo_contribuyente, solicitud_estado, observacion, comentarios, constancia_sat_url, calle, numero, colonia, ciudad, estado, cp, nombre_contacto, puesto_contacto, correo_contacto, telefono_contacto, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM solicitud_registro_nuevo_cliente
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ObtenerSolicitudByID(ctx context.Context, id int32) (SolicitudRegistroNuevoCliente, error) {
	row := q.db.QueryRow(ctx, obtenerSolicitudByID, id)
	var i SolicitudRegistroNuevoCliente
	err := row.Scan(
		&i.ID,
		&i.NombreComercial,
		&i.RazonSocial,
		&i.Rfc,
		&i.TipoContribuyente,
		&i.SolicitudEstado,
		&i.Observacion,
		&i.Comentarios,
		&i.ConstanciaSatUrl,
		&i.Calle,
		&i.Numero,
		&i.Colonia,
		&i.Ciudad,
		&i.Estado,
		&i.Cp,
		&i.NombreContacto,
		&i.PuestoContacto,
		&i.CorreoContacto,
		&i.TelefonoContacto,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteSolicitud = `-- name: SoftDeleteSolicitud :exec
UPDATE solicitud_registro_nuevo_cliente
SET 
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2
WHERE id = $1
`

type SoftDeleteSolicitudParams struct {
	ID        int32       `json:"id"`
	DeletedBy pgtype.Int4 `json:"deleted_by"`
}

func (q *Queries) SoftDeleteSolicitud(ctx context.Context, arg SoftDeleteSolicitudParams) error {
	_, err := q.db.Exec(ctx, softDeleteSolicitud, arg.ID, arg.DeletedBy)
	return err
}
