// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usuarios.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarPassword = `-- name: ActualizarPassword :exec
UPDATE usuarios
SET 
    password_hash = $2,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $1
WHERE id = $1
`

type ActualizarPasswordParams struct {
	UpdatedBy    pgtype.Int4 `json:"updated_by"`
	PasswordHash string      `json:"password_hash"`
}

// Query específica para cambio de contraseña por seguridad
func (q *Queries) ActualizarPassword(ctx context.Context, arg ActualizarPasswordParams) error {
	_, err := q.db.Exec(ctx, actualizarPassword, arg.UpdatedBy, arg.PasswordHash)
	return err
}

const actualizarUsuario = `-- name: ActualizarUsuario :one
UPDATE usuarios
SET 
    email = $2,
    rol = $3,
    is_active = $4,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, cliente_id, email, password_hash, rol, is_active, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type ActualizarUsuarioParams struct {
	ID        int32       `json:"id"`
	Email     string      `json:"email"`
	Rol       string      `json:"rol"`
	IsActive  pgtype.Bool `json:"is_active"`
	UpdatedBy pgtype.Int4 `json:"updated_by"`
}

// Permite cambiar rol, email o estado de activación
func (q *Queries) ActualizarUsuario(ctx context.Context, arg ActualizarUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, actualizarUsuario,
		arg.ID,
		arg.Email,
		arg.Rol,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const crearUsuario = `-- name: CrearUsuario :one
INSERT INTO usuarios (
    cliente_id, 
    email, 
    password_hash, 
    rol, 
    is_active, 
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, cliente_id, email, password_hash, rol, is_active, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by
`

type CrearUsuarioParams struct {
	ClienteID    pgtype.Int4 `json:"cliente_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Rol          string      `json:"rol"`
	IsActive     pgtype.Bool `json:"is_active"`
	CreatedBy    pgtype.Int4 `json:"created_by"`
}

// Registra un nuevo usuario (Staff o Cliente).
// Si cliente_id es NULL, es personal de Alialloys.
func (q *Queries) CrearUsuario(ctx context.Context, arg CrearUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, crearUsuario,
		arg.ClienteID,
		arg.Email,
		arg.PasswordHash,
		arg.Rol,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getUsuarioByEmail = `-- name: GetUsuarioByEmail :one
SELECT id, cliente_id, email, password_hash, rol, is_active, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM usuarios 
WHERE email = $1 AND deleted_at IS NULL LIMIT 1
`

// Fundamental para el flujo de Login
func (q *Queries) GetUsuarioByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUsuarioByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getUsuarioByID = `-- name: GetUsuarioByID :one
SELECT id, cliente_id, email, password_hash, rol, is_active, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM usuarios 
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUsuarioByID(ctx context.Context, id int32) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUsuarioByID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const listarUsuarios = `-- name: ListarUsuarios :many
SELECT id, cliente_id, email, password_hash, rol, is_active, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM usuarios 
WHERE deleted_at IS NULL 
ORDER BY created_at DESC
`

// Lista todos los usuarios no borrados para el panel de control
func (q *Queries) ListarUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.Query(ctx, listarUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.Email,
			&i.PasswordHash,
			&i.Rol,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarUsuariosPorCliente = `-- name: ListarUsuariosPorCliente :many
SELECT id, cliente_id, email, password_hash, rol, is_active, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by FROM usuarios 
WHERE cliente_id = $1 AND deleted_at IS NULL
`

// Obtiene todos los contactos/compradores de una empresa específica
func (q *Queries) ListarUsuariosPorCliente(ctx context.Context, clienteID pgtype.Int4) ([]Usuario, error) {
	rows, err := q.db.Query(ctx, listarUsuariosPorCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.Email,
			&i.PasswordHash,
			&i.Rol,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUsuario = `-- name: SoftDeleteUsuario :exec
UPDATE usuarios
SET 
    deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2,
    is_active = FALSE
WHERE id = $1
`

type SoftDeleteUsuarioParams struct {
	ID        int32       `json:"id"`
	DeletedBy pgtype.Int4 `json:"deleted_by"`
}

// Borrado lógico registrando quién ejecutó la baja
func (q *Queries) SoftDeleteUsuario(ctx context.Context, arg SoftDeleteUsuarioParams) error {
	_, err := q.db.Exec(ctx, softDeleteUsuario, arg.ID, arg.DeletedBy)
	return err
}
